/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Soufiane KHIAT
 * SPDX-License-Identifier: MIT
 *
 * alwan_deterministic.h - bit-exact polynomial implementations for
 * primitives that would otherwise call libm.
 *
 * Active only when `ALWAN_DETERMINISTIC=1` is defined. Each function
 * here approximates a transcendental over its valid colour-science
 * range with a polynomial whose coefficients are committed to source
 * (generated by alwan_dev/gendata/gen_*.py), then evaluated via
 * Horner's method with FMA contraction explicitly disabled.
 *
 * Two guarantees together give cross-platform bit-exactness:
 *
 *   1. The polynomial is fully specified (coefficients in
 *      alwan_det_*_coeffs.h, no platform-dependent input).
 *   2. `#pragma STDC FP_CONTRACT OFF` blocks the compiler from
 *      fusing `a*b + c` into a single-rounding FMA, which would
 *      otherwise differ between x86 (with/without -mfma) and
 *      aarch64 (FMA mandatory).
 *
 * The polynomial does NOT match libm bit-for-bit. It approximates
 * the same mathematical function within a documented error budget
 * (the sRGB and BT.2020 transfer functions land at 3.3e-16, the f64
 * rounding floor, since their power branch became alwan_det_pow_pos;
 * see docs/determinism.md for the per-family table). The point is
 * that *every* deterministic build, on every platform, returns the
 * same bytes for the same inputs -- that's what
 * cross-platform-determinism CI verifies via output hashing.
 *
 * Currently covered:
 *   - sRGB     OETF/EOTF
 *   - BT.2020  OETF/EOTF (also valid for BT.709 -- same constants)
 *
 * Pipeline (PQ, HLG, Lab cube root, ACES splines, ...) follow in
 * later phases -- see docs/determinism.md
 */

#ifndef ALWAN_DETERMINISTIC_H
#define ALWAN_DETERMINISTIC_H

/* Block FMA contraction inside this header. The CMake build also
 * passes `-ffp-contract=off` (clang/gcc) or `/fp:precise` (MSVC) for
 * defense in depth; the per-file pragma is belt-and-suspenders so a
 * downstream consumer can't accidentally re-fuse our polynomial
 * evaluations. Each compiler needs its own spelling:
 *   - clang implements the ISO C `#pragma STDC FP_CONTRACT`.
 *   - GCC parses but does NOT implement that pragma -- it warns
 *     -Wunknown-pragmas ("ignoring '#pragma STDC FP_CONTRACT'"), which
 *     -Werror turns fatal. GCC's equivalent is `#pragma GCC optimize
 *     ("fp-contract=off")`, which overrides even a command-line
 *     -ffp-contract=fast (verified on gcc 13). ICC is excluded: it
 *     defines __GNUC__ but does not honor this pragma cleanly.
 *   - MSVC's STDC support is incomplete -- its equivalent is
 *     `#pragma fp_contract(off)` with different syntax.
 * This header is only included in deterministic builds (see
 * alwan_math.h), so the TU-wide pragma never touches the fast path. */
#if ALWAN_BACKEND == ALWAN_BACKEND_C
#if defined(__clang__)
#  pragma STDC FP_CONTRACT OFF
#elif defined(__GNUC__) && !defined(__INTEL_COMPILER)
#  pragma GCC optimize ("fp-contract=off")
#elif defined(_MSC_VER)
#  pragma fp_contract(off)
#endif
#elif ALWAN_BACKEND == ALWAN_BACKEND_OPENCL
/* OpenCL's own spelling of the same contract. The C pragma above is spelled
 * `STDC`, this one `OPENCL`, and both say the compiler may not fuse a*b+c into
 * a single-rounding fma. HLSL and GLSL have no pragma for it and use `precise`
 * on the accumulator instead. */
#pragma OPENCL FP_CONTRACT OFF
#endif /* per-backend contraction control */

#include "../alwan_types.h"
#include "alwan_det_srgb_coeffs.h"
#include "alwan_det_bt2020_coeffs.h"
#include "alwan_det_math_coeffs.h"
#include "alwan_det_trig_coeffs.h"

/* frexp / ldexp are libm but pure IEEE-754 bit manipulation, not
 * transcendental approximation, so they're bit-identical across
 * platforms. Used by alwan_det_log2 / alwan_det_exp2 below for
 * argument reduction. (GPU backends use the HLSL frexp/ldexp intrinsics.) */
#if ALWAN_BACKEND == ALWAN_BACKEND_C
#include <math.h>
#endif

/* The C path defines the full f32+f64 suffixed set (pointer-Horner + libm
 * frexp). The GPU path can't take arrays by pointer or call libm, so it gets an
 * inlined single-precision subset at the end of this header. */
#if ALWAN_BACKEND == ALWAN_BACKEND_C

/* ----------------------------------------------------------------
 * Horner evaluation -- explicit `mul; add` so FP_CONTRACT OFF actually
 * has something to refuse to fuse.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64
alwan_det_horner_f64(alwan_f64 const *coeffs, int degree, alwan_f64 x) {
    alwan_f64 acc = coeffs[degree];
    for (int i = degree - 1; i >= 0; i--) {
        const alwan_f64 t = acc * x;        /* round 1 */
        acc = t + coeffs[i];                /* round 2 -- never fused */
    }
    return acc;
}

ALWAN_INLINE alwan_f32
alwan_det_horner_f32(alwan_f32 const *coeffs, int degree, alwan_f32 x) {
    alwan_f32 acc = coeffs[degree];
    for (int i = degree - 1; i >= 0; i--) {
        const alwan_f32 t = acc * x;
        acc = t + coeffs[i];
    }
    return acc;
}

/* Domain normalisation: maps x in [lo, hi] to u in [-1, 1]. */
ALWAN_INLINE alwan_f64 alwan_det_normalize_f64(alwan_f64 x, alwan_f64 lo, alwan_f64 hi) {
    return 2.0 * (x - lo) / (hi - lo) - 1.0;
}
ALWAN_INLINE alwan_f32 alwan_det_normalize_f32(alwan_f32 x, alwan_f32 lo, alwan_f32 hi) {
    return 2.0f * (x - lo) / (hi - lo) - 1.0f;
}

/* ----------------------------------------------------------------
 * Argument-reduced log2 / exp2 / pow_pos.
 *
 * log2(x) for x > 0:
 *   x = m * 2^k   (frexp; m in [0.5, 1.0), k integer)
 *   log2(x) = k + log2(m), polynomial fits log2(m) on [0.5, 1.0].
 *
 * exp2(t) for any t:
 *   t = int_t + frac_t   (frac_t in [0, 1))
 *   exp2(t) = ldexp(exp2(frac_t), int_t), polynomial fits exp2 on [0, 1].
 *
 * pow_pos(x, e) for x > 0:
 *   exp2(e * log2(x)).
 *
 * For x <= 0 the result is 0 (matching IEEE/libm pow conventions for
 * x = 0; for negative x it's a domain error, which we treat as 0
 * deterministically rather than NaN).
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan_det_log2_f64(alwan_f64 x) {
    if (x <= 0.0) return -INFINITY;  /* IEEE convention */
    int k;
    const alwan_f64 m = frexp(x, &k);
    /* m in [0.5, 1.0); normalise to u in [-1, 1] for the polynomial.
     * The polynomial is log2(m)/(m-1), not log2(m): the quotient is
     * analytic and nonzero across the domain, so it can be fitted by a
     * relative-error minimax, which log2 itself cannot be because of its
     * zero at m = 1. Reconstructing costs one multiply and buys four
     * orders of accuracy. See gendata/gen_math_minimax.wls. */
    const alwan_f64 u = alwan_det_normalize_f64(m, 0.5, 1.0);
    return (alwan_f64)k + (m - 1.0) * alwan_det_horner_f64(
        alwan_det_log2_coeffs_f64, ALWAN_DET_LOG2_DEGREE, u);
}

ALWAN_INLINE alwan_f32 alwan_det_log2_f32(alwan_f32 x) {
    if (x <= 0.0f) return -INFINITY;
    int k;
    const alwan_f32 m = frexpf(x, &k);
    const alwan_f32 u = alwan_det_normalize_f32(m, 0.5f, 1.0f);
    return (alwan_f32)k + (m - 1.0f) * alwan_det_horner_f32(
        alwan_det_log2_coeffs_f32, ALWAN_DET_LOG2_DEGREE, u);
}

ALWAN_INLINE alwan_f64 alwan_det_exp2_f64(alwan_f64 t) {
    /* Split t into integer and fractional parts. floor() works for
     * negative t too (frac stays in [0, 1)). */
    const alwan_f64 int_part = floor(t);
    const alwan_f64 frac_part = t - int_part;
    const alwan_f64 u = alwan_det_normalize_f64(frac_part, 0.0, 1.0);
    const alwan_f64 exp2_frac = alwan_det_horner_f64(
        alwan_det_exp2_coeffs_f64, ALWAN_DET_EXP2_DEGREE, u);
    return ldexp(exp2_frac, (int)int_part);
}

ALWAN_INLINE alwan_f32 alwan_det_exp2_f32(alwan_f32 t) {
    const alwan_f32 int_part = floorf(t);
    const alwan_f32 frac_part = t - int_part;
    const alwan_f32 u = alwan_det_normalize_f32(frac_part, 0.0f, 1.0f);
    const alwan_f32 exp2_frac = alwan_det_horner_f32(
        alwan_det_exp2_coeffs_f32, ALWAN_DET_EXP2_DEGREE, u);
    return ldexpf(exp2_frac, (int)int_part);
}

ALWAN_INLINE alwan_f64 alwan_det_log_f64(alwan_f64 x) {
    /* ln(x) = log2(x) * ln(2). The constant 0.6931... is exact in f64. */
    return alwan_det_log2_f64(x) * 0.69314718055994530941723212145817657;
}
ALWAN_INLINE alwan_f32 alwan_det_log_f32(alwan_f32 x) {
    return alwan_det_log2_f32(x) * 0.69314718055994530941723212145817657f;
}

ALWAN_INLINE alwan_f64 alwan_det_exp_f64(alwan_f64 x) {
    /* e^x = 2^(x / ln(2)) = 2^(x * 1.4426950...). */
    return alwan_det_exp2_f64(x * 1.4426950408889634073599246810018922);
}
ALWAN_INLINE alwan_f32 alwan_det_exp_f32(alwan_f32 x) {
    return alwan_det_exp2_f32(x * 1.4426950408889634073599246810018922f);
}

/* pow(x, e) for positive base x. For x = 0 returns 0. For x < 0
 * returns 0 (det-mode convention; libm returns NaN for non-integer
 * exponents). */
ALWAN_INLINE alwan_f64 alwan_det_pow_pos_f64(alwan_f64 x, alwan_f64 e) {
    if (x <= 0.0) return 0.0;
    return alwan_det_exp2_f64(e * alwan_det_log2_f64(x));
}
ALWAN_INLINE alwan_f32 alwan_det_pow_pos_f32(alwan_f32 x, alwan_f32 e) {
    if (x <= 0.0f) return 0.0f;
    return alwan_det_exp2_f32(e * alwan_det_log2_f32(x));
}

/* Cube root via pow_pos. Handles negative x by sign-preservation
 * (matches libm cbrt behaviour). */
ALWAN_INLINE alwan_f64 alwan_det_cbrt_f64(alwan_f64 x) {
    if (x == 0.0) return 0.0;
    const alwan_f64 a = (x < 0.0) ? -x : x;
    const alwan_f64 r = alwan_det_pow_pos_f64(a, 1.0 / 3.0);
    return (x < 0.0) ? -r : r;
}
ALWAN_INLINE alwan_f32 alwan_det_cbrt_f32(alwan_f32 x) {
    if (x == 0.0f) return 0.0f;
    const alwan_f32 a = (x < 0.0f) ? -x : x;
    const alwan_f32 r = alwan_det_pow_pos_f32(a, 1.0f / 3.0f);
    return (x < 0.0f) ? -r : r;
}

/* ----------------------------------------------------------------
 * The angle family: sin, cos, tan, atan, atan2, acos, plus log10 and tanh.
 *
 * These are what stood between the determinism contract and every hue channel
 * in the library. Coefficients are in alwan_det_trig_coeffs.h, minimax-fitted
 * at 60 digits; parity is factored out, so
 *
 *   sin(r)  = r * P(r*r)   cos(r) = Q(r*r)   for |r| <= pi/4
 *   atan(s) = s * R(s*s)                     for |s| <= tan(pi/8)
 *
 * and sin(0), atan(0) are exactly 0. Every fit sits three or more orders below
 * f64 epsilon, so what you get back is limited by Horner rounding: measured
 * against libm, 0.5 ULP for sin and cos and 1 ULP for atan.
 *
 * log10 and tanh need no polynomial of their own. They are exact identities
 * over the log2/exp2 pair above, so they inherit its determinism for free.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan_det_log10_f64(alwan_f64 x) {
    return alwan_det_log2_f64(x) * ALWAN_DET_LOG10_2;
}
ALWAN_INLINE alwan_f32 alwan_det_log10_f32(alwan_f32 x) {
    return alwan_det_log2_f32(x) * (alwan_f32)ALWAN_DET_LOG10_2;
}

/* tanh via the negative exponential, so the argument to exp is never positive:
 * e^-2|x| stays in (0, 1], nothing overflows, and large |x| saturates to +-1 by
 * construction rather than by a magnitude test. */
ALWAN_INLINE alwan_f64 alwan_det_tanh_f64(alwan_f64 x) {
    /* Computing from |x| and restoring the sign makes this exactly odd, except
     * at the origin: alwan_det_exp2(0) carries the polynomial's own residual, so
     * (1-e)/(1+e) lands about 2e-15 off zero rather than on it. Returning x
     * itself there costs one compare, keeps the signed zero, and is what makes
     * tanh odd everywhere rather than almost everywhere. */
    if (x == 0.0) return x;
    {
    const alwan_f64 a = (x < 0.0) ? -x : x;
    const alwan_f64 e = alwan_det_exp_f64(-2.0 * a);
    const alwan_f64 t = (1.0 - e) / (1.0 + e);
    return (x < 0.0) ? -t : t;
    }
}
ALWAN_INLINE alwan_f32 alwan_det_tanh_f32(alwan_f32 x) {
    if (x == 0.0f) return x;
    {
    const alwan_f32 a = (x < 0.0f) ? -x : x;
    const alwan_f32 e = alwan_det_exp_f32(-2.0f * a);
    const alwan_f32 t = (1.0f - e) / (1.0f + e);
    return (x < 0.0f) ? -t : t;
    }
}

/* Cody-Waite reduction: x = n*(pi/2) + r with |r| <= pi/4. Writes n mod 4 to
 * `quadrant` and returns r. pi/2 is subtracted in three parts whose leading two
 * have trailing zero mantissa bits, so n*hi and n*mid are exact and the only
 * rounding lands in the lo term, where it cannot cancel against anything.
 *
 * The quadrant is taken as fn - 4*floor(fn/4) in floating point rather than by
 * casting to an integer, so a large |x| cannot overflow the cast. Accuracy
 * still degrades once |x| passes roughly 2^40, as it does for any Cody-Waite
 * reduction; libm switches to Payne-Hanek there and this does not. Colour
 * science works in hue angles, so the reduction never sees such a value. */
ALWAN_INLINE alwan_f64 alwan__det_reduce_pio2_f64(alwan_f64 x, int *quadrant) {
    const alwan_f64 fn = floor(x * ALWAN_DET_TWO_OVER_PI + 0.5);
    const alwan_f64 k  = fn - 4.0 * floor(fn * 0.25);
    *quadrant = (int)k;
    return ((x - fn * ALWAN_DET_PIO2_HI) - fn * ALWAN_DET_PIO2_MID)
           - fn * ALWAN_DET_PIO2_LO;
}
ALWAN_INLINE alwan_f32 alwan__det_reduce_pio2_f32(alwan_f32 x, int *quadrant) {
    const alwan_f32 fn = floorf(x * (alwan_f32)ALWAN_DET_TWO_OVER_PI + 0.5f);
    const alwan_f32 k  = fn - 4.0f * floorf(fn * 0.25f);
    *quadrant = (int)k;
    return ((x - fn * ALWAN_DET_PIO2_HI_F32) - fn * ALWAN_DET_PIO2_MID_F32)
           - fn * ALWAN_DET_PIO2_LO_F32;
}

#define ALWAN__DET_SINPOLY_F64(r, y) \
    ((r) * alwan_det_horner_f64(alwan_det_sin_coeffs_f64, ALWAN_DET_SIN_DEGREE, (y)))
#define ALWAN__DET_COSPOLY_F64(y) \
    (alwan_det_horner_f64(alwan_det_cos_coeffs_f64, ALWAN_DET_COS_DEGREE, (y)))
#define ALWAN__DET_SINPOLY_F32(r, y) \
    ((r) * alwan_det_horner_f32(alwan_det_sin_coeffs_f32, ALWAN_DET_SIN_DEGREE, (y)))
#define ALWAN__DET_COSPOLY_F32(y) \
    (alwan_det_horner_f32(alwan_det_cos_coeffs_f32, ALWAN_DET_COS_DEGREE, (y)))

ALWAN_INLINE alwan_f64 alwan_det_sin_f64(alwan_f64 x) {
    int q; const alwan_f64 r = alwan__det_reduce_pio2_f64(x, &q);
    const alwan_f64 y = r * r;
    if (q == 0) return  ALWAN__DET_SINPOLY_F64(r, y);
    if (q == 1) return  ALWAN__DET_COSPOLY_F64(y);
    if (q == 2) return -ALWAN__DET_SINPOLY_F64(r, y);
    return              -ALWAN__DET_COSPOLY_F64(y);
}
ALWAN_INLINE alwan_f32 alwan_det_sin_f32(alwan_f32 x) {
    int q; const alwan_f32 r = alwan__det_reduce_pio2_f32(x, &q);
    const alwan_f32 y = r * r;
    if (q == 0) return  ALWAN__DET_SINPOLY_F32(r, y);
    if (q == 1) return  ALWAN__DET_COSPOLY_F32(y);
    if (q == 2) return -ALWAN__DET_SINPOLY_F32(r, y);
    return              -ALWAN__DET_COSPOLY_F32(y);
}

ALWAN_INLINE alwan_f64 alwan_det_cos_f64(alwan_f64 x) {
    int q; const alwan_f64 r = alwan__det_reduce_pio2_f64(x, &q);
    const alwan_f64 y = r * r;
    if (q == 0) return  ALWAN__DET_COSPOLY_F64(y);
    if (q == 1) return -ALWAN__DET_SINPOLY_F64(r, y);
    if (q == 2) return -ALWAN__DET_COSPOLY_F64(y);
    return               ALWAN__DET_SINPOLY_F64(r, y);
}
ALWAN_INLINE alwan_f32 alwan_det_cos_f32(alwan_f32 x) {
    int q; const alwan_f32 r = alwan__det_reduce_pio2_f32(x, &q);
    const alwan_f32 y = r * r;
    if (q == 0) return  ALWAN__DET_COSPOLY_F32(y);
    if (q == 1) return -ALWAN__DET_SINPOLY_F32(r, y);
    if (q == 2) return -ALWAN__DET_COSPOLY_F32(y);
    return               ALWAN__DET_SINPOLY_F32(r, y);
}

/* tan from the same single reduction. An even quadrant is tan(r) = sin/cos; an
 * odd one is tan(pi/2 + r) = -cot(r) = -cos/sin. Poles return the sign-correct
 * infinity the division produces, as libm does. */
ALWAN_INLINE alwan_f64 alwan_det_tan_f64(alwan_f64 x) {
    int q; const alwan_f64 r = alwan__det_reduce_pio2_f64(x, &q);
    const alwan_f64 y = r * r;
    const alwan_f64 s = ALWAN__DET_SINPOLY_F64(r, y);
    const alwan_f64 c = ALWAN__DET_COSPOLY_F64(y);
    return (q & 1) ? (-c / s) : (s / c);
}
ALWAN_INLINE alwan_f32 alwan_det_tan_f32(alwan_f32 x) {
    int q; const alwan_f32 r = alwan__det_reduce_pio2_f32(x, &q);
    const alwan_f32 y = r * r;
    const alwan_f32 s = ALWAN__DET_SINPOLY_F32(r, y);
    const alwan_f32 c = ALWAN__DET_COSPOLY_F32(y);
    return (q & 1) ? (-c / s) : (s / c);
}

/* atan on [0, 1]. Above tan(pi/8) the identity
 *   atan(t) = pi/4 + atan((t - 1) / (t + 1))
 * maps the argument back into |s| <= tan(pi/8), which is the domain the
 * polynomial was fitted on. Without that second reduction a single polynomial
 * over the whole of [0, 1] needs a much higher degree for the same accuracy. */
ALWAN_INLINE alwan_f64 alwan__det_atan_core_f64(alwan_f64 t) {
    if (t > ALWAN_DET_TAN_PI_8) {
        const alwan_f64 s = (t - 1.0) / (t + 1.0);
        return ALWAN_DET_PIO4 + s * alwan_det_horner_f64(
            alwan_det_atan_coeffs_f64, ALWAN_DET_ATAN_DEGREE, s * s);
    }
    return t * alwan_det_horner_f64(
        alwan_det_atan_coeffs_f64, ALWAN_DET_ATAN_DEGREE, t * t);
}
ALWAN_INLINE alwan_f32 alwan__det_atan_core_f32(alwan_f32 t) {
    if (t > (alwan_f32)ALWAN_DET_TAN_PI_8) {
        const alwan_f32 s = (t - 1.0f) / (t + 1.0f);
        return (alwan_f32)ALWAN_DET_PIO4 + s * alwan_det_horner_f32(
            alwan_det_atan_coeffs_f32, ALWAN_DET_ATAN_DEGREE, s * s);
    }
    return t * alwan_det_horner_f32(
        alwan_det_atan_coeffs_f32, ALWAN_DET_ATAN_DEGREE, t * t);
}

ALWAN_INLINE alwan_f64 alwan_det_atan_f64(alwan_f64 x) {
    const alwan_f64 a = (x < 0.0) ? -x : x;
    /* |x| > 1 folds through atan(t) = pi/2 - atan(1/t). An infinite argument
     * reciprocates to 0, so it returns pi/2 without a special case. */
    const alwan_f64 r = (a > 1.0)
        ? (ALWAN_DET_PIO2 - alwan__det_atan_core_f64(1.0 / a))
        : alwan__det_atan_core_f64(a);
    return (x < 0.0) ? -r : r;
}
ALWAN_INLINE alwan_f32 alwan_det_atan_f32(alwan_f32 x) {
    const alwan_f32 a = (x < 0.0f) ? -x : x;
    const alwan_f32 r = (a > 1.0f)
        ? ((alwan_f32)ALWAN_DET_PIO2 - alwan__det_atan_core_f32(1.0f / a))
        : alwan__det_atan_core_f32(a);
    return (x < 0.0f) ? -r : r;
}

/* atan2 with the C99 quadrant conventions, including atan2(0, 0) = 0. */
ALWAN_INLINE alwan_f64 alwan_det_atan2_f64(alwan_f64 y, alwan_f64 x) {
    if (x == 0.0) {
        if (y > 0.0) return  ALWAN_DET_PIO2;
        if (y < 0.0) return -ALWAN_DET_PIO2;
        return 0.0;
    }
    {
        const alwan_f64 a = alwan_det_atan_f64(y / x);
        if (x > 0.0) return a;
        return (y >= 0.0) ? (a + ALWAN_DET_PI) : (a - ALWAN_DET_PI);
    }
}
ALWAN_INLINE alwan_f32 alwan_det_atan2_f32(alwan_f32 y, alwan_f32 x) {
    if (x == 0.0f) {
        if (y > 0.0f) return  (alwan_f32)ALWAN_DET_PIO2;
        if (y < 0.0f) return -(alwan_f32)ALWAN_DET_PIO2;
        return 0.0f;
    }
    {
        const alwan_f32 a = alwan_det_atan_f32(y / x);
        if (x > 0.0f) return a;
        return (y >= 0.0f) ? (a + (alwan_f32)ALWAN_DET_PI) : (a - (alwan_f32)ALWAN_DET_PI);
    }
}

/* acos through atan2, which keeps it accurate near both ends where the naive
 * form loses precision. sqrt is correctly rounded by IEEE-754, so it carries no
 * platform variation of its own.
 *
 * Out of domain returns the endpoint rather than NaN. libm returns NaN; det
 * mode prefers a defined value, the same choice alwan_det_pow_pos makes for a
 * negative base. */
ALWAN_INLINE alwan_f64 alwan_det_acos_f64(alwan_f64 x) {
    const alwan_f64 c = (x < -1.0) ? -1.0 : ((x > 1.0) ? 1.0 : x);
    return alwan_det_atan2_f64(sqrt(1.0 - c * c), c);
}
ALWAN_INLINE alwan_f32 alwan_det_acos_f32(alwan_f32 x) {
    const alwan_f32 c = (x < -1.0f) ? -1.0f : ((x > 1.0f) ? 1.0f : x);
    return alwan_det_atan2_f32(sqrtf(1.0f - c * c), c);
}

/* ----------------------------------------------------------------
 * Generic linear+power OETF/EOTF evaluator. Used by every TF whose
 * shape is `linear * x for x < break, alpha * pow(x, exp) - beta`
 * (sRGB, BT.2020, BT.709, ...). Each TF supplies its own constants
 * via the per-TF `alwan_det_<tf>_coeffs.h`.
 *
 * The power branch goes through alwan_det_pow_pos. These used to hold
 * per-TF Chebyshev tables instead, split into a lo and a hi piece,
 * because pow() reaches libm. Three things were wrong with that.
 *
 * Accuracy: the tables sat between 4.8e-08 and 2.5e-04. x^(1/2.4) has
 * an algebraic branch point at 0 and the OETF domain starts at
 * 0.0031308, so polynomial convergence is slow no matter the degree;
 * a true minimax fit at the same degrees only doubles it. pow_pos
 * reduces the argument (frexp, then floor+ldexp) rather than
 * approximating through the singularity, and lands at 3.3e-16.
 *
 * Extrapolation: a fitted polynomial evaluated outside its domain is
 * not merely inaccurate. The sRGB OETF of linear 4.0 returned -9.2e10.
 * Scene-linear above 1 is ordinary input. Nothing extrapolates now.
 *
 * Surface: no tables, no split points, no branch on which piece.
 *
 * The cost is a log2 and an exp2 in place of one Horner. That is the
 * right trade for a build whose whole purpose is reproducibility.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan__det_lin_pow_oetf_f64(
    alwan_f64 x,
    alwan_f64 break_x, alwan_f64 exponent,
    alwan_f64 linear_slope, alwan_f64 alpha, alwan_f64 beta
) {
    if (x <= break_x) return linear_slope * x;
    return alpha * alwan_det_pow_pos_f64(x, exponent) - beta;
}

ALWAN_INLINE alwan_f32 alwan__det_lin_pow_oetf_f32(
    alwan_f32 x,
    alwan_f32 break_x, alwan_f32 exponent,
    alwan_f32 linear_slope, alwan_f32 alpha, alwan_f32 beta
) {
    if (x <= break_x) return linear_slope * x;
    return alpha * alwan_det_pow_pos_f32(x, exponent) - beta;
}

ALWAN_INLINE alwan_f64 alwan__det_lin_pow_eotf_f64(
    alwan_f64 x,
    alwan_f64 enc_break, alwan_f64 linear_slope,
    alwan_f64 alpha, alwan_f64 beta, alwan_f64 inv_exponent
) {
    if (x <= enc_break) return x / linear_slope;
    return alwan_det_pow_pos_f64((x + beta) / alpha, inv_exponent);
}

ALWAN_INLINE alwan_f32 alwan__det_lin_pow_eotf_f32(
    alwan_f32 x,
    alwan_f32 enc_break, alwan_f32 linear_slope,
    alwan_f32 alpha, alwan_f32 beta, alwan_f32 inv_exponent
) {
    if (x <= enc_break) return x / linear_slope;
    return alwan_det_pow_pos_f32((x + beta) / alpha, inv_exponent);
}

/* ----------------------------------------------------------------
 * sRGB OETF / EOTF
 * IEC 61966-2-1: linear=12.92, alpha=1.055, exp=1/2.4, break=0.0031308.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan_det_srgb_oetf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_oetf_f64(x,
        ALWAN_DET_SRGB_OETF_BREAK, (1.0 / 2.4),
        ALWAN_DET_SRGB_OETF_LINEAR, ALWAN_DET_SRGB_OETF_ALPHA, ALWAN_DET_SRGB_OETF_BETA);
}

ALWAN_INLINE alwan_f32 alwan_det_srgb_oetf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_oetf_f32(x,
        (alwan_f32)ALWAN_DET_SRGB_OETF_BREAK, (1.0f / 2.4f),
        (alwan_f32)ALWAN_DET_SRGB_OETF_LINEAR, (alwan_f32)ALWAN_DET_SRGB_OETF_ALPHA,
        (alwan_f32)ALWAN_DET_SRGB_OETF_BETA);
}

ALWAN_INLINE alwan_f64 alwan_det_srgb_eotf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_eotf_f64(x,
        ALWAN_DET_SRGB_EOTF_BREAK, ALWAN_DET_SRGB_OETF_LINEAR,
        ALWAN_DET_SRGB_OETF_ALPHA, ALWAN_DET_SRGB_OETF_BETA, 2.4);
}

ALWAN_INLINE alwan_f32 alwan_det_srgb_eotf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_eotf_f32(x,
        (alwan_f32)ALWAN_DET_SRGB_EOTF_BREAK, (alwan_f32)ALWAN_DET_SRGB_OETF_LINEAR,
        (alwan_f32)ALWAN_DET_SRGB_OETF_ALPHA, (alwan_f32)ALWAN_DET_SRGB_OETF_BETA, 2.4f);
}

/* ----------------------------------------------------------------
 * BT.2020 / BT.709 OETF / EOTF
 * ITU-R BT.2020-2: linear=4.5, alpha=1.099, exp=0.45, break=0.018.
 * BT.709 uses the same constants in the 4-decimal form, so this same
 * polynomial serves both standards.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan_det_bt2020_oetf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_oetf_f64(x,
        ALWAN_DET_BT2020_OETF_BREAK, 0.45,
        ALWAN_DET_BT2020_OETF_LINEAR, ALWAN_DET_BT2020_OETF_ALPHA, ALWAN_DET_BT2020_OETF_BETA);
}

ALWAN_INLINE alwan_f32 alwan_det_bt2020_oetf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_oetf_f32(x,
        (alwan_f32)ALWAN_DET_BT2020_OETF_BREAK, 0.45f,
        (alwan_f32)ALWAN_DET_BT2020_OETF_LINEAR, (alwan_f32)ALWAN_DET_BT2020_OETF_ALPHA,
        (alwan_f32)ALWAN_DET_BT2020_OETF_BETA);
}

ALWAN_INLINE alwan_f64 alwan_det_bt2020_eotf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_eotf_f64(x,
        ALWAN_DET_BT2020_EOTF_BREAK, ALWAN_DET_BT2020_OETF_LINEAR,
        ALWAN_DET_BT2020_OETF_ALPHA, ALWAN_DET_BT2020_OETF_BETA, (1.0 / 0.45));
}

ALWAN_INLINE alwan_f32 alwan_det_bt2020_eotf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_eotf_f32(x,
        (alwan_f32)ALWAN_DET_BT2020_EOTF_BREAK, (alwan_f32)ALWAN_DET_BT2020_OETF_LINEAR,
        (alwan_f32)ALWAN_DET_BT2020_OETF_ALPHA, (alwan_f32)ALWAN_DET_BT2020_OETF_BETA, (1.0f / 0.45f));
}

#else /* ================= GPU backends (single precision) ================= *
 * Inlined deterministic transcendentals, one body for every single-pass
 * backend: HLSL, GLSL and OpenCL. Same polynomials and the same committed
 * coefficient tables as the C _f32 path.
 *
 * The three per-language spellings live in alwan_platform.h. frexp writes its
 * exponent through a reference in HLSL and through a pointer in OpenCL.
 * Blocking mul+add fusion is `precise` in HLSL and the FP_CONTRACT pragma above
 * in OpenCL, which is why ALWAN_DET_PRECISE is empty there rather than missing.
 * The unroll is a hint either way.
 *
 * Bit-exact with det-C by construction. Verified on OpenCL against the C
 * library (alwan_dev/opencl_regression); the HLSL runtime check covers the
 * transfer functions only. */

ALWAN_INLINE alwan_scalar alwan_det_log2(alwan_scalar x) {
    /* The C twin returns -INFINITY here and this branch had no guard at all,
     * so log2 of zero or a negative went into frexp and came back as whatever
     * the polynomial made of a zero mantissa. Not reachable from the transfer
     * functions, which clamp first, but reachable the moment anything else on
     * a GPU path calls it, and a silent difference from the C path either way. */
    if (x <= (alwan_scalar)0.0) return -ALWAN_LITERAL(1.0) / (alwan_scalar)0.0;
    {
    ALWAN_DET_EXPT e; alwan_scalar m = ALWAN_DET_FREXP(x, e);   /* m in [0.5,1), e = exponent */
    alwan_scalar u = (alwan_scalar)2.0 * (m - (alwan_scalar)0.5) / (alwan_scalar)0.5 - (alwan_scalar)1.0;
    ALWAN_DET_PRECISE alwan_scalar acc = alwan_det_log2_coeffs_f32[ALWAN_DET_LOG2_DEGREE];
    ALWAN_DET_UNROLL for (int i = ALWAN_DET_LOG2_DEGREE - 1; i >= 0; --i) {
        ALWAN_DET_PRECISE alwan_scalar t = acc * u; acc = t + alwan_det_log2_coeffs_f32[i];
    }
    /* The table is log2(m)/(m-1); reconstruct. Mirrors the C _f32 path. */
    ALWAN_DET_PRECISE alwan_scalar lg = (m - (alwan_scalar)1.0) * acc;
    return (alwan_scalar)e + lg;
    }
}

ALWAN_INLINE alwan_scalar alwan_det_exp2(alwan_scalar t) {
    alwan_scalar ip = floor(t);
    alwan_scalar u = (alwan_scalar)2.0 * (t - ip) - (alwan_scalar)1.0;  /* frac[0,1)->[-1,1] */
    ALWAN_DET_PRECISE alwan_scalar acc = alwan_det_exp2_coeffs_f32[ALWAN_DET_EXP2_DEGREE];
    ALWAN_DET_UNROLL for (int i = ALWAN_DET_EXP2_DEGREE - 1; i >= 0; --i) {
        ALWAN_DET_PRECISE alwan_scalar tt = acc * u; acc = tt + alwan_det_exp2_coeffs_f32[i];
    }
    return ALWAN_DET_LDEXP(acc, ip);
}

ALWAN_INLINE alwan_scalar alwan_det_pow_pos(alwan_scalar x, alwan_scalar e) {
    if (x <= (alwan_scalar)0.0) return (alwan_scalar)0.0;
    return alwan_det_exp2(e * alwan_det_log2(x));
}

/* Everything that is an exact identity over the pair above, mirroring the C
 * _f32 definitions line for line. These were missing from this branch, and the
 * absence was not visible: without them ALWAN_CORE_CBRT and friends fell
 * through to the hardware intrinsic, so a deterministic GPU build was
 * deterministic for the four transfer functions and nothing else. Measured on
 * OpenCL against a deterministic host, that showed as xyz_to_oklab differing
 * while srgb_oetf was exact. */
ALWAN_INLINE alwan_scalar alwan_det_cbrt(alwan_scalar x) {
    if (x == (alwan_scalar)0.0) return (alwan_scalar)0.0;
    {
    alwan_scalar a = (x < (alwan_scalar)0.0) ? -x : x;
    alwan_scalar r = alwan_det_pow_pos(a, (alwan_scalar)(1.0 / 3.0));
    return (x < (alwan_scalar)0.0) ? -r : r;
    }
}
ALWAN_INLINE alwan_scalar alwan_det_exp(alwan_scalar x) {
    /* e^x = 2^(x * log2(e)) */
    return alwan_det_exp2(x * (alwan_scalar)1.4426950408889634073599246810018922);
}
ALWAN_INLINE alwan_scalar alwan_det_log(alwan_scalar x) {
    /* ln(x) = log2(x) * ln(2) */
    return alwan_det_log2(x) * (alwan_scalar)0.69314718055994530941723212145817657;
}
ALWAN_INLINE alwan_scalar alwan_det_log10(alwan_scalar x) {
    return alwan_det_log2(x) * (alwan_scalar)ALWAN_DET_LOG10_2;
}

ALWAN_INLINE alwan_scalar alwan_det_tanh(alwan_scalar x) {
    if (x == (alwan_scalar)0.0) return x;   /* keep it exactly odd at 0 */
    {
    alwan_scalar a = (x < (alwan_scalar)0.0) ? -x : x;
    alwan_scalar e = alwan_det_exp((alwan_scalar)-2.0 * a);
    alwan_scalar t = ((alwan_scalar)1.0 - e) / ((alwan_scalar)1.0 + e);
    return (x < (alwan_scalar)0.0) ? -t : t;
    }
}

/* ----------------------------------------------------------------
 * The angle family, mirroring the C _f32 path.
 *
 * This was the last thing on these backends still reaching the hardware
 * intrinsic under ALWAN_DETERMINISTIC, and therefore the last reason a
 * deterministic GPU build could disagree with a deterministic CPU one. Every
 * cylindrical space, every CAM hue correlate, dE2000 and dE CMC reach it.
 *
 * Same three polynomials as the C path, from the same committed f32 tables, and
 * the same Cody-Waite reduction. The f32 constants exist because the C f32 pass
 * needs its own 12-bit split of pi/2: casting the f64 parts to float would
 * round away exactly the extra precision the split exists to carry.
 * ---------------------------------------------------------------- */

/* x = n*(pi/2) + r with |r| <= pi/4; returns r and writes n mod 4.
 * The quadrant is taken in floating point rather than through an integer cast,
 * so a large |x| cannot overflow it. Accuracy still degrades past roughly 2^40,
 * as it does for any Cody-Waite reduction; hue angles never go there. */
/* Split into three plain functions rather than one with an out-parameter. HLSL
 * spells an out-parameter `out int`, OpenCL and C spell it `int *`, and the
 * quadrant has to be an integer either way because tan tests its low bit. Three
 * value-returning calls need no spelling at all, and the caller pays one extra
 * floor for it. */
ALWAN_INLINE alwan_scalar alwan__det_reduce_fn(alwan_scalar x) {
    return floor(x * (alwan_scalar)ALWAN_DET_TWO_OVER_PI + (alwan_scalar)0.5);
}
ALWAN_INLINE alwan_scalar alwan__det_reduce_r(alwan_scalar x, alwan_scalar fn) {
    return ((x - fn * (alwan_scalar)ALWAN_DET_PIO2_HI_F32)
               - fn * (alwan_scalar)ALWAN_DET_PIO2_MID_F32)
               - fn * (alwan_scalar)ALWAN_DET_PIO2_LO_F32;
}
ALWAN_INLINE int alwan__det_quadrant(alwan_scalar fn) {
    return (int)(fn - (alwan_scalar)4.0 * floor(fn * (alwan_scalar)0.25));
}

/* sin(r)/r and cos(r) as polynomials in y = r*r. Factoring the parity out is
 * what makes sin(0) and atan(0) exactly zero rather than approximately so. */
ALWAN_INLINE alwan_scalar alwan__det_sinpoly(alwan_scalar r, alwan_scalar y) {
    ALWAN_DET_PRECISE alwan_scalar acc = alwan_det_sin_coeffs_f32[ALWAN_DET_SIN_DEGREE];
    ALWAN_DET_UNROLL for (int i = ALWAN_DET_SIN_DEGREE - 1; i >= 0; --i) {
        ALWAN_DET_PRECISE alwan_scalar t = acc * y; acc = t + alwan_det_sin_coeffs_f32[i];
    }
    return r * acc;
}
ALWAN_INLINE alwan_scalar alwan__det_cospoly(alwan_scalar y) {
    ALWAN_DET_PRECISE alwan_scalar acc = alwan_det_cos_coeffs_f32[ALWAN_DET_COS_DEGREE];
    ALWAN_DET_UNROLL for (int i = ALWAN_DET_COS_DEGREE - 1; i >= 0; --i) {
        ALWAN_DET_PRECISE alwan_scalar t = acc * y; acc = t + alwan_det_cos_coeffs_f32[i];
    }
    return acc;
}
ALWAN_INLINE alwan_scalar alwan__det_atanpoly(alwan_scalar y) {
    ALWAN_DET_PRECISE alwan_scalar acc = alwan_det_atan_coeffs_f32[ALWAN_DET_ATAN_DEGREE];
    ALWAN_DET_UNROLL for (int i = ALWAN_DET_ATAN_DEGREE - 1; i >= 0; --i) {
        ALWAN_DET_PRECISE alwan_scalar t = acc * y; acc = t + alwan_det_atan_coeffs_f32[i];
    }
    return acc;
}

ALWAN_INLINE alwan_scalar alwan_det_sin(alwan_scalar x) {
    alwan_scalar fn = alwan__det_reduce_fn(x);
    alwan_scalar r = alwan__det_reduce_r(x, fn);
    int q = alwan__det_quadrant(fn);
    alwan_scalar y = r * r;
    if (q == 0) return  alwan__det_sinpoly(r, y);
    if (q == 1) return  alwan__det_cospoly(y);
    if (q == 2) return -alwan__det_sinpoly(r, y);
    return              -alwan__det_cospoly(y);
}

ALWAN_INLINE alwan_scalar alwan_det_cos(alwan_scalar x) {
    alwan_scalar fn = alwan__det_reduce_fn(x);
    alwan_scalar r = alwan__det_reduce_r(x, fn);
    int q = alwan__det_quadrant(fn);
    alwan_scalar y = r * r;
    if (q == 0) return  alwan__det_cospoly(y);
    if (q == 1) return -alwan__det_sinpoly(r, y);
    if (q == 2) return -alwan__det_cospoly(y);
    return               alwan__det_sinpoly(r, y);
}

ALWAN_INLINE alwan_scalar alwan_det_tan(alwan_scalar x) {
    alwan_scalar fn = alwan__det_reduce_fn(x);
    alwan_scalar r = alwan__det_reduce_r(x, fn);
    int q = alwan__det_quadrant(fn);
    alwan_scalar y = r * r;
    alwan_scalar s = alwan__det_sinpoly(r, y);
    alwan_scalar c = alwan__det_cospoly(y);
    return (q & 1) ? (-c / s) : (s / c);
}

/* A second reduction at tan(pi/8), fdlibm style. One polynomial over the whole
 * of [0, 1] converges too slowly: degree 12 only reaches 9e-12. */
ALWAN_INLINE alwan_scalar alwan__det_atan_core(alwan_scalar t) {
    if (t > (alwan_scalar)ALWAN_DET_TAN_PI_8) {
        alwan_scalar s = (t - (alwan_scalar)1.0) / (t + (alwan_scalar)1.0);
        return (alwan_scalar)ALWAN_DET_PIO4 + s * alwan__det_atanpoly(s * s);
    }
    return t * alwan__det_atanpoly(t * t);
}

ALWAN_INLINE alwan_scalar alwan_det_atan(alwan_scalar x) {
    alwan_scalar a = (x < (alwan_scalar)0.0) ? -x : x;
    alwan_scalar r = (a > (alwan_scalar)1.0)
        ? ((alwan_scalar)ALWAN_DET_PIO2 - alwan__det_atan_core((alwan_scalar)1.0 / a))
        : alwan__det_atan_core(a);
    return (x < (alwan_scalar)0.0) ? -r : r;
}

ALWAN_INLINE alwan_scalar alwan_det_atan2(alwan_scalar y, alwan_scalar x) {
    if (x == (alwan_scalar)0.0) {
        if (y > (alwan_scalar)0.0) return  (alwan_scalar)ALWAN_DET_PIO2;
        if (y < (alwan_scalar)0.0) return -(alwan_scalar)ALWAN_DET_PIO2;
        return (alwan_scalar)0.0;
    }
    {
    alwan_scalar a = alwan_det_atan(y / x);
    if (x > (alwan_scalar)0.0) return a;
    return (y >= (alwan_scalar)0.0) ? (a + (alwan_scalar)ALWAN_DET_PI)
                                    : (a - (alwan_scalar)ALWAN_DET_PI);
    }
}

ALWAN_INLINE alwan_scalar alwan_det_acos(alwan_scalar x) {
    alwan_scalar c = (x < (alwan_scalar)-1.0) ? (alwan_scalar)-1.0
                   : ((x > (alwan_scalar)1.0) ? (alwan_scalar)1.0 : x);
    return alwan_det_atan2(sqrt((alwan_scalar)1.0 - c * c), c);
}

/* The four TFs, mirroring the C _f32 helpers exactly: same pow_pos, same
 * constants, same rounding order. Because the power branch is now pow_pos
 * rather than a per-TF table, C and GPU share one code path in all but
 * spelling, so cross-backend parity no longer rests on two hand-kept copies of
 * a Horner loop. This also gives the GPU path the out-of-domain behaviour it
 * never had: the old tables extrapolated above 1.0 the same way the C ones did,
 * and nothing here guarded it. */

ALWAN_INLINE alwan_scalar alwan_det_srgb_oetf(alwan_scalar x) {
    if (x <= (alwan_scalar)ALWAN_DET_SRGB_OETF_BREAK)
        return (alwan_scalar)ALWAN_DET_SRGB_OETF_LINEAR * x;
    ALWAN_DET_PRECISE alwan_scalar p = alwan_det_pow_pos(x, (alwan_scalar)(1.0 / 2.4));
    return (alwan_scalar)ALWAN_DET_SRGB_OETF_ALPHA * p - (alwan_scalar)ALWAN_DET_SRGB_OETF_BETA;
}

ALWAN_INLINE alwan_scalar alwan_det_srgb_eotf(alwan_scalar x) {
    if (x <= (alwan_scalar)ALWAN_DET_SRGB_EOTF_BREAK)
        return x / (alwan_scalar)ALWAN_DET_SRGB_OETF_LINEAR;
    alwan_scalar z = (x + (alwan_scalar)ALWAN_DET_SRGB_OETF_BETA) / (alwan_scalar)ALWAN_DET_SRGB_OETF_ALPHA;
    return alwan_det_pow_pos(z, (alwan_scalar)2.4);
}

ALWAN_INLINE alwan_scalar alwan_det_bt2020_oetf(alwan_scalar x) {
    if (x <= (alwan_scalar)ALWAN_DET_BT2020_OETF_BREAK)
        return (alwan_scalar)ALWAN_DET_BT2020_OETF_LINEAR * x;
    ALWAN_DET_PRECISE alwan_scalar p = alwan_det_pow_pos(x, (alwan_scalar)0.45);
    return (alwan_scalar)ALWAN_DET_BT2020_OETF_ALPHA * p - (alwan_scalar)ALWAN_DET_BT2020_OETF_BETA;
}

ALWAN_INLINE alwan_scalar alwan_det_bt2020_eotf(alwan_scalar x) {
    if (x <= (alwan_scalar)ALWAN_DET_BT2020_EOTF_BREAK)
        return x / (alwan_scalar)ALWAN_DET_BT2020_OETF_LINEAR;
    alwan_scalar z = (x + (alwan_scalar)ALWAN_DET_BT2020_OETF_BETA) / (alwan_scalar)ALWAN_DET_BT2020_OETF_ALPHA;
    return alwan_det_pow_pos(z, (alwan_scalar)(1.0 / 0.45));
}

#endif /* ALWAN_BACKEND_C else GPU */

#endif /* ALWAN_DETERMINISTIC_H */
