/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Soufiane KHIAT
 * SPDX-License-Identifier: MIT
 *
 * alwan_deterministic.h - bit-exact polynomial implementations for
 * primitives that would otherwise call libm.
 *
 * Active only when `ALWAN_DETERMINISTIC=1` is defined. Each function
 * here approximates a transcendental over its valid colour-science
 * range with a polynomial whose coefficients are committed to source
 * (generated by alwan_dev/gendata/gen_*.py), then evaluated via
 * Horner's method with FMA contraction explicitly disabled.
 *
 * Two guarantees together give cross-platform bit-exactness:
 *
 *   1. The polynomial is fully specified (coefficients in
 *      alwan_det_*_coeffs.h, no platform-dependent input).
 *   2. `#pragma STDC FP_CONTRACT OFF` blocks the compiler from
 *      fusing `a*b + c` into a single-rounding FMA, which would
 *      otherwise differ between x86 (with/without -mfma) and
 *      aarch64 (FMA mandatory).
 *
 * The polynomial does NOT match libm bit-for-bit. It approximates
 * the same mathematical function within a documented error budget
 * (typically <0.05% absolute for sRGB-range inputs). The point is
 * that *every* deterministic build, on every platform, returns the
 * same bytes for the same inputs -- that's what
 * cross-platform-determinism CI verifies via output hashing.
 *
 * Currently covered:
 *   - sRGB     OETF/EOTF
 *   - BT.2020  OETF/EOTF (also valid for BT.709 -- same constants)
 *
 * Pipeline (PQ, HLG, Lab cube root, ACES splines, ...) follow in
 * later phases -- see docs/determinism.md
 */

#ifndef ALWAN_DETERMINISTIC_H
#define ALWAN_DETERMINISTIC_H

/* Block FMA contraction inside this header. The CMake build also
 * passes `-ffp-contract=off` (clang/gcc) or `/fp:precise` (MSVC) for
 * defense in depth; the per-file pragma is belt-and-suspenders so a
 * downstream consumer can't accidentally re-fuse our polynomial
 * evaluations. Each compiler needs its own spelling:
 *   - clang implements the ISO C `#pragma STDC FP_CONTRACT`.
 *   - GCC parses but does NOT implement that pragma -- it warns
 *     -Wunknown-pragmas ("ignoring '#pragma STDC FP_CONTRACT'"), which
 *     -Werror turns fatal. GCC's equivalent is `#pragma GCC optimize
 *     ("fp-contract=off")`, which overrides even a command-line
 *     -ffp-contract=fast (verified on gcc 13). ICC is excluded: it
 *     defines __GNUC__ but does not honor this pragma cleanly.
 *   - MSVC's STDC support is incomplete -- its equivalent is
 *     `#pragma fp_contract(off)` with different syntax.
 * This header is only included in deterministic builds (see
 * alwan_math.h), so the TU-wide pragma never touches the fast path. */
#if ALWAN_BACKEND == ALWAN_BACKEND_C
#if defined(__clang__)
#  pragma STDC FP_CONTRACT OFF
#elif defined(__GNUC__) && !defined(__INTEL_COMPILER)
#  pragma GCC optimize ("fp-contract=off")
#elif defined(_MSC_VER)
#  pragma fp_contract(off)
#endif
#endif /* ALWAN_BACKEND_C -- GPU blocks fusion with `precise` instead */

#include "../alwan_types.h"
#include "alwan_det_srgb_coeffs.h"
#include "alwan_det_bt2020_coeffs.h"
#include "alwan_det_math_coeffs.h"

/* frexp / ldexp are libm but pure IEEE-754 bit manipulation, not
 * transcendental approximation, so they're bit-identical across
 * platforms. Used by alwan_det_log2 / alwan_det_exp2 below for
 * argument reduction. (GPU backends use the HLSL frexp/ldexp intrinsics.) */
#if ALWAN_BACKEND == ALWAN_BACKEND_C
#include <math.h>
#endif

/* The C path defines the full f32+f64 suffixed set (pointer-Horner + libm
 * frexp). The GPU path can't take arrays by pointer or call libm, so it gets an
 * inlined single-precision subset at the end of this header. */
#if ALWAN_BACKEND == ALWAN_BACKEND_C

/* ----------------------------------------------------------------
 * Horner evaluation -- explicit `mul; add` so FP_CONTRACT OFF actually
 * has something to refuse to fuse.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64
alwan_det_horner_f64(alwan_f64 const *coeffs, int degree, alwan_f64 x) {
    alwan_f64 acc = coeffs[degree];
    for (int i = degree - 1; i >= 0; i--) {
        alwan_f64 const t = acc * x;        /* round 1 */
        acc = t + coeffs[i];                /* round 2 -- never fused */
    }
    return acc;
}

ALWAN_INLINE alwan_f32
alwan_det_horner_f32(alwan_f32 const *coeffs, int degree, alwan_f32 x) {
    alwan_f32 acc = coeffs[degree];
    for (int i = degree - 1; i >= 0; i--) {
        alwan_f32 const t = acc * x;
        acc = t + coeffs[i];
    }
    return acc;
}

/* Domain normalisation: maps x in [lo, hi] to u in [-1, 1]. */
ALWAN_INLINE alwan_f64 alwan_det_normalize_f64(alwan_f64 x, alwan_f64 lo, alwan_f64 hi) {
    return 2.0 * (x - lo) / (hi - lo) - 1.0;
}
ALWAN_INLINE alwan_f32 alwan_det_normalize_f32(alwan_f32 x, alwan_f32 lo, alwan_f32 hi) {
    return 2.0f * (x - lo) / (hi - lo) - 1.0f;
}

/* ----------------------------------------------------------------
 * Argument-reduced log2 / exp2 / pow_pos.
 *
 * log2(x) for x > 0:
 *   x = m * 2^k   (frexp; m in [0.5, 1.0), k integer)
 *   log2(x) = k + log2(m), polynomial fits log2(m) on [0.5, 1.0].
 *
 * exp2(t) for any t:
 *   t = int_t + frac_t   (frac_t in [0, 1))
 *   exp2(t) = ldexp(exp2(frac_t), int_t), polynomial fits exp2 on [0, 1].
 *
 * pow_pos(x, e) for x > 0:
 *   exp2(e * log2(x)).
 *
 * For x <= 0 the result is 0 (matching IEEE/libm pow conventions for
 * x = 0; for negative x it's a domain error, which we treat as 0
 * deterministically rather than NaN).
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan_det_log2_f64(alwan_f64 x) {
    if (x <= 0.0) return -INFINITY;  /* IEEE convention */
    int k;
    alwan_f64 const m = frexp(x, &k);
    /* m in [0.5, 1.0); normalise to u in [-1, 1] for the polynomial. */
    alwan_f64 const u = alwan_det_normalize_f64(m, 0.5, 1.0);
    return (alwan_f64)k + alwan_det_horner_f64(
        alwan_det_log2_coeffs_f64, ALWAN_DET_LOG2_DEGREE, u);
}

ALWAN_INLINE alwan_f32 alwan_det_log2_f32(alwan_f32 x) {
    if (x <= 0.0f) return -INFINITY;
    int k;
    alwan_f32 const m = frexpf(x, &k);
    alwan_f32 const u = alwan_det_normalize_f32(m, 0.5f, 1.0f);
    return (alwan_f32)k + alwan_det_horner_f32(
        alwan_det_log2_coeffs_f32, ALWAN_DET_LOG2_DEGREE, u);
}

ALWAN_INLINE alwan_f64 alwan_det_exp2_f64(alwan_f64 t) {
    /* Split t into integer and fractional parts. floor() works for
     * negative t too (frac stays in [0, 1)). */
    alwan_f64 const int_part = floor(t);
    alwan_f64 const frac_part = t - int_part;
    alwan_f64 const u = alwan_det_normalize_f64(frac_part, 0.0, 1.0);
    alwan_f64 const exp2_frac = alwan_det_horner_f64(
        alwan_det_exp2_coeffs_f64, ALWAN_DET_EXP2_DEGREE, u);
    return ldexp(exp2_frac, (int)int_part);
}

ALWAN_INLINE alwan_f32 alwan_det_exp2_f32(alwan_f32 t) {
    alwan_f32 const int_part = floorf(t);
    alwan_f32 const frac_part = t - int_part;
    alwan_f32 const u = alwan_det_normalize_f32(frac_part, 0.0f, 1.0f);
    alwan_f32 const exp2_frac = alwan_det_horner_f32(
        alwan_det_exp2_coeffs_f32, ALWAN_DET_EXP2_DEGREE, u);
    return ldexpf(exp2_frac, (int)int_part);
}

ALWAN_INLINE alwan_f64 alwan_det_log_f64(alwan_f64 x) {
    /* ln(x) = log2(x) * ln(2). The constant 0.6931... is exact in f64. */
    return alwan_det_log2_f64(x) * 0.69314718055994530941723212145817657;
}
ALWAN_INLINE alwan_f32 alwan_det_log_f32(alwan_f32 x) {
    return alwan_det_log2_f32(x) * 0.69314718055994530941723212145817657f;
}

ALWAN_INLINE alwan_f64 alwan_det_exp_f64(alwan_f64 x) {
    /* e^x = 2^(x / ln(2)) = 2^(x * 1.4426950...). */
    return alwan_det_exp2_f64(x * 1.4426950408889634073599246810018922);
}
ALWAN_INLINE alwan_f32 alwan_det_exp_f32(alwan_f32 x) {
    return alwan_det_exp2_f32(x * 1.4426950408889634073599246810018922f);
}

/* pow(x, e) for positive base x. For x = 0 returns 0. For x < 0
 * returns 0 (det-mode convention; libm returns NaN for non-integer
 * exponents). */
ALWAN_INLINE alwan_f64 alwan_det_pow_pos_f64(alwan_f64 x, alwan_f64 e) {
    if (x <= 0.0) return 0.0;
    return alwan_det_exp2_f64(e * alwan_det_log2_f64(x));
}
ALWAN_INLINE alwan_f32 alwan_det_pow_pos_f32(alwan_f32 x, alwan_f32 e) {
    if (x <= 0.0f) return 0.0f;
    return alwan_det_exp2_f32(e * alwan_det_log2_f32(x));
}

/* Cube root via pow_pos. Handles negative x by sign-preservation
 * (matches libm cbrt behaviour). */
ALWAN_INLINE alwan_f64 alwan_det_cbrt_f64(alwan_f64 x) {
    if (x == 0.0) return 0.0;
    alwan_f64 const a = (x < 0.0) ? -x : x;
    alwan_f64 const r = alwan_det_pow_pos_f64(a, 1.0 / 3.0);
    return (x < 0.0) ? -r : r;
}
ALWAN_INLINE alwan_f32 alwan_det_cbrt_f32(alwan_f32 x) {
    if (x == 0.0f) return 0.0f;
    alwan_f32 const a = (x < 0.0f) ? -x : x;
    alwan_f32 const r = alwan_det_pow_pos_f32(a, 1.0f / 3.0f);
    return (x < 0.0f) ? -r : r;
}

/* ----------------------------------------------------------------
 * Generic linear+power OETF/EOTF evaluator. Used by every TF whose
 * shape is `linear * x for x < break, alpha * pow(x, exp) - beta`
 * (sRGB, BT.2020, BT.709, ...). Each TF supplies its own constants
 * and polynomial coefficients via the per-TF `alwan_det_<tf>_coeffs.h`.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan__det_lin_pow_oetf_f64(
    alwan_f64 x,
    alwan_f64 break_x, alwan_f64 split,
    alwan_f64 linear_slope, alwan_f64 alpha, alwan_f64 beta,
    alwan_f64 const *lo_coeffs, int lo_degree,
    alwan_f64 const *hi_coeffs, int hi_degree
) {
    if (x <= break_x) return linear_slope * x;
    alwan_f64 power;
    if (x < split) {
        alwan_f64 const u = alwan_det_normalize_f64(x, break_x, split);
        power = alwan_det_horner_f64(lo_coeffs, lo_degree, u);
    } else {
        alwan_f64 const u = alwan_det_normalize_f64(x, split, 1.0);
        power = alwan_det_horner_f64(hi_coeffs, hi_degree, u);
    }
    return alpha * power - beta;
}

ALWAN_INLINE alwan_f32 alwan__det_lin_pow_oetf_f32(
    alwan_f32 x,
    alwan_f32 break_x, alwan_f32 split,
    alwan_f32 linear_slope, alwan_f32 alpha, alwan_f32 beta,
    alwan_f32 const *lo_coeffs, int lo_degree,
    alwan_f32 const *hi_coeffs, int hi_degree
) {
    if (x <= break_x) return linear_slope * x;
    alwan_f32 power;
    if (x < split) {
        alwan_f32 const u = alwan_det_normalize_f32(x, break_x, split);
        power = alwan_det_horner_f32(lo_coeffs, lo_degree, u);
    } else {
        alwan_f32 const u = alwan_det_normalize_f32(x, split, 1.0f);
        power = alwan_det_horner_f32(hi_coeffs, hi_degree, u);
    }
    return alpha * power - beta;
}

ALWAN_INLINE alwan_f64 alwan__det_lin_pow_eotf_f64(
    alwan_f64 x,
    alwan_f64 enc_break, alwan_f64 linear_slope,
    alwan_f64 alpha, alwan_f64 beta,
    alwan_f64 poly_lo,
    alwan_f64 const *coeffs, int degree
) {
    if (x <= enc_break) return x / linear_slope;
    alwan_f64 const z = (x + beta) / alpha;
    alwan_f64 const u = alwan_det_normalize_f64(z, poly_lo, 1.0);
    return alwan_det_horner_f64(coeffs, degree, u);
}

ALWAN_INLINE alwan_f32 alwan__det_lin_pow_eotf_f32(
    alwan_f32 x,
    alwan_f32 enc_break, alwan_f32 linear_slope,
    alwan_f32 alpha, alwan_f32 beta,
    alwan_f32 poly_lo,
    alwan_f32 const *coeffs, int degree
) {
    if (x <= enc_break) return x / linear_slope;
    alwan_f32 const z = (x + beta) / alpha;
    alwan_f32 const u = alwan_det_normalize_f32(z, poly_lo, 1.0f);
    return alwan_det_horner_f32(coeffs, degree, u);
}

/* ----------------------------------------------------------------
 * sRGB OETF / EOTF
 * IEC 61966-2-1: linear=12.92, alpha=1.055, exp=1/2.4, break=0.0031308.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan_det_srgb_oetf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_oetf_f64(x,
        ALWAN_DET_SRGB_OETF_BREAK, ALWAN_DET_SRGB_OETF_SPLIT,
        ALWAN_DET_SRGB_OETF_LINEAR, ALWAN_DET_SRGB_OETF_ALPHA, ALWAN_DET_SRGB_OETF_BETA,
        alwan_det_srgb_oetf_lo_coeffs_f64, ALWAN_DET_SRGB_OETF_LO_DEGREE,
        alwan_det_srgb_oetf_hi_coeffs_f64, ALWAN_DET_SRGB_OETF_HI_DEGREE);
}

ALWAN_INLINE alwan_f32 alwan_det_srgb_oetf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_oetf_f32(x,
        (alwan_f32)ALWAN_DET_SRGB_OETF_BREAK, (alwan_f32)ALWAN_DET_SRGB_OETF_SPLIT,
        (alwan_f32)ALWAN_DET_SRGB_OETF_LINEAR, (alwan_f32)ALWAN_DET_SRGB_OETF_ALPHA,
        (alwan_f32)ALWAN_DET_SRGB_OETF_BETA,
        alwan_det_srgb_oetf_lo_coeffs_f32, ALWAN_DET_SRGB_OETF_LO_DEGREE,
        alwan_det_srgb_oetf_hi_coeffs_f32, ALWAN_DET_SRGB_OETF_HI_DEGREE);
}

ALWAN_INLINE alwan_f64 alwan_det_srgb_eotf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_eotf_f64(x,
        ALWAN_DET_SRGB_EOTF_BREAK, ALWAN_DET_SRGB_OETF_LINEAR,
        ALWAN_DET_SRGB_OETF_ALPHA, ALWAN_DET_SRGB_OETF_BETA,
        ALWAN_DET_SRGB_EOTF_POLY_LO,
        alwan_det_srgb_eotf_coeffs_f64, ALWAN_DET_SRGB_EOTF_DEGREE);
}

ALWAN_INLINE alwan_f32 alwan_det_srgb_eotf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_eotf_f32(x,
        (alwan_f32)ALWAN_DET_SRGB_EOTF_BREAK, (alwan_f32)ALWAN_DET_SRGB_OETF_LINEAR,
        (alwan_f32)ALWAN_DET_SRGB_OETF_ALPHA, (alwan_f32)ALWAN_DET_SRGB_OETF_BETA,
        (alwan_f32)ALWAN_DET_SRGB_EOTF_POLY_LO,
        alwan_det_srgb_eotf_coeffs_f32, ALWAN_DET_SRGB_EOTF_DEGREE);
}

/* ----------------------------------------------------------------
 * BT.2020 / BT.709 OETF / EOTF
 * ITU-R BT.2020-2: linear=4.5, alpha=1.099, exp=0.45, break=0.018.
 * BT.709 uses the same constants in the 4-decimal form, so this same
 * polynomial serves both standards.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan_det_bt2020_oetf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_oetf_f64(x,
        ALWAN_DET_BT2020_OETF_BREAK, ALWAN_DET_BT2020_OETF_SPLIT,
        ALWAN_DET_BT2020_OETF_LINEAR, ALWAN_DET_BT2020_OETF_ALPHA, ALWAN_DET_BT2020_OETF_BETA,
        alwan_det_bt2020_oetf_lo_coeffs_f64, ALWAN_DET_BT2020_OETF_LO_DEGREE,
        alwan_det_bt2020_oetf_hi_coeffs_f64, ALWAN_DET_BT2020_OETF_HI_DEGREE);
}

ALWAN_INLINE alwan_f32 alwan_det_bt2020_oetf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_oetf_f32(x,
        (alwan_f32)ALWAN_DET_BT2020_OETF_BREAK, (alwan_f32)ALWAN_DET_BT2020_OETF_SPLIT,
        (alwan_f32)ALWAN_DET_BT2020_OETF_LINEAR, (alwan_f32)ALWAN_DET_BT2020_OETF_ALPHA,
        (alwan_f32)ALWAN_DET_BT2020_OETF_BETA,
        alwan_det_bt2020_oetf_lo_coeffs_f32, ALWAN_DET_BT2020_OETF_LO_DEGREE,
        alwan_det_bt2020_oetf_hi_coeffs_f32, ALWAN_DET_BT2020_OETF_HI_DEGREE);
}

ALWAN_INLINE alwan_f64 alwan_det_bt2020_eotf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_eotf_f64(x,
        ALWAN_DET_BT2020_EOTF_BREAK, ALWAN_DET_BT2020_OETF_LINEAR,
        ALWAN_DET_BT2020_OETF_ALPHA, ALWAN_DET_BT2020_OETF_BETA,
        ALWAN_DET_BT2020_EOTF_POLY_LO,
        alwan_det_bt2020_eotf_coeffs_f64, ALWAN_DET_BT2020_EOTF_DEGREE);
}

ALWAN_INLINE alwan_f32 alwan_det_bt2020_eotf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_eotf_f32(x,
        (alwan_f32)ALWAN_DET_BT2020_EOTF_BREAK, (alwan_f32)ALWAN_DET_BT2020_OETF_LINEAR,
        (alwan_f32)ALWAN_DET_BT2020_OETF_ALPHA, (alwan_f32)ALWAN_DET_BT2020_OETF_BETA,
        (alwan_f32)ALWAN_DET_BT2020_EOTF_POLY_LO,
        alwan_det_bt2020_eotf_coeffs_f32, ALWAN_DET_BT2020_EOTF_DEGREE);
}

#else /* ================= GPU backends (single precision) ================= *
 * Inlined deterministic transcendentals for the AgX GPU kernel: same
 * polynomials and coefficient tables as the C _f32 path, but frexp/ldexp/floor
 * are HLSL intrinsics and the Horner loop is inlined with `precise` so dxc does
 * not fuse mul+add into mad (the C path relies on FP_CONTRACT OFF for exactly
 * that). Bit-exact with det-C by construction; runtime parity is pending a GPU
 * test runner. */

ALWAN_INLINE alwan_scalar alwan_det_log2(alwan_scalar x) {
    alwan_scalar e; alwan_scalar m = frexp(x, e);   /* m in [0.5,1), e = exponent */
    alwan_scalar u = (alwan_scalar)2.0 * (m - (alwan_scalar)0.5) / (alwan_scalar)0.5 - (alwan_scalar)1.0;
    precise alwan_scalar acc = alwan_det_log2_coeffs_f32[ALWAN_DET_LOG2_DEGREE];
    [unroll] for (int i = ALWAN_DET_LOG2_DEGREE - 1; i >= 0; --i) {
        precise alwan_scalar t = acc * u; acc = t + alwan_det_log2_coeffs_f32[i];
    }
    return e + acc;
}

ALWAN_INLINE alwan_scalar alwan_det_exp2(alwan_scalar t) {
    alwan_scalar ip = floor(t);
    alwan_scalar u = (alwan_scalar)2.0 * (t - ip) - (alwan_scalar)1.0;  /* frac[0,1)->[-1,1] */
    precise alwan_scalar acc = alwan_det_exp2_coeffs_f32[ALWAN_DET_EXP2_DEGREE];
    [unroll] for (int i = ALWAN_DET_EXP2_DEGREE - 1; i >= 0; --i) {
        precise alwan_scalar tt = acc * u; acc = tt + alwan_det_exp2_coeffs_f32[i];
    }
    return ldexp(acc, ip);
}

ALWAN_INLINE alwan_scalar alwan_det_pow_pos(alwan_scalar x, alwan_scalar e) {
    if (x <= (alwan_scalar)0.0) return (alwan_scalar)0.0;
    return alwan_det_exp2(e * alwan_det_log2(x));
}

ALWAN_INLINE alwan_scalar alwan_det_srgb_eotf(alwan_scalar x) {
    if (x <= (alwan_scalar)ALWAN_DET_SRGB_EOTF_BREAK)
        return x / (alwan_scalar)ALWAN_DET_SRGB_OETF_LINEAR;
    alwan_scalar z = (x + (alwan_scalar)ALWAN_DET_SRGB_OETF_BETA) / (alwan_scalar)ALWAN_DET_SRGB_OETF_ALPHA;
    alwan_scalar lo = (alwan_scalar)ALWAN_DET_SRGB_EOTF_POLY_LO;
    alwan_scalar u = (alwan_scalar)2.0 * (z - lo) / ((alwan_scalar)1.0 - lo) - (alwan_scalar)1.0;
    precise alwan_scalar acc = alwan_det_srgb_eotf_coeffs_f32[ALWAN_DET_SRGB_EOTF_DEGREE];
    [unroll] for (int i = ALWAN_DET_SRGB_EOTF_DEGREE - 1; i >= 0; --i) {
        precise alwan_scalar t = acc * u; acc = t + alwan_det_srgb_eotf_coeffs_f32[i];
    }
    return acc;
}

/* Two-segment (lo/hi split) OETF evaluator, mirroring alwan__det_lin_pow_oetf_f32:
 * same coefficient tables, same normalisation, same rounding order (precise
 * blocks mad-fusion, matching the C FP_CONTRACT-off contract). */

ALWAN_INLINE alwan_scalar alwan_det_srgb_oetf(alwan_scalar x) {
    if (x <= (alwan_scalar)ALWAN_DET_SRGB_OETF_BREAK)
        return (alwan_scalar)ALWAN_DET_SRGB_OETF_LINEAR * x;
    precise alwan_scalar acc;
    if (x < (alwan_scalar)ALWAN_DET_SRGB_OETF_SPLIT) {
        alwan_scalar b = (alwan_scalar)ALWAN_DET_SRGB_OETF_BREAK, s = (alwan_scalar)ALWAN_DET_SRGB_OETF_SPLIT;
        alwan_scalar u = (alwan_scalar)2.0 * (x - b) / (s - b) - (alwan_scalar)1.0;
        acc = alwan_det_srgb_oetf_lo_coeffs_f32[ALWAN_DET_SRGB_OETF_LO_DEGREE];
        [unroll] for (int i = ALWAN_DET_SRGB_OETF_LO_DEGREE - 1; i >= 0; --i) {
            precise alwan_scalar t = acc * u; acc = t + alwan_det_srgb_oetf_lo_coeffs_f32[i];
        }
    } else {
        alwan_scalar s = (alwan_scalar)ALWAN_DET_SRGB_OETF_SPLIT;
        alwan_scalar u = (alwan_scalar)2.0 * (x - s) / ((alwan_scalar)1.0 - s) - (alwan_scalar)1.0;
        acc = alwan_det_srgb_oetf_hi_coeffs_f32[ALWAN_DET_SRGB_OETF_HI_DEGREE];
        [unroll] for (int i = ALWAN_DET_SRGB_OETF_HI_DEGREE - 1; i >= 0; --i) {
            precise alwan_scalar t = acc * u; acc = t + alwan_det_srgb_oetf_hi_coeffs_f32[i];
        }
    }
    return (alwan_scalar)ALWAN_DET_SRGB_OETF_ALPHA * acc - (alwan_scalar)ALWAN_DET_SRGB_OETF_BETA;
}

ALWAN_INLINE alwan_scalar alwan_det_bt2020_oetf(alwan_scalar x) {
    if (x <= (alwan_scalar)ALWAN_DET_BT2020_OETF_BREAK)
        return (alwan_scalar)ALWAN_DET_BT2020_OETF_LINEAR * x;
    precise alwan_scalar acc;
    if (x < (alwan_scalar)ALWAN_DET_BT2020_OETF_SPLIT) {
        alwan_scalar b = (alwan_scalar)ALWAN_DET_BT2020_OETF_BREAK, s = (alwan_scalar)ALWAN_DET_BT2020_OETF_SPLIT;
        alwan_scalar u = (alwan_scalar)2.0 * (x - b) / (s - b) - (alwan_scalar)1.0;
        acc = alwan_det_bt2020_oetf_lo_coeffs_f32[ALWAN_DET_BT2020_OETF_LO_DEGREE];
        [unroll] for (int i = ALWAN_DET_BT2020_OETF_LO_DEGREE - 1; i >= 0; --i) {
            precise alwan_scalar t = acc * u; acc = t + alwan_det_bt2020_oetf_lo_coeffs_f32[i];
        }
    } else {
        alwan_scalar s = (alwan_scalar)ALWAN_DET_BT2020_OETF_SPLIT;
        alwan_scalar u = (alwan_scalar)2.0 * (x - s) / ((alwan_scalar)1.0 - s) - (alwan_scalar)1.0;
        acc = alwan_det_bt2020_oetf_hi_coeffs_f32[ALWAN_DET_BT2020_OETF_HI_DEGREE];
        [unroll] for (int i = ALWAN_DET_BT2020_OETF_HI_DEGREE - 1; i >= 0; --i) {
            precise alwan_scalar t = acc * u; acc = t + alwan_det_bt2020_oetf_hi_coeffs_f32[i];
        }
    }
    return (alwan_scalar)ALWAN_DET_BT2020_OETF_ALPHA * acc - (alwan_scalar)ALWAN_DET_BT2020_OETF_BETA;
}

ALWAN_INLINE alwan_scalar alwan_det_bt2020_eotf(alwan_scalar x) {
    if (x <= (alwan_scalar)ALWAN_DET_BT2020_EOTF_BREAK)
        return x / (alwan_scalar)ALWAN_DET_BT2020_OETF_LINEAR;
    alwan_scalar z = (x + (alwan_scalar)ALWAN_DET_BT2020_OETF_BETA) / (alwan_scalar)ALWAN_DET_BT2020_OETF_ALPHA;
    alwan_scalar lo = (alwan_scalar)ALWAN_DET_BT2020_EOTF_POLY_LO;
    alwan_scalar u = (alwan_scalar)2.0 * (z - lo) / ((alwan_scalar)1.0 - lo) - (alwan_scalar)1.0;
    precise alwan_scalar acc = alwan_det_bt2020_eotf_coeffs_f32[ALWAN_DET_BT2020_EOTF_DEGREE];
    [unroll] for (int i = ALWAN_DET_BT2020_EOTF_DEGREE - 1; i >= 0; --i) {
        precise alwan_scalar t = acc * u; acc = t + alwan_det_bt2020_eotf_coeffs_f32[i];
    }
    return acc;
}

#endif /* ALWAN_BACKEND_C else GPU */

#endif /* ALWAN_DETERMINISTIC_H */
