/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Soufiane KHIAT
 * SPDX-License-Identifier: MIT
 *
 * alwan_deterministic.h - bit-exact polynomial implementations for
 * primitives that would otherwise call libm.
 *
 * Active only when `ALWAN_DETERMINISTIC=1` is defined. Each function
 * here approximates a transcendental over its valid colour-science
 * range with a polynomial whose coefficients are committed to source
 * (generated by alwan_dev/gendata/gen_*.py), then evaluated via
 * Horner's method with FMA contraction explicitly disabled.
 *
 * Two guarantees together give cross-platform bit-exactness:
 *
 *   1. The polynomial is fully specified (coefficients in
 *      alwan_det_*_coeffs.h, no platform-dependent input).
 *   2. `#pragma STDC FP_CONTRACT OFF` blocks the compiler from
 *      fusing `a*b + c` into a single-rounding FMA, which would
 *      otherwise differ between x86 (with/without -mfma) and
 *      aarch64 (FMA mandatory).
 *
 * The polynomial does NOT match libm bit-for-bit. It approximates
 * the same mathematical function within a documented error budget
 * (typically <0.05% absolute for sRGB-range inputs). The point is
 * that *every* deterministic build, on every platform, returns the
 * same bytes for the same inputs — that's what
 * cross-platform-determinism CI verifies via output hashing.
 *
 * Currently covered:
 *   - sRGB     OETF/EOTF
 *   - BT.2020  OETF/EOTF (also valid for BT.709 — same constants)
 *
 * Pipeline (PQ, HLG, Lab cube root, ACES splines, ...) follow in
 * later phases — see road_to_determinism.md §6.8.
 */

#ifndef ALWAN_DETERMINISTIC_H
#define ALWAN_DETERMINISTIC_H

/* Block FMA contraction inside this header. The CMake build also
 * passes `-ffp-contract=off` (clang/gcc) or `/fp:precise` (MSVC) for
 * defense in depth; the per-file pragma is belt-and-suspenders so a
 * downstream consumer can't accidentally re-fuse our polynomial
 * evaluations. MSVC's STDC support is incomplete — its equivalent is
 * `#pragma fp_contract(off)` with different syntax. */
#if defined(__clang__) || (defined(__GNUC__) && !defined(__INTEL_COMPILER))
#  pragma STDC FP_CONTRACT OFF
#elif defined(_MSC_VER)
#  pragma fp_contract(off)
#endif

#include "../alwan_types.h"
#include "alwan_det_srgb_coeffs.h"
#include "alwan_det_bt2020_coeffs.h"

/* ----------------------------------------------------------------
 * Horner evaluation — explicit `mul; add` so FP_CONTRACT OFF actually
 * has something to refuse to fuse.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64
alwan_det_horner_f64(alwan_f64 const *coeffs, int degree, alwan_f64 x) {
    alwan_f64 acc = coeffs[degree];
    for (int i = degree - 1; i >= 0; i--) {
        alwan_f64 const t = acc * x;        /* round 1 */
        acc = t + coeffs[i];                /* round 2 — never fused */
    }
    return acc;
}

ALWAN_INLINE alwan_f32
alwan_det_horner_f32(alwan_f32 const *coeffs, int degree, alwan_f32 x) {
    alwan_f32 acc = coeffs[degree];
    for (int i = degree - 1; i >= 0; i--) {
        alwan_f32 const t = acc * x;
        acc = t + coeffs[i];
    }
    return acc;
}

/* Domain normalisation: maps x in [lo, hi] to u in [-1, 1]. */
ALWAN_INLINE alwan_f64 alwan_det_normalize_f64(alwan_f64 x, alwan_f64 lo, alwan_f64 hi) {
    return 2.0 * (x - lo) / (hi - lo) - 1.0;
}
ALWAN_INLINE alwan_f32 alwan_det_normalize_f32(alwan_f32 x, alwan_f32 lo, alwan_f32 hi) {
    return 2.0f * (x - lo) / (hi - lo) - 1.0f;
}

/* ----------------------------------------------------------------
 * Generic linear+power OETF/EOTF evaluator. Used by every TF whose
 * shape is `linear * x for x < break, alpha * pow(x, exp) - beta`
 * (sRGB, BT.2020, BT.709, ...). Each TF supplies its own constants
 * and polynomial coefficients via the per-TF `alwan_det_<tf>_coeffs.h`.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan__det_lin_pow_oetf_f64(
    alwan_f64 x,
    alwan_f64 break_x, alwan_f64 split,
    alwan_f64 linear_slope, alwan_f64 alpha, alwan_f64 beta,
    alwan_f64 const *lo_coeffs, int lo_degree,
    alwan_f64 const *hi_coeffs, int hi_degree
) {
    if (x <= break_x) return linear_slope * x;
    alwan_f64 power;
    if (x < split) {
        alwan_f64 const u = alwan_det_normalize_f64(x, break_x, split);
        power = alwan_det_horner_f64(lo_coeffs, lo_degree, u);
    } else {
        alwan_f64 const u = alwan_det_normalize_f64(x, split, 1.0);
        power = alwan_det_horner_f64(hi_coeffs, hi_degree, u);
    }
    return alpha * power - beta;
}

ALWAN_INLINE alwan_f32 alwan__det_lin_pow_oetf_f32(
    alwan_f32 x,
    alwan_f32 break_x, alwan_f32 split,
    alwan_f32 linear_slope, alwan_f32 alpha, alwan_f32 beta,
    alwan_f32 const *lo_coeffs, int lo_degree,
    alwan_f32 const *hi_coeffs, int hi_degree
) {
    if (x <= break_x) return linear_slope * x;
    alwan_f32 power;
    if (x < split) {
        alwan_f32 const u = alwan_det_normalize_f32(x, break_x, split);
        power = alwan_det_horner_f32(lo_coeffs, lo_degree, u);
    } else {
        alwan_f32 const u = alwan_det_normalize_f32(x, split, 1.0f);
        power = alwan_det_horner_f32(hi_coeffs, hi_degree, u);
    }
    return alpha * power - beta;
}

ALWAN_INLINE alwan_f64 alwan__det_lin_pow_eotf_f64(
    alwan_f64 x,
    alwan_f64 enc_break, alwan_f64 linear_slope,
    alwan_f64 alpha, alwan_f64 beta,
    alwan_f64 poly_lo,
    alwan_f64 const *coeffs, int degree
) {
    if (x <= enc_break) return x / linear_slope;
    alwan_f64 const z = (x + beta) / alpha;
    alwan_f64 const u = alwan_det_normalize_f64(z, poly_lo, 1.0);
    return alwan_det_horner_f64(coeffs, degree, u);
}

ALWAN_INLINE alwan_f32 alwan__det_lin_pow_eotf_f32(
    alwan_f32 x,
    alwan_f32 enc_break, alwan_f32 linear_slope,
    alwan_f32 alpha, alwan_f32 beta,
    alwan_f32 poly_lo,
    alwan_f32 const *coeffs, int degree
) {
    if (x <= enc_break) return x / linear_slope;
    alwan_f32 const z = (x + beta) / alpha;
    alwan_f32 const u = alwan_det_normalize_f32(z, poly_lo, 1.0f);
    return alwan_det_horner_f32(coeffs, degree, u);
}

/* ----------------------------------------------------------------
 * sRGB OETF / EOTF
 * IEC 61966-2-1: linear=12.92, alpha=1.055, exp=1/2.4, break=0.0031308.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan_det_srgb_oetf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_oetf_f64(x,
        ALWAN_DET_SRGB_OETF_BREAK, ALWAN_DET_SRGB_OETF_SPLIT,
        ALWAN_DET_SRGB_OETF_LINEAR, ALWAN_DET_SRGB_OETF_ALPHA, ALWAN_DET_SRGB_OETF_BETA,
        alwan_det_srgb_oetf_lo_coeffs_f64, ALWAN_DET_SRGB_OETF_LO_DEGREE,
        alwan_det_srgb_oetf_hi_coeffs_f64, ALWAN_DET_SRGB_OETF_HI_DEGREE);
}

ALWAN_INLINE alwan_f32 alwan_det_srgb_oetf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_oetf_f32(x,
        (alwan_f32)ALWAN_DET_SRGB_OETF_BREAK, (alwan_f32)ALWAN_DET_SRGB_OETF_SPLIT,
        (alwan_f32)ALWAN_DET_SRGB_OETF_LINEAR, (alwan_f32)ALWAN_DET_SRGB_OETF_ALPHA,
        (alwan_f32)ALWAN_DET_SRGB_OETF_BETA,
        alwan_det_srgb_oetf_lo_coeffs_f32, ALWAN_DET_SRGB_OETF_LO_DEGREE,
        alwan_det_srgb_oetf_hi_coeffs_f32, ALWAN_DET_SRGB_OETF_HI_DEGREE);
}

ALWAN_INLINE alwan_f64 alwan_det_srgb_eotf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_eotf_f64(x,
        ALWAN_DET_SRGB_EOTF_BREAK, ALWAN_DET_SRGB_OETF_LINEAR,
        ALWAN_DET_SRGB_OETF_ALPHA, ALWAN_DET_SRGB_OETF_BETA,
        ALWAN_DET_SRGB_EOTF_POLY_LO,
        alwan_det_srgb_eotf_coeffs_f64, ALWAN_DET_SRGB_EOTF_DEGREE);
}

ALWAN_INLINE alwan_f32 alwan_det_srgb_eotf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_eotf_f32(x,
        (alwan_f32)ALWAN_DET_SRGB_EOTF_BREAK, (alwan_f32)ALWAN_DET_SRGB_OETF_LINEAR,
        (alwan_f32)ALWAN_DET_SRGB_OETF_ALPHA, (alwan_f32)ALWAN_DET_SRGB_OETF_BETA,
        (alwan_f32)ALWAN_DET_SRGB_EOTF_POLY_LO,
        alwan_det_srgb_eotf_coeffs_f32, ALWAN_DET_SRGB_EOTF_DEGREE);
}

/* ----------------------------------------------------------------
 * BT.2020 / BT.709 OETF / EOTF
 * ITU-R BT.2020-2: linear=4.5, alpha=1.099, exp=0.45, break=0.018.
 * BT.709 uses the same constants in the 4-decimal form, so this same
 * polynomial serves both standards.
 * ---------------------------------------------------------------- */

ALWAN_INLINE alwan_f64 alwan_det_bt2020_oetf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_oetf_f64(x,
        ALWAN_DET_BT2020_OETF_BREAK, ALWAN_DET_BT2020_OETF_SPLIT,
        ALWAN_DET_BT2020_OETF_LINEAR, ALWAN_DET_BT2020_OETF_ALPHA, ALWAN_DET_BT2020_OETF_BETA,
        alwan_det_bt2020_oetf_lo_coeffs_f64, ALWAN_DET_BT2020_OETF_LO_DEGREE,
        alwan_det_bt2020_oetf_hi_coeffs_f64, ALWAN_DET_BT2020_OETF_HI_DEGREE);
}

ALWAN_INLINE alwan_f32 alwan_det_bt2020_oetf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_oetf_f32(x,
        (alwan_f32)ALWAN_DET_BT2020_OETF_BREAK, (alwan_f32)ALWAN_DET_BT2020_OETF_SPLIT,
        (alwan_f32)ALWAN_DET_BT2020_OETF_LINEAR, (alwan_f32)ALWAN_DET_BT2020_OETF_ALPHA,
        (alwan_f32)ALWAN_DET_BT2020_OETF_BETA,
        alwan_det_bt2020_oetf_lo_coeffs_f32, ALWAN_DET_BT2020_OETF_LO_DEGREE,
        alwan_det_bt2020_oetf_hi_coeffs_f32, ALWAN_DET_BT2020_OETF_HI_DEGREE);
}

ALWAN_INLINE alwan_f64 alwan_det_bt2020_eotf_f64(alwan_f64 x) {
    return alwan__det_lin_pow_eotf_f64(x,
        ALWAN_DET_BT2020_EOTF_BREAK, ALWAN_DET_BT2020_OETF_LINEAR,
        ALWAN_DET_BT2020_OETF_ALPHA, ALWAN_DET_BT2020_OETF_BETA,
        ALWAN_DET_BT2020_EOTF_POLY_LO,
        alwan_det_bt2020_eotf_coeffs_f64, ALWAN_DET_BT2020_EOTF_DEGREE);
}

ALWAN_INLINE alwan_f32 alwan_det_bt2020_eotf_f32(alwan_f32 x) {
    return alwan__det_lin_pow_eotf_f32(x,
        (alwan_f32)ALWAN_DET_BT2020_EOTF_BREAK, (alwan_f32)ALWAN_DET_BT2020_OETF_LINEAR,
        (alwan_f32)ALWAN_DET_BT2020_OETF_ALPHA, (alwan_f32)ALWAN_DET_BT2020_OETF_BETA,
        (alwan_f32)ALWAN_DET_BT2020_EOTF_POLY_LO,
        alwan_det_bt2020_eotf_coeffs_f32, ALWAN_DET_BT2020_EOTF_DEGREE);
}

#endif /* ALWAN_DETERMINISTIC_H */
