#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generate Alwan test data from colour-science (Modular Architecture).
.DESCRIPTION
    Orchestrates Python scripts to generate test reference data.
    Test inputs are hardcoded, expected outputs come from colour-science.
#>

$ErrorActionPreference = "Stop"

Write-Host "========================================"
Write-Host "Alwan Test Data Generation (Modular v2.0)"
Write-Host "========================================"
Write-Host ""

# Output directory
$TEST_DIR = "tests/reference_values"

# Check Python
Write-Host "Checking Python installation..."
$python = Get-Command python -ErrorAction SilentlyContinue
if (-not $python) {
    Write-Host "ERROR: Python not found in PATH" -ForegroundColor Red
    exit 1
}
$pythonVersion = & python --version 2>&1
Write-Host "  Found: $pythonVersion" -ForegroundColor Green

# Note: Skipping colour-science version check (can hang on import)
# Individual modules will report errors if colour-science is not available
Write-Host "Note: colour-science is required (install with: pip install colour-science)" -ForegroundColor Cyan
Write-Host ""

# Ensure output directory exists
if (-not (Test-Path $TEST_DIR)) {
    New-Item -ItemType Directory -Path $TEST_DIR -Force | Out-Null
}
Write-Host "  Output directory: $TEST_DIR" -ForegroundColor Cyan
Write-Host ""

# Test generation scripts
$testScripts = @(
    @{Name="Test Reference Values"; Script="gendata/data/test_reference_values.py"},
    @{Name="Hellwig2022"; Script="gendata/tests/hellwig2022.py"},
    @{Name="Kim2009"; Script="gendata/tests/kim2009.py"},
    @{Name="LLAB"; Script="gendata/tests/llab.py"},
    @{Name="ATD95"; Script="gendata/tests/atd95.py"}
)

# Run CAM fixtures generator separately (outputs to parent dir)
Write-Host "Generating CAM fixtures (CIECAM02, CAM16)..." -ForegroundColor Yellow
try {
    $output = cmd /c "python gendata/data/cam_fixtures.py tests 2>&1"
    $exitCode = $LASTEXITCODE
    if ($exitCode -eq 0) {
        Write-Host $output
        Write-Host "  [OK] CAM fixtures generated" -ForegroundColor Green
    } else {
        Write-Host "  WARNING: Failed to generate CAM fixtures" -ForegroundColor Red
        Write-Host $output -ForegroundColor Gray
    }
} catch {
    Write-Host "  WARNING: Failed to generate CAM fixtures: $($_.Exception.Message)" -ForegroundColor Red
}
Write-Host ""

# Run each test generation script
$successCount = 0
$failCount = 0

foreach ($item in $testScripts) {
    Write-Host "Generating $($item.Name) test data..." -ForegroundColor Yellow

    # Capture output and errors, suppress PowerShell error handling
    try {
        $output = cmd /c "python `"$($item.Script)`" `"$TEST_DIR`" 2>&1"
        $exitCode = $LASTEXITCODE
    } catch {
        $output = $_.Exception.Message
        $exitCode = 1
    }

    if ($exitCode -eq 0) {
        Write-Host $output
        $successCount++
    } else {
        Write-Host "  WARNING: Failed to generate $($item.Name) test data" -ForegroundColor Red
        Write-Host $output -ForegroundColor Gray
        $failCount++
    }
    Write-Host ""
}

# Summary
Write-Host "========================================"
Write-Host "Test Data Generation Summary"
Write-Host "========================================"
Write-Host "  Completed: $successCount test modules" -ForegroundColor Green
if ($failCount -gt 0) {
    Write-Host "  Failed: $failCount test modules" -ForegroundColor Red
}
Write-Host "  Output directory: $TEST_DIR" -ForegroundColor Cyan
Write-Host ""

if ($failCount -eq 0) {
    Write-Host "All test data generation completed successfully!" -ForegroundColor Green
} else {
    Write-Host "WARNING: Some test modules failed (see above)" -ForegroundColor Yellow
}
Write-Host ""

# Show what's remaining
Write-Host "Note: All test generators completed!" -ForegroundColor Gray
Write-Host "  - Test Reference Values: Hunter Lab, white points, Delta E, etc." -ForegroundColor Green
Write-Host "  - Test-specific: Hellwig2022, Kim2009, LLAB, ATD95" -ForegroundColor Green
Write-Host "  - Fixture-based: CIECAM02, CAM16 (generated by cam_fixtures.py)" -ForegroundColor Green
Write-Host "  See gendata/PROGRESS.md for full status" -ForegroundColor Gray
