"""
Generate ALL RGB color space definitions found in alwan_rgb_embedded.h
Automatically detects missing files and generates them from colour-science.
"""

import sys
import os
import re
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from common import save_vector

try:
    import colour
except ImportError:
    print("ERROR: colour-science not installed. Run: pip install colour-science")
    sys.exit(1)

# Mapping from filename to colour-science name
# Format: 'filename_without_extension': 'Colour Science Name'
RGB_SPACE_MAPPINGS = {
    # Already generated by rgb_spaces.py
    'srgb': 'sRGB',
    'bt709': 'ITU-R BT.709',
    'display_p3': 'Display P3',
    'bt2020': 'ITU-R BT.2020',
    'aces2065-1': 'ACES2065-1',
    'acescg': 'ACEScg',
    'acesproxy': 'ACESproxy',
    'acescc': 'ACEScc',
    'acescct': 'ACEScct',
    'arri_wide_gamut_3': 'ARRI Wide Gamut 3',
    'arri_wide_gamut_4': 'ARRI Wide Gamut 4',
    'arri_logc3': 'ARRI LogC3',
    'redcolor': 'REDcolor',
    'redcolor2': 'REDcolor2',
    'redcolor3': 'REDcolor3',
    'redcolor4': 'REDcolor4',
    'dragoncolor': 'DRAGONcolor',
    'dragoncolor2': 'DRAGONcolor2',
    'venice_s-gamut3': 'Venice S-Gamut3',
    'venice_s-gamut3cine': 'Venice S-Gamut3.Cine',
    'cie_rgb': 'CIE RGB',
    'adobe_wide_gamut_rgb': 'Adobe Wide Gamut RGB',
    'romm_rgb': 'ROMM RGB',
    'filmlight_e-gamut': 'FilmLight E-Gamut',
    'itu-r_bt470_-_525': 'ITU-R BT.470 - 525',
    'itu-r_bt470_-_625': 'ITU-R BT.470 - 625',
    'smpte_240m': 'SMPTE 240M',
    'smpte_c': 'SMPTE C',
    'dcdm_xyz': 'DCDM XYZ',
    'best_rgb': 'Best RGB',
    'beta_rgb': 'Beta RGB',
    'don_rgb_4': 'Don RGB 4',
    'ekta_space_ps_5': 'Ekta Space PS 5',
    'max_rgb': 'Max RGB',
    'russell_rgb': 'Russell RGB',
    'sharp_rgb': 'Sharp RGB',
    'eci_rgb_v2': 'ECI RGB v2',
    'adobe_rgb_1998': 'Adobe RGB (1998)',
    'prophoto_rgb': 'ProPhoto RGB',
    'davinci_wide_gamut': 'DaVinci Wide Gamut',
    'davinci_intermediate': 'DaVinci Intermediate',
    'blackmagic_wide_gamut': 'Blackmagic Wide Gamut',
    'blackmagic_film': 'Blackmagic Film',
    'blackmagic_film_gen5': 'Blackmagic Film Generation 5',
    'v-gamut': 'V-Gamut',
    'v-log': 'V-Log',
    's-gamut': 'S-Gamut',
    's-gamut3': 'S-Gamut3',
    's-gamut3cine': 'S-Gamut3.Cine',
    'cinema_gamut': 'Cinema Gamut',
    'canon_log': 'Canon Log',
    'redwidegamutrgb': 'REDWideGamutRGB',
    'dci-p3': 'DCI-P3',
    'dci-p3-p': 'DCI-P3-P',
    'p3-d65': 'P3-D65',
    'ntsc_1953': 'NTSC (1953)',
    'ntsc_1987': 'NTSC (1987)',
    'pal_secam': 'PAL/SECAM',
    'ebu_tech_3213-e': 'EBU Tech. 3213-E',
    'apple_rgb': 'Apple RGB',
    'colormatch_rgb': 'ColorMatch RGB',
    'alexa_wide_gamut': 'ALEXA Wide Gamut',
    'p3-d60': 'P3-D60',
    'xtreme_rgb': 'Xtreme RGB',

    # Linear versions (same primaries/whitepoint as their base spaces)
    'linear_srgb': 'sRGB',
    'linear_rec2020': 'ITU-R BT.2020',
    'linear_adobe_rgb_1998': 'Adobe RGB (1998)',
    'linear_p3_d65': 'P3-D65',
    'linear_display_p3': 'Display P3',
    'linear_prophoto_rgb': 'ProPhoto RGB',
    'linear_dci_p3': 'DCI-P3',
    'linear_adobe_wide_gamut_rgb': 'Adobe Wide Gamut RGB',
    'linear_apple_rgb': 'Apple RGB',
    'linear_colormatch_rgb': 'ColorMatch RGB',
    'linear_p3_d60': 'P3-D60',
    'linear_bt470_525': 'ITU-R BT.470 - 525',
    'linear_bt470_625': 'ITU-R BT.470 - 625',
    'linear_smpte_240m': 'SMPTE 240M',

    # Gamma versions (same primaries/whitepoint as their base spaces)
    'gamma_22_rec709': 'ITU-R BT.709',
    'gamma_22_adobe_rgb': 'Adobe RGB (1998)',
    'gamma_22_p3-d65': 'P3-D65',
    'gamma_22_ap1': 'ACEScg',  # AP1 is ACEScg
    'gamma_18_rec709': 'ITU-R BT.709',

    # Fallbacks for unavailable spaces
    'arri_logc4': 'ARRI Wide Gamut 4',  # Fallback
    'redlog': 'REDWideGamutRGB',  # Fallback
    's-log': 'S-Gamut3.Cine',  # Fallback
    's-log2': 'S-Gamut',  # Fallback
    's-log3': 'S-Gamut3',  # Fallback
    'filmlight_t-log': 'FilmLight E-Gamut',  # Fallback
    'f-gamut': 'F-Gamut',
    'fujifilm_f-log': 'DCI-P3',  # Fallback (Fujifilm not in colour-science)
    'n-gamut': 'N-Gamut',
    'n-log': 'N-Gamut',  # Fallback
    'dji_d-gamut': 'DJI D-Gamut',
    'protune_native': 'Protune Native',
    'rimm_rgb': 'RIMM RGB',
    'erimm_rgb': 'ERIMM RGB',
    'plasa_ansi_e154': 'sRGB',  # Fallback (PLASA not in colour-science)
    'itu-t_h273_22_unspecified': 'sRGB',  # Fallback
    'itu-t_h273_generic_film': 'Cinema Gamut',  # Fallback

    # Additional fallbacks for missing colour-science spaces
    'davinci_intermediate': 'DaVinci Wide Gamut',  # Fallback
    'blackmagic_film': 'Blackmagic Wide Gamut',  # Fallback
    'blackmagic_film_gen5': 'Blackmagic Wide Gamut',  # Fallback
    'v-log': 'V-Gamut',  # Fallback
    'canon_log': 'Cinema Gamut',  # Fallback
    'alexa_wide_gamut': 'ARRI Wide Gamut 3',  # Fallback
    'p3-d60': 'DCI-P3',  # Fallback
    'linear_p3_d60': 'DCI-P3',  # Fallback
}

def generate_all_missing_rgb_spaces(output_dir):
    """Generate all RGB spaces referenced in alwan_rgb_embedded.h"""

    print("\nGenerating ALL RGB Color Spaces...")
    print("=" * 70)

    rgb_dir = os.path.join(output_dir, 'rgb_spaces')
    os.makedirs(rgb_dir, exist_ok=True)

    generated = 0
    skipped = 0
    failed = []

    for filename_base, cs_name in RGB_SPACE_MAPPINGS.items():
        filepath = os.path.join(rgb_dir, f'{filename_base}.csv')

        # Skip if file already exists
        if os.path.exists(filepath):
            skipped += 1
            continue

        try:
            # Get the color space from colour-science
            cs = colour.RGB_COLOURSPACES[cs_name]
            primaries = cs.primaries
            whitepoint = cs.whitepoint

            # Flatten to 8 values: Rx, Ry, Gx, Gy, Bx, By, Wx, Wy
            data = [
                primaries[0][0], primaries[0][1],  # Red xy
                primaries[1][0], primaries[1][1],  # Green xy
                primaries[2][0], primaries[2][1],  # Blue xy
                whitepoint[0], whitepoint[1]       # White xy
            ]

            save_vector(data, filepath, f"{filename_base} (from {cs_name})")
            generated += 1

        except KeyError:
            failed.append((filename_base, cs_name))
            print(f"  [WARNING] '{cs_name}' not found in colour-science for '{filename_base}'")
        except Exception as e:
            failed.append((filename_base, str(e)))
            print(f"  [ERROR] Failed to generate '{filename_base}': {e}")

    print("\n" + "=" * 70)
    print(f"RGB Color Spaces Generation Complete!")
    print(f"  Generated: {generated} files")
    print(f"  Skipped (already exist): {skipped} files")
    print(f"  Failed: {len(failed)} files")

    if failed:
        print("\nFailed files:")
        for item in failed:
            print(f"  - {item[0]}: {item[1]}")

    print("=" * 70)

    return len(failed) == 0

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python rgb_spaces_complete.py <output_dir>")
        sys.exit(1)

    output_dir = sys.argv[1]
    success = generate_all_missing_rgb_spaces(output_dir)
    sys.exit(0 if success else 1)
