/* Test suite for Rayleigh Scattering (Optical Phenomena)
 * Reference: Bodhaine et al. (1999), colour-science implementation
 */

#include "alwan.h"
#include "alwan_internal.h"
#include "test_common.h"
#include <stdio.h>
#include <string.h>

/* ================================================================
 * Reference Data from colour-science
 * Generated by gendata/tests/rayleigh_scattering.py
 * ================================================================ */

/* Wavelengths in nm */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar wavelengths_nm[] = {
#include "reference_values/rayleigh_wavelengths_nm.csv"
};
ALWAN_DIAG_POP
#define NUM_WAVELENGTHS (sizeof(wavelengths_nm) / sizeof(wavelengths_nm[0]))

/* Cross section with default params (cm^2) */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_cross_section_default[] = {
#include "reference_values/rayleigh_cross_section_default.csv"
};
ALWAN_DIAG_POP

/* Optical depth with default params */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_optical_depth_default[] = {
#include "reference_values/rayleigh_optical_depth_default.csv"
};
ALWAN_DIAG_POP

/* CO2 concentration levels */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar co2_levels[] = {
#include "reference_values/rayleigh_co2_levels.csv"
};
ALWAN_DIAG_POP
#define NUM_CO2_LEVELS (sizeof(co2_levels) / sizeof(co2_levels[0]))

/* Cross section at 555nm for different CO2 levels */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_cross_section_co2_555nm[] = {
#include "reference_values/rayleigh_cross_section_co2_555nm.csv"
};
ALWAN_DIAG_POP

/* Pressure levels (Pa) */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar pressures[] = {
#include "reference_values/rayleigh_pressures.csv"
};
ALWAN_DIAG_POP
#define NUM_PRESSURES (sizeof(pressures) / sizeof(pressures[0]))

/* Optical depth at 555nm for different pressures */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_optical_depth_pressure_555nm[] = {
#include "reference_values/rayleigh_optical_depth_pressure_555nm.csv"
};
ALWAN_DIAG_POP

/* Latitudes (degrees) */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar latitudes[] = {
#include "reference_values/rayleigh_latitudes.csv"
};
ALWAN_DIAG_POP
#define NUM_LATITUDES (sizeof(latitudes) / sizeof(latitudes[0]))

/* Optical depth at 555nm for different latitudes */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_optical_depth_latitude_555nm[] = {
#include "reference_values/rayleigh_optical_depth_latitude_555nm.csv"
};
ALWAN_DIAG_POP

/* Altitudes (meters) */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar altitudes[] = {
#include "reference_values/rayleigh_altitudes.csv"
};
ALWAN_DIAG_POP
#define NUM_ALTITUDES (sizeof(altitudes) / sizeof(altitudes[0]))

/* Optical depth at 555nm for different altitudes */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_optical_depth_altitude_555nm[] = {
#include "reference_values/rayleigh_optical_depth_altitude_555nm.csv"
};
ALWAN_DIAG_POP

/* Combined parameter test results */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_optical_depth_combined[] = {
#include "reference_values/rayleigh_optical_depth_combined.csv"
};
ALWAN_DIAG_POP

/* Combined params: lat, alt pairs (Paris, Denver, high altitude) */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar combined_params[] = {
#include "reference_values/rayleigh_combined_params.csv"
};
ALWAN_DIAG_POP

/* SPD parameters: start, end, step */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar spd_params[] = {
#include "reference_values/rayleigh_spd_params.csv"
};
ALWAN_DIAG_POP

/* SPD reference values */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_spd_default[] = {
#include "reference_values/rayleigh_spd_default.csv"
};
ALWAN_DIAG_POP
#define NUM_SPD_VALUES (sizeof(ref_spd_default) / sizeof(ref_spd_default[0]))

/* ================================================================
 * Test Functions
 * ================================================================ */

static int test_atmosphere_params_default(void)
{
    printf("  TEST: Atmosphere params default initialization\n");

    alwan_atmosphere_params params;
    alwan_atmosphere_params_default(&params);

    /* Verify defaults match colour-science constants */
    TEST_ASSERT_NEAR(params.CO2_concentration, ALWAN_LITERAL(300.0), ALWAN_LITERAL(1e-10),
                     "Default CO2 should be 300 ppm");
    TEST_ASSERT_NEAR(params.temperature, ALWAN_LITERAL(288.15), ALWAN_LITERAL(1e-10),
                     "Default temperature should be 288.15 K");
    TEST_ASSERT_NEAR(params.pressure, ALWAN_LITERAL(101325.0), ALWAN_LITERAL(1e-10),
                     "Default pressure should be 101325 Pa");
    TEST_ASSERT_NEAR(params.latitude, ALWAN_LITERAL(0.0), ALWAN_LITERAL(1e-10),
                     "Default latitude should be 0 degrees");
    TEST_ASSERT_NEAR(params.altitude, ALWAN_LITERAL(0.0), ALWAN_LITERAL(1e-10),
                     "Default altitude should be 0 meters");

    return 0;
}

static int test_cross_section_default(void)
{
    printf("  TEST: Cross section with default parameters\n");

    for (size_t i = 0; i < NUM_WAVELENGTHS; i++) {
        alwan_scalar sigma = alwan_rayleigh_cross_section(wavelengths_nm[i], NULL);
        char msg[64];
        sprintf(msg, "Cross section at %.0f nm", wavelengths_nm[i]);
        TEST_ASSERT_REL(sigma, ref_cross_section_default[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_cross_section_co2(void)
{
    printf("  TEST: Cross section at 555nm with different CO2 levels\n");

    alwan_atmosphere_params params;
    alwan_atmosphere_params_default(&params);

    for (size_t i = 0; i < NUM_CO2_LEVELS; i++) {
        params.CO2_concentration = co2_levels[i];
        alwan_scalar sigma = alwan_rayleigh_cross_section(555.0, &params);
        char msg[64];
        sprintf(msg, "Cross section at CO2 = %.0f ppm", co2_levels[i]);
        TEST_ASSERT_REL(sigma, ref_cross_section_co2_555nm[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_optical_depth_default(void)
{
    printf("  TEST: Optical depth with default parameters\n");

    for (size_t i = 0; i < NUM_WAVELENGTHS; i++) {
        alwan_scalar depth = alwan_rayleigh_optical_depth(wavelengths_nm[i], NULL);
        char msg[64];
        sprintf(msg, "Optical depth at %.0f nm", wavelengths_nm[i]);
        TEST_ASSERT_REL(depth, ref_optical_depth_default[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_optical_depth_pressure(void)
{
    printf("  TEST: Optical depth at 555nm with different pressures\n");

    alwan_atmosphere_params params;
    alwan_atmosphere_params_default(&params);

    for (size_t i = 0; i < NUM_PRESSURES; i++) {
        params.pressure = pressures[i];
        alwan_scalar depth = alwan_rayleigh_optical_depth(555.0, &params);
        char msg[64];
        sprintf(msg, "Optical depth at P = %.0f Pa", pressures[i]);
        TEST_ASSERT_REL(depth, ref_optical_depth_pressure_555nm[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_optical_depth_latitude(void)
{
    printf("  TEST: Optical depth at 555nm with different latitudes\n");

    alwan_atmosphere_params params;
    alwan_atmosphere_params_default(&params);

    for (size_t i = 0; i < NUM_LATITUDES; i++) {
        params.latitude = latitudes[i];
        alwan_scalar depth = alwan_rayleigh_optical_depth(555.0, &params);
        char msg[64];
        sprintf(msg, "Optical depth at lat = %.0f deg", latitudes[i]);
        TEST_ASSERT_REL(depth, ref_optical_depth_latitude_555nm[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_optical_depth_altitude(void)
{
    printf("  TEST: Optical depth at 555nm with different altitudes\n");

    alwan_atmosphere_params params;
    alwan_atmosphere_params_default(&params);

    for (size_t i = 0; i < NUM_ALTITUDES; i++) {
        params.altitude = altitudes[i];
        alwan_scalar depth = alwan_rayleigh_optical_depth(555.0, &params);
        char msg[64];
        sprintf(msg, "Optical depth at alt = %.0f m", altitudes[i]);
        TEST_ASSERT_REL(depth, ref_optical_depth_altitude_555nm[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_optical_depth_combined(void)
{
    printf("  TEST: Optical depth with combined location parameters\n");

    alwan_atmosphere_params params;
    alwan_atmosphere_params_default(&params);
    const char* locations[] = {"Paris", "Denver", "High altitude"};

    for (int i = 0; i < 3; i++) {
        params.latitude = combined_params[i * 2];
        params.altitude = combined_params[i * 2 + 1];
        alwan_scalar depth = alwan_rayleigh_optical_depth(555.0, &params);
        char msg[64];
        sprintf(msg, "Optical depth at %s", locations[i]);
        TEST_ASSERT_REL(depth, ref_optical_depth_combined[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_spd(void)
{
    printf("  TEST: Spectral distribution generation\n");

    alwan_scalar out[100];
    int out_count;

    int status = alwan_rayleigh_spd(
        (alwan_scalar)spd_params[0],  /* start */
        (alwan_scalar)spd_params[1],  /* end */
        (alwan_scalar)spd_params[2],  /* step */
        NULL,
        out,
        &out_count
    );

    TEST_ASSERT(status == ALWAN_OK, "SPD generation failed");
    TEST_ASSERT(out_count == (int)NUM_SPD_VALUES, "SPD count mismatch");

    for (int i = 0; i < out_count; i++) {
        char msg[64];
        sprintf(msg, "SPD value at index %d", i);
        TEST_ASSERT_REL(out[i], ref_spd_default[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_spd_error_handling(void)
{
    printf("  TEST: SPD error handling\n");

    alwan_scalar out[100];
    int out_count;
    int status;

    /* Test null output pointer */
    status = alwan_rayleigh_spd(360, 780, 10, NULL, NULL, &out_count);
    TEST_ASSERT(status == -1, "Should return error for null output");

    /* Test null count pointer */
    status = alwan_rayleigh_spd(360, 780, 10, NULL, out, NULL);
    TEST_ASSERT(status == -1, "Should return error for null count");

    /* Test invalid step */
    status = alwan_rayleigh_spd(360, 780, 0, NULL, out, &out_count);
    TEST_ASSERT(status == -1, "Should return error for zero step");

    /* Test invalid range */
    status = alwan_rayleigh_spd(780, 360, 10, NULL, out, &out_count);
    TEST_ASSERT(status == -1, "Should return error for invalid range");

    return 0;
}

/* ================================================================
 * Test Suite
 * ================================================================ */

typedef int (*test_func)(void);

typedef struct {
    const char *name;
    test_func func;
} test_case;

static test_case test_cases[] = {
    {"Atmosphere params default", test_atmosphere_params_default},
    {"Cross section default", test_cross_section_default},
    {"Cross section CO2 variation", test_cross_section_co2},
    {"Optical depth default", test_optical_depth_default},
    {"Optical depth pressure", test_optical_depth_pressure},
    {"Optical depth latitude", test_optical_depth_latitude},
    {"Optical depth altitude", test_optical_depth_altitude},
    {"Optical depth combined", test_optical_depth_combined},
    {"SPD generation", test_spd},
    {"SPD error handling", test_spd_error_handling},
};

#define NUM_TEST_CASES (sizeof(test_cases) / sizeof(test_cases[0]))

int test_49_rayleigh_scattering_main(void)
{
    int failed = 0;

    for (size_t i = 0; i < NUM_TEST_CASES; i++) {
        if (test_cases[i].func() != 0) {
            failed++;
        }
    }

    printf("Rayleigh Scattering: %d/%d tests passed\n",
           (int)NUM_TEST_CASES - failed, (int)NUM_TEST_CASES);

    return failed;
}
