/* Test suite for Barten 1999 Contrast Sensitivity Functions
 * Reference: Barten (1999), colour-science implementation
 */

#include "alwan.h"
#include "alwan_internal.h"
#include "test_common.h"
#include <stdio.h>
#include <string.h>

/* ================================================================
 * Reference Data from colour-science
 * Generated by gendata/tests/barten1999_csf.py
 * ================================================================ */

/* Luminance values */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar luminances[] = {
#include "reference_values/barten_luminances.csv"
};
ALWAN_DIAG_POP
#define NUM_LUMINANCES (sizeof(luminances) / sizeof(luminances[0]))

/* Angular sizes */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar angular_sizes[] = {
#include "reference_values/barten_angular_sizes.csv"
};
ALWAN_DIAG_POP
#define NUM_ANGULAR_SIZES (sizeof(angular_sizes) / sizeof(angular_sizes[0]))

/* Pupil diameters */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar pupil_diameters[] = {
#include "reference_values/barten_pupil_diameters.csv"
};
ALWAN_DIAG_POP
#define NUM_PUPIL_DIAMETERS (sizeof(pupil_diameters) / sizeof(pupil_diameters[0]))

/* Spatial frequencies */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar frequencies[] = {
#include "reference_values/barten_frequencies.csv"
};
ALWAN_DIAG_POP
#define NUM_FREQUENCIES (sizeof(frequencies) / sizeof(frequencies[0]))

/* Sigma values for MTF tests */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar sigmas[] = {
#include "reference_values/barten_sigmas.csv"
};
ALWAN_DIAG_POP
#define NUM_SIGMAS (sizeof(sigmas) / sizeof(sigmas[0]))

/* CSF frequencies (extended range) */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar csf_frequencies[] = {
#include "reference_values/barten_csf_frequencies.csv"
};
ALWAN_DIAG_POP
#define NUM_CSF_FREQUENCIES (sizeof(csf_frequencies) / sizeof(csf_frequencies[0]))

/* Reference pupil diameter with defaults (L varies, X_0=Y_0=60) */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_pupil_default[] = {
#include "reference_values/barten_pupil_diameter_default.csv"
};
ALWAN_DIAG_POP

/* Reference pupil diameter with varying angular size (L=100) */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_pupil_angular[] = {
#include "reference_values/barten_pupil_diameter_angular.csv"
};
ALWAN_DIAG_POP

/* Reference retinal illuminance with Stiles-Crawford */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_retinal_sc[] = {
#include "reference_values/barten_retinal_illuminance_sc.csv"
};
ALWAN_DIAG_POP

/* Reference retinal illuminance without Stiles-Crawford */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_retinal_no_sc[] = {
#include "reference_values/barten_retinal_illuminance_no_sc.csv"
};
ALWAN_DIAG_POP

/* Reference retinal illuminance at fixed L=100 */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_retinal_fixed_L[] = {
#include "reference_values/barten_retinal_illuminance_fixed_L.csv"
};
ALWAN_DIAG_POP

/* Reference MTF with default sigma=0.01 */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_mtf_default[] = {
#include "reference_values/barten_mtf_default.csv"
};
ALWAN_DIAG_POP

/* Reference MTF at u=4 with varying sigma */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_mtf_u4[] = {
#include "reference_values/barten_mtf_u4.csv"
};
ALWAN_DIAG_POP

/* Reference sigma with defaults */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_sigma_default[] = {
#include "reference_values/barten_sigma_default.csv"
};
ALWAN_DIAG_POP

/* Sigma_0 values */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar sigma_0_values[] = {
#include "reference_values/barten_sigma_0_values.csv"
};
ALWAN_DIAG_POP
#define NUM_SIGMA_0 (sizeof(sigma_0_values) / sizeof(sigma_0_values[0]))

/* Reference sigma with varying sigma_0 */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_sigma_vary_s0[] = {
#include "reference_values/barten_sigma_vary_s0.csv"
};
ALWAN_DIAG_POP

/* Reference max angular size with defaults */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_max_angular_default[] = {
#include "reference_values/barten_max_angular_size_default.csv"
};
ALWAN_DIAG_POP

/* X_0 values for max angular size tests */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar X_0_values[] = {
#include "reference_values/barten_X_0_values.csv"
};
ALWAN_DIAG_POP
#define NUM_X_0 (sizeof(X_0_values) / sizeof(X_0_values[0]))

/* Reference max angular size with varying X_0 */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_max_angular_vary_X0[] = {
#include "reference_values/barten_max_angular_size_vary_X0.csv"
};
ALWAN_DIAG_POP

/* Reference CSF with defaults */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_csf_default[] = {
#include "reference_values/barten_csf_default.csv"
};
ALWAN_DIAG_POP

/* Retinal illuminance values for CSF tests */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar E_values[] = {
#include "reference_values/barten_E_values.csv"
};
ALWAN_DIAG_POP
#define NUM_E_VALUES (sizeof(E_values) / sizeof(E_values[0]))

/* Reference CSF at u=4 with varying E */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_csf_vary_E[] = {
#include "reference_values/barten_csf_vary_E.csv"
};
ALWAN_DIAG_POP

/* Sigma values for CSF tests */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar csf_sigma_values[] = {
#include "reference_values/barten_csf_sigma_values.csv"
};
ALWAN_DIAG_POP
#define NUM_CSF_SIGMAS (sizeof(csf_sigma_values) / sizeof(csf_sigma_values[0]))

/* Reference CSF at u=4 with varying sigma */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_csf_vary_sigma[] = {
#include "reference_values/barten_csf_vary_sigma.csv"
};
ALWAN_DIAG_POP

/* Reference CSF at L=1 */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_csf_L1[] = {
#include "reference_values/barten_csf_L1.csv"
};
ALWAN_DIAG_POP

/* Reference CSF at L=10 */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_csf_L10[] = {
#include "reference_values/barten_csf_L10.csv"
};
ALWAN_DIAG_POP

/* Reference CSF at L=100 */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static const alwan_scalar ref_csf_L100[] = {
#include "reference_values/barten_csf_L100.csv"
};
ALWAN_DIAG_POP

/* ================================================================
 * Test Functions
 * ================================================================ */

static int test_pupil_diameter_default(void)
{
    printf("  TEST: Pupil diameter with default angular size\n");

    for (size_t i = 0; i < NUM_LUMINANCES; i++) {
        alwan_scalar d = alwan_pupil_diameter_barten1999(luminances[i], 60, 60);
        char msg[64];
        sprintf(msg, "Pupil at L=%.2f", luminances[i]);
        TEST_ASSERT_REL(d, ref_pupil_default[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_pupil_diameter_angular(void)
{
    printf("  TEST: Pupil diameter with varying angular size\n");

    for (size_t i = 0; i < NUM_ANGULAR_SIZES; i++) {
        alwan_scalar d = alwan_pupil_diameter_barten1999(100, angular_sizes[i], angular_sizes[i]);
        char msg[64];
        sprintf(msg, "Pupil at X_0=%.0f", angular_sizes[i]);
        TEST_ASSERT_REL(d, ref_pupil_angular[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_retinal_illuminance_sc(void)
{
    printf("  TEST: Retinal illuminance with Stiles-Crawford\n");

    for (size_t i = 0; i < NUM_PUPIL_DIAMETERS; i++) {
        alwan_scalar E = alwan_retinal_illuminance_barten1999(luminances[i], pupil_diameters[i], 1);
        char msg[64];
        sprintf(msg, "Retinal at L=%.2f, d=%.1f (SC)", luminances[i], pupil_diameters[i]);
        TEST_ASSERT_REL(E, ref_retinal_sc[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_retinal_illuminance_no_sc(void)
{
    printf("  TEST: Retinal illuminance without Stiles-Crawford\n");

    for (size_t i = 0; i < NUM_PUPIL_DIAMETERS; i++) {
        alwan_scalar E = alwan_retinal_illuminance_barten1999(luminances[i], pupil_diameters[i], 0);
        char msg[64];
        sprintf(msg, "Retinal at L=%.2f, d=%.1f (no SC)", luminances[i], pupil_diameters[i]);
        TEST_ASSERT_REL(E, ref_retinal_no_sc[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_optical_mtf_default(void)
{
    printf("  TEST: Optical MTF with default sigma\n");

    for (size_t i = 0; i < NUM_FREQUENCIES; i++) {
        alwan_scalar M = alwan_optical_mtf_barten1999(frequencies[i], 0.01);
        char msg[64];
        sprintf(msg, "MTF at u=%.1f", frequencies[i]);
        TEST_ASSERT_REL(M, ref_mtf_default[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_optical_mtf_vary_sigma(void)
{
    printf("  TEST: Optical MTF at u=4 with varying sigma\n");

    for (size_t i = 0; i < NUM_SIGMAS; i++) {
        alwan_scalar M = alwan_optical_mtf_barten1999(4, sigmas[i]);
        char msg[64];
        sprintf(msg, "MTF at sigma=%.4f", sigmas[i]);
        TEST_ASSERT_REL(M, ref_mtf_u4[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

/* Pupil diameters used for sigma tests (different from retinal illuminance tests) */
static const alwan_scalar sigma_pupil_diameters[] = {1.0, 1.5, 2.0, 2.1, 2.5, 3.0, 4.0, 5.0};
#define NUM_SIGMA_PUPIL_DIAMETERS (sizeof(sigma_pupil_diameters) / sizeof(sigma_pupil_diameters[0]))

static int test_sigma_default(void)
{
    printf("  TEST: Sigma with default parameters\n");

    alwan_scalar sigma_0 = 0.5 / 60;
    alwan_scalar C_ab = 0.08 / 60;

    for (size_t i = 0; i < NUM_SIGMA_PUPIL_DIAMETERS; i++) {
        alwan_scalar d = sigma_pupil_diameters[i];
        alwan_scalar s = alwan_sigma_barten1999(sigma_0, C_ab, d);
        char msg[64];
        sprintf(msg, "Sigma at d=%.1f", d);
        TEST_ASSERT_REL(s, ref_sigma_default[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_max_angular_size_default(void)
{
    printf("  TEST: Maximum angular size with defaults\n");

    for (size_t i = 0; i < NUM_FREQUENCIES; i++) {
        alwan_scalar X = alwan_maximum_angular_size_barten1999(frequencies[i], 60, 12, 15);
        char msg[64];
        sprintf(msg, "Max angular at u=%.1f", frequencies[i]);
        TEST_ASSERT_REL(X, ref_max_angular_default[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_max_angular_size_vary_X0(void)
{
    printf("  TEST: Maximum angular size with varying X_0\n");

    for (size_t i = 0; i < NUM_X_0; i++) {
        alwan_scalar X = alwan_maximum_angular_size_barten1999(4, X_0_values[i], 12, 15);
        char msg[64];
        sprintf(msg, "Max angular at X_0=%.0f", X_0_values[i]);
        TEST_ASSERT_REL(X, ref_max_angular_vary_X0[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_csf_default(void)
{
    printf("  TEST: CSF with default parameters\n");

    for (size_t i = 0; i < NUM_CSF_FREQUENCIES; i++) {
        alwan_scalar S = alwan_csf_barten1999(csf_frequencies[i], NULL);
        char msg[64];
        sprintf(msg, "CSF at u=%.1f", csf_frequencies[i]);
        TEST_ASSERT_REL(S, ref_csf_default[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_csf_vary_E(void)
{
    printf("  TEST: CSF at u=4 with varying retinal illuminance\n");

    alwan_csf_barten1999_params params;
    alwan_csf_barten1999_params_default(&params);

    for (size_t i = 0; i < NUM_E_VALUES; i++) {
        params.E = E_values[i];
        alwan_scalar S = alwan_csf_barten1999(4, &params);
        char msg[64];
        sprintf(msg, "CSF at E=%.0f", E_values[i]);
        TEST_ASSERT_REL(S, ref_csf_vary_E[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_csf_vary_sigma(void)
{
    printf("  TEST: CSF at u=4 with varying sigma\n");

    alwan_csf_barten1999_params params;
    alwan_csf_barten1999_params_default(&params);

    for (size_t i = 0; i < NUM_CSF_SIGMAS; i++) {
        params.sigma = csf_sigma_values[i];
        alwan_scalar S = alwan_csf_barten1999(4, &params);
        char msg[64];
        sprintf(msg, "CSF at sigma=%.4f", csf_sigma_values[i]);
        TEST_ASSERT_REL(S, ref_csf_vary_sigma[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_csf_full_workflow(void)
{
    printf("  TEST: CSF full workflow (L -> d -> sigma, E -> CSF)\n");

    /* Test at L=100 */
    alwan_scalar L = 100;
    alwan_scalar d = alwan_pupil_diameter_barten1999(L, 60, 60);
    alwan_scalar sigma = alwan_sigma_barten1999(0.5/60, 0.08/60, d);
    alwan_scalar E = alwan_retinal_illuminance_barten1999(L, d, 1);

    alwan_csf_barten1999_params params;
    alwan_csf_barten1999_params_default(&params);
    params.sigma = sigma;
    params.E = E;

    for (size_t i = 0; i < NUM_CSF_FREQUENCIES; i++) {
        alwan_scalar S = alwan_csf_barten1999(csf_frequencies[i], &params);
        char msg[64];
        sprintf(msg, "CSF L=100 at u=%.1f", csf_frequencies[i]);
        TEST_ASSERT_REL(S, ref_csf_L100[i], TEST_TOLERANCE, msg);
    }

    return 0;
}

static int test_params_default(void)
{
    printf("  TEST: CSF params default initialization\n");

    alwan_csf_barten1999_params params;
    alwan_csf_barten1999_params_default(&params);

    /* Check known defaults from colour-science */
    TEST_ASSERT_REL(params.k, ALWAN_LITERAL(3.0), ALWAN_LITERAL(1e-10), "Default k should be 3.0");
    TEST_ASSERT_REL(params.T, ALWAN_LITERAL(0.1), ALWAN_LITERAL(1e-10), "Default T should be 0.1");
    TEST_ASSERT_REL(params.X_0, ALWAN_LITERAL(60.0), ALWAN_LITERAL(1e-10), "Default X_0 should be 60");
    TEST_ASSERT_REL(params.X_max, ALWAN_LITERAL(12.0), ALWAN_LITERAL(1e-10), "Default X_max should be 12");
    TEST_ASSERT_REL(params.N_max, ALWAN_LITERAL(15.0), ALWAN_LITERAL(1e-10), "Default N_max should be 15");
    TEST_ASSERT_REL(params.n, ALWAN_LITERAL(0.03), ALWAN_LITERAL(1e-10), "Default n should be 0.03");
    TEST_ASSERT_REL(params.p, ALWAN_LITERAL(1.2274e6), ALWAN_LITERAL(1e-10), "Default p should be 1.2274e6");
    TEST_ASSERT_REL(params.phi_0, ALWAN_LITERAL(3.0e-8), ALWAN_LITERAL(1e-10), "Default phi_0 should be 3e-8");
    TEST_ASSERT_REL(params.u_0, ALWAN_LITERAL(7.0), ALWAN_LITERAL(1e-10), "Default u_0 should be 7");

    /* Sigma should be computed from sigma_0=0.5/60, C_ab=0.08/60, d=2.1 */
    alwan_scalar expected_sigma = alwan_sigma_barten1999(0.5/60, 0.08/60, 2.1);
    TEST_ASSERT_REL(params.sigma, expected_sigma, TEST_TOLERANCE, "Default sigma");

    /* E should be computed from L=20, d=2.1, SC=true */
    alwan_scalar expected_E = alwan_retinal_illuminance_barten1999(20, 2.1, 1);
    TEST_ASSERT_REL(params.E, expected_E, TEST_TOLERANCE, "Default E");

    return 0;
}

/* ================================================================
 * Test Suite
 * ================================================================ */

typedef int (*test_func)(void);

typedef struct {
    const char *name;
    test_func func;
} test_case;

static test_case test_cases[] = {
    {"Pupil diameter default", test_pupil_diameter_default},
    {"Pupil diameter angular", test_pupil_diameter_angular},
    {"Retinal illuminance SC", test_retinal_illuminance_sc},
    {"Retinal illuminance no SC", test_retinal_illuminance_no_sc},
    {"Optical MTF default", test_optical_mtf_default},
    {"Optical MTF vary sigma", test_optical_mtf_vary_sigma},
    {"Sigma default", test_sigma_default},
    {"Max angular size default", test_max_angular_size_default},
    {"Max angular size vary X_0", test_max_angular_size_vary_X0},
    {"CSF default", test_csf_default},
    {"CSF vary E", test_csf_vary_E},
    {"CSF vary sigma", test_csf_vary_sigma},
    {"CSF full workflow", test_csf_full_workflow},
    {"CSF params default", test_params_default},
};

#define NUM_TEST_CASES (sizeof(test_cases) / sizeof(test_cases[0]))

int test_50_barten1999_csf_main(void)
{
    int failed = 0;

    for (size_t i = 0; i < NUM_TEST_CASES; i++) {
        if (test_cases[i].func() != 0) {
            failed++;
        }
    }

    printf("Barten 1999 CSF: %d/%d tests passed\n",
           (int)NUM_TEST_CASES - failed, (int)NUM_TEST_CASES);

    return failed;
}
