/*
 * Alwan - Pure C colour science library
 * Test 82: Machado 2009 CVD Simulation
 *
 * Validates Machado 2009 colour vision deficiency simulation against
 * reference values generated by colour-science.
 */

#include "test_common.h"
#include <string.h>

/* ================================================================
 * Reference data: 90 test cases (6 colors x 3 types x 5 severities)
 * Format per case: R_in, G_in, B_in, type(0/1/2), severity, R_out, G_out, B_out
 * ================================================================ */

ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_f64 const g_machado_ref[] = {
#include "reference_values/test_machado2009_cvd.csv"
};
ALWAN_DIAG_POP

#define MACHADO_REF_STRIDE 8
#define MACHADO_REF_COUNT  90

/* ================================================================
 * Test: Reference comparison against colour-science
 * ================================================================ */

static int test_machado_reference(void) {
    TEST_START("test_machado_reference");

    static alwan_cvd_type const type_map[] = {
        ALWAN_CVD_PROTANOPIA,
        ALWAN_CVD_DEUTERANOPIA,
        ALWAN_CVD_TRITANOPIA,
    };

    int failures = 0;

    for (int i = 0; i < MACHADO_REF_COUNT; i++) {
        alwan_f64 const *d = &g_machado_ref[i * MACHADO_REF_STRIDE];

        alwan_rgb rgb_in = {d[0], d[1], d[2]};
        int type_idx = (int)d[3];
        alwan_f64 severity = d[4];
        alwan_f64 exp_r = d[5], exp_g = d[6], exp_b = d[7];

        alwan_rgb rgb_out;
        int status = alwan_simulate_cvd_machado(&rgb_out, &rgb_in,
                                                 type_map[type_idx], severity);
        if (status != ALWAN_OK) {
            printf("[FAIL] case %d: returned %d\n", i, status);
            failures++;
            continue;
        }

        alwan_f64 dr = ALWAN_ABS(rgb_out.r - exp_r);
        alwan_f64 dg = ALWAN_ABS(rgb_out.g - exp_g);
        alwan_f64 db = ALWAN_ABS(rgb_out.b - exp_b);
        alwan_f64 max_diff = dr;
        if (dg > max_diff) max_diff = dg;
        if (db > max_diff) max_diff = db;

        if (max_diff > ALWAN_TEST_TOLERANCE) {
            printf("[FAIL] case %d (type=%d sev=%.1f): max_diff=%.16e\n",
                   i, type_idx, (double)severity, (double)max_diff);
            printf("  In:  [%.6f, %.6f, %.6f]\n",
                   (double)d[0], (double)d[1], (double)d[2]);
            printf("  Exp: [%.10e, %.10e, %.10e]\n",
                   (double)exp_r, (double)exp_g, (double)exp_b);
            printf("  Got: [%.10e, %.10e, %.10e]\n",
                   (double)rgb_out.r, (double)rgb_out.g, (double)rgb_out.b);
            failures++;
        }
    }

    if (failures > 0) {
        TEST_FAIL("%d / %d reference cases failed", failures, MACHADO_REF_COUNT);
    }

    TEST_PASS("test_machado_reference");
}

/* ================================================================
 * Test: Severity 0.0 should be identity
 * ================================================================ */

static int test_machado_identity(void) {
    TEST_START("test_machado_identity");

    alwan_rgb colors[] = {
        {1.0, 0.0, 0.0},
        {0.0, 1.0, 0.0},
        {0.0, 0.0, 1.0},
        {0.5, 0.5, 0.5},
        {0.8, 0.3, 0.1},
    };

    alwan_cvd_type types[] = {
        ALWAN_CVD_PROTANOPIA,
        ALWAN_CVD_DEUTERANOPIA,
        ALWAN_CVD_TRITANOPIA,
    };

    for (int t = 0; t < 3; t++) {
        for (int c = 0; c < 5; c++) {
            alwan_rgb out;
            int status = alwan_simulate_cvd_machado(&out, &colors[c],
                                                     types[t],
                                                     ALWAN_LITERAL(0.0));
            TEST_ASSERT(status == ALWAN_OK, "severity=0 returned error");
            TEST_CHECK_NEAR(out.r, colors[c].r, ALWAN_TEST_TOLERANCE);
            TEST_CHECK_NEAR(out.g, colors[c].g, ALWAN_TEST_TOLERANCE);
            TEST_CHECK_NEAR(out.b, colors[c].b, ALWAN_TEST_TOLERANCE);
        }
    }

    TEST_PASS("test_machado_identity");
}

/* ================================================================
 * Test: alwan_simulate_cvd_ex dispatches correctly
 * ================================================================ */

static int test_cvd_ex_dispatch(void) {
    TEST_START("test_cvd_ex_dispatch");

    alwan_rgb rgb_in = {0.8, 0.3, 0.1};
    alwan_rgb out_brettel, out_machado, out_ex_brettel, out_ex_machado;

    /* Get direct results */
    alwan_simulate_cvd(&out_brettel, &rgb_in, ALWAN_CVD_PROTANOPIA, ALWAN_LITERAL(0.7));
    alwan_simulate_cvd_machado(&out_machado, &rgb_in, ALWAN_CVD_PROTANOPIA, ALWAN_LITERAL(0.7));

    /* Get ex results */
    alwan_simulate_cvd_ex(&out_ex_brettel, &rgb_in, ALWAN_CVD_PROTANOPIA,
                           ALWAN_LITERAL(0.7), ALWAN_CVD_MODEL_BRETTEL);
    alwan_simulate_cvd_ex(&out_ex_machado, &rgb_in, ALWAN_CVD_PROTANOPIA,
                           ALWAN_LITERAL(0.7), ALWAN_CVD_MODEL_MACHADO);

    /* _ex with BRETTEL should match direct Brettel */
    TEST_CHECK_NEAR(out_ex_brettel.r, out_brettel.r, ALWAN_TEST_TOLERANCE);
    TEST_CHECK_NEAR(out_ex_brettel.g, out_brettel.g, ALWAN_TEST_TOLERANCE);
    TEST_CHECK_NEAR(out_ex_brettel.b, out_brettel.b, ALWAN_TEST_TOLERANCE);

    /* _ex with MACHADO should match direct Machado */
    TEST_CHECK_NEAR(out_ex_machado.r, out_machado.r, ALWAN_TEST_TOLERANCE);
    TEST_CHECK_NEAR(out_ex_machado.g, out_machado.g, ALWAN_TEST_TOLERANCE);
    TEST_CHECK_NEAR(out_ex_machado.b, out_machado.b, ALWAN_TEST_TOLERANCE);

    /* Brettel and Machado should give different results (different models) */
    alwan_f64 dr = ALWAN_ABS(out_brettel.r - out_machado.r);
    alwan_f64 dg = ALWAN_ABS(out_brettel.g - out_machado.g);
    alwan_f64 db = ALWAN_ABS(out_brettel.b - out_machado.b);
    alwan_f64 max_diff = dr;
    if (dg > max_diff) max_diff = dg;
    if (db > max_diff) max_diff = db;
    TEST_ASSERT(max_diff > ALWAN_LITERAL(0.001),
                "Brettel and Machado should produce different results");

    TEST_PASS("test_cvd_ex_dispatch");
}

/* ================================================================
 * Test: Batch map matches single-pixel results
 * ================================================================ */

static int test_machado_batch(void) {
    TEST_START("test_machado_batch");

    alwan_f64 rgb_in[] = {
        0.8, 0.3, 0.1,
        0.2, 0.6, 0.8,
        1.0, 0.0, 0.0,
        0.5, 0.5, 0.5,
    };
    size_t count = 4;
    alwan_f64 rgb_out[12];
    size_t stride = 3 * sizeof(alwan_f64);

    int status = alwan_simulate_cvd_machado_map_interleave(
        rgb_out, rgb_in, ALWAN_CVD_DEUTERANOPIA, ALWAN_LITERAL(0.7),
        count, stride, stride);
    TEST_ASSERT(status == ALWAN_OK, "batch returned error");

    /* Compare against single-pixel API */
    for (size_t i = 0; i < count; i++) {
        alwan_rgb in_px = {rgb_in[i*3], rgb_in[i*3+1], rgb_in[i*3+2]};
        alwan_rgb out_px;
        alwan_simulate_cvd_machado(&out_px, &in_px, ALWAN_CVD_DEUTERANOPIA,
                                    ALWAN_LITERAL(0.7));
        TEST_CHECK_NEAR(rgb_out[i*3+0], out_px.r, ALWAN_TEST_TOLERANCE);
        TEST_CHECK_NEAR(rgb_out[i*3+1], out_px.g, ALWAN_TEST_TOLERANCE);
        TEST_CHECK_NEAR(rgb_out[i*3+2], out_px.b, ALWAN_TEST_TOLERANCE);
    }

    TEST_PASS("test_machado_batch");
}

/* ================================================================
 * Test: Severity monotonicity (further from original as severity grows)
 * ================================================================ */

static int test_machado_monotonicity(void) {
    TEST_START("test_machado_monotonicity");

    alwan_rgb rgb_in = {0.8, 0.2, 0.1};

    /* Only test protan and deutan; tritan uses an approximate shift model
     * (domain [5,59] vs [0,20]) and is not strictly monotonic. */
    alwan_cvd_type types[] = {
        ALWAN_CVD_PROTANOPIA,
        ALWAN_CVD_DEUTERANOPIA,
    };

    for (int t = 0; t < 2; t++) {
        alwan_f64 prev_dist = ALWAN_LITERAL(0.0);

        for (int s = 1; s <= 10; s++) {
            alwan_f64 severity = (alwan_f64)s / ALWAN_LITERAL(10.0);
            alwan_rgb out;
            alwan_simulate_cvd_machado(&out, &rgb_in, types[t], severity);

            /* Euclidean distance from original */
            alwan_f64 dr = out.r - rgb_in.r;
            alwan_f64 dg = out.g - rgb_in.g;
            alwan_f64 db = out.b - rgb_in.b;
            alwan_f64 dist = ALWAN_SQRT(dr*dr + dg*dg + db*db);

            /* Should be non-decreasing (allow small tolerance for interpolation) */
            if (dist < prev_dist - ALWAN_LITERAL(1e-4)) {
                printf("[FAIL] type=%d: distance decreased at severity=%.1f "
                       "(%.6e < %.6e)\n", t, (double)severity,
                       (double)dist, (double)prev_dist);
                TEST_FAIL_INCR();
                return 1;
            }
            prev_dist = dist;
        }
    }

    TEST_PASS("test_machado_monotonicity");
}

/* ================================================================
 * Test: Gray preservation (achromatic colors stay achromatic)
 * ================================================================ */

static int test_machado_gray(void) {
    TEST_START("test_machado_gray");

    /* For protan and deutan, gray should remain nearly gray at all severities.
     * Tritan may shift gray slightly due to the model approximation. */
    alwan_rgb gray = {0.5, 0.5, 0.5};
    alwan_cvd_type types[] = {ALWAN_CVD_PROTANOPIA, ALWAN_CVD_DEUTERANOPIA};

    for (int t = 0; t < 2; t++) {
        for (int s = 0; s <= 10; s++) {
            alwan_f64 severity = (alwan_f64)s / ALWAN_LITERAL(10.0);
            alwan_rgb out;
            alwan_simulate_cvd_machado(&out, &gray, types[t], severity);

            /* R, G, B should be similar (achromatic) */
            alwan_f64 max_ch = out.r;
            if (out.g > max_ch) max_ch = out.g;
            if (out.b > max_ch) max_ch = out.b;
            alwan_f64 min_ch = out.r;
            if (out.g < min_ch) min_ch = out.g;
            if (out.b < min_ch) min_ch = out.b;
            alwan_f64 spread = max_ch - min_ch;

            if (spread > ALWAN_LITERAL(0.05)) {
                printf("[FAIL] type=%d severity=%.1f: gray -> [%.6f,%.6f,%.6f] "
                       "(spread=%.6f)\n", t, (double)severity,
                       (double)out.r, (double)out.g, (double)out.b,
                       (double)spread);
                TEST_FAIL_INCR();
                return 1;
            }
        }
    }

    TEST_PASS("test_machado_gray");
}

/* ================================================================
 * Test: NULL pointer checks
 * ================================================================ */

static int test_machado_null(void) {
    TEST_START("test_machado_null");

    alwan_rgb rgb = {0.5, 0.5, 0.5};
    alwan_rgb out;

    TEST_ASSERT(alwan_simulate_cvd_machado(NULL, &rgb, ALWAN_CVD_PROTANOPIA,
                ALWAN_LITERAL(0.5)) == ALWAN_E_INVALID, "NULL out");
    TEST_ASSERT(alwan_simulate_cvd_machado(&out, NULL, ALWAN_CVD_PROTANOPIA,
                ALWAN_LITERAL(0.5)) == ALWAN_E_INVALID, "NULL in");
    TEST_ASSERT(alwan_simulate_cvd_ex(NULL, &rgb, ALWAN_CVD_PROTANOPIA,
                ALWAN_LITERAL(0.5), ALWAN_CVD_MODEL_MACHADO) == ALWAN_E_INVALID,
                "NULL out (ex)");
    TEST_ASSERT(alwan_simulate_cvd_machado_map_interleave(NULL, (alwan_f64*)&rgb,
                ALWAN_CVD_PROTANOPIA, ALWAN_LITERAL(0.5), 1,
                3*sizeof(alwan_f64), 3*sizeof(alwan_f64)) == ALWAN_E_INVALID,
                "NULL batch out");

    TEST_PASS("test_machado_null");
}

/* ================================================================
 * Test: Output clamping to [0, 1]
 * ================================================================ */

static int test_machado_clamping(void) {
    TEST_START("test_machado_clamping");

    /* Saturated colors at high severity can push channels negative or > 1.
     * The implementation should clamp output to [0, 1]. */
    alwan_rgb saturated[] = {
        {1.0, 0.0, 0.0},
        {0.0, 1.0, 0.0},
        {0.0, 0.0, 1.0},
    };

    for (int c = 0; c < 3; c++) {
        for (int t = 0; t < 3; t++) {
            alwan_cvd_type types[] = {
                ALWAN_CVD_PROTANOPIA, ALWAN_CVD_DEUTERANOPIA, ALWAN_CVD_TRITANOPIA
            };
            alwan_rgb out;
            alwan_simulate_cvd_machado(&out, &saturated[c], types[t],
                                        ALWAN_LITERAL(1.0));
            TEST_ASSERT(out.r >= ALWAN_LITERAL(0.0) && out.r <= ALWAN_LITERAL(1.0),
                        "R out of [0,1]");
            TEST_ASSERT(out.g >= ALWAN_LITERAL(0.0) && out.g <= ALWAN_LITERAL(1.0),
                        "G out of [0,1]");
            TEST_ASSERT(out.b >= ALWAN_LITERAL(0.0) && out.b <= ALWAN_LITERAL(1.0),
                        "B out of [0,1]");
        }
    }

    TEST_PASS("test_machado_clamping");
}

/* ================================================================
 * Main
 * ================================================================ */

int test_82_machado_cvd_main(void) {
    int fail = 0;

    fail += test_machado_reference();
    fail += test_machado_identity();
    fail += test_cvd_ex_dispatch();
    fail += test_machado_batch();
    fail += test_machado_monotonicity();
    fail += test_machado_gray();
    fail += test_machado_null();
    fail += test_machado_clamping();

    return fail;
}
