/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Soufiane KHIAT
 * SPDX-License-Identifier: MIT
 *
 * View Transforms (Display Rendering)
 * Per-pixel math in alwan_view_core.h / alwan_hdr_core.h.
 *
 * The view transforms are instantiated natively for both f32 and f64
 * from alwan_view_impl.inc (included once per precision below), so the
 * single-precision path computes in float throughout rather than
 * widening to double. Only the shared constant data, enum dispatch and
 * bulk loop live here.
 */

#include "../alwan.h"
#include "../alwan_internal.h"
#include "../core/alwan_view_core.h"
#include "../core/alwan_hdr_core.h"
#include <string.h>

/* ----------------------------------------------------------------
 * Shared constant data -- defined once at f64 precision and read at the
 * active precision from the templated impl (with per-element casts).
 * ---------------------------------------------------------------- */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV

/* AP1 -> AP0 (alwan_aces1_output_transform expects AP0). */
#if ALWAN_WITH_F32
static alwan_f32 const ap1_to_ap0_f32[9] = {
#include "../data/matrices/aces_ap1_to_ap0.csv"
};
#endif
#if ALWAN_WITH_F64
static alwan_f64 const ap1_to_ap0_f64[9] = {
#include "../data/matrices/aces_ap1_to_ap0.csv"
};
#endif

/* AgX inset matrix: BT.709 -> AgX log-encoding space, plus outset. */
#if ALWAN_WITH_F32
static alwan_f32 const agx_inset_matrix_f32[9] = {
#include "../data/matrices/agx_inset.csv"
};
#endif
#if ALWAN_WITH_F64
static alwan_f64 const agx_inset_matrix_f64[9] = {
#include "../data/matrices/agx_inset.csv"
};
#endif
/* SB2383 AgX experiment: its own inset (BT.709 -> SB2383 working space) and
 * log2 range. A distinct picture-formation experiment, not a tweak of the
 * original -- generated by alwan_dev/gendata/data/agx_sb2383.py. */
#if ALWAN_WITH_F32
static alwan_f32 const agx_sb2383_inset_matrix_f32[9] = {
#include "../data/matrices/agx_sb2383_inset.csv"
};
#endif
#if ALWAN_WITH_F64
static alwan_f64 const agx_sb2383_inset_matrix_f64[9] = {
#include "../data/matrices/agx_sb2383_inset.csv"
};
#endif

/* AgX Default Contrast LUT -- from sobotka/AgX config.ocio.
 * Defines agx_default_contrast_lut[] and AGX_LUT_SIZE. */
#include "../data/agx_default_contrast_lut.h"

/* SB2383 contrast LUT (uses AGX_LUT_SIZE from the header above). */
#include "../data/agx_sb2383_contrast_lut.h"

/* Blender AgX (EaryChow): Rec.709 -> FilmLight E-Gamut matrix. The 57^3 3D LUT
 * itself is in agx_blender_lut3d.h (f32). Generated by gendata/agx_blender.py. */
#if ALWAN_WITH_F32
static alwan_f32 const agx_blender_rec709_to_egamut_f32[9] = {
#include "../data/matrices/agx_blender_rec709_to_egamut.csv"
};
#endif
#if ALWAN_WITH_F64
static alwan_f64 const agx_blender_rec709_to_egamut_f64[9] = {
#include "../data/matrices/agx_blender_rec709_to_egamut.csv"
};
#endif

ALWAN_DIAG_POP

/* Blender 57^3 3D LUT -- native dual precision (agx_blender_lut3d_f32/f64). */
#include "../data/agx_blender_lut3d.h"

/* ----------------------------------------------------------------
 * Native dual-precision instantiation.
 * ---------------------------------------------------------------- */
#if ALWAN_WITH_F32
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
#include "alwan_api_f32_setup.h"
#include "alwan_view_impl.inc"
#include "alwan_api_teardown.h"
ALWAN_DIAG_POP
#endif

#if ALWAN_WITH_F64
#include "alwan_api_f64_setup.h"
#include "alwan_view_impl.inc"
#include "alwan_api_teardown.h"
#endif
