/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Soufiane KHIAT
 * SPDX-License-Identifier: MIT
 *
 * Reference Data & Color Systems
 * Munsell, Color Checker, NCS, and RGB Space Definitions
 */

#include "../alwan.h"
#include "../alwan_internal.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ----------------------------------------------------------------
 * Munsell Renotation Data
 * ---------------------------------------------------------------- */

/* Munsell renotation data -- full dataset from the 1943 Munsell Renotation.
 * Format: flat interleaved H, V, C, x, y, Y (under Illuminant C)
 * 6 values per entry. Generated by gendata/munsell_renotation.py
 * using colour-science MUNSELL_COLOURS_ALL. */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_f64 const g_munsell_renotation_flat[] = {
#include "../data/munsell_renotation.csv"
};
ALWAN_DIAG_POP

#define MUNSELL_FIELDS_PER_ENTRY 6
static size_t const g_munsell_renotation_count =
    sizeof(g_munsell_renotation_flat) / (MUNSELL_FIELDS_PER_ENTRY * sizeof(alwan_f64));

/* Access helpers for flat Munsell data */
#define MUNSELL_HUE(i)    g_munsell_renotation_flat[(i) * MUNSELL_FIELDS_PER_ENTRY + 0]
#define MUNSELL_VALUE(i)  g_munsell_renotation_flat[(i) * MUNSELL_FIELDS_PER_ENTRY + 1]
#define MUNSELL_CHROMA(i) g_munsell_renotation_flat[(i) * MUNSELL_FIELDS_PER_ENTRY + 2]
#define MUNSELL_X(i)      g_munsell_renotation_flat[(i) * MUNSELL_FIELDS_PER_ENTRY + 3]
#define MUNSELL_Y(i)      g_munsell_renotation_flat[(i) * MUNSELL_FIELDS_PER_ENTRY + 4]
#define MUNSELL_YLUM(i)   g_munsell_renotation_flat[(i) * MUNSELL_FIELDS_PER_ENTRY + 5]

/* Convert Munsell HVC to XYZ tristimulus values
 * Uses trilinear interpolation in the Munsell renotation data */
int alwan_munsell_to_xyz_f64(alwan_xyz_f64 *xyz, alwan_f64 hue, alwan_f64 value, alwan_f64 chroma,
                         alwan_illuminant illuminant) {
    if (!xyz) {
        return ALWAN_E_INVALID;
    }

    /* Validate input ranges */
    if (value < ALWAN_LITERAL(0.0) || value > ALWAN_LITERAL(10.0)) {
        return ALWAN_E_RANGE;
    }
    if (chroma < ALWAN_LITERAL(0.0)) {
        return ALWAN_E_RANGE;
    }

    /* Normalize hue to [0, 100] */
    while (hue < ALWAN_LITERAL(0.0)) {
        hue += ALWAN_LITERAL(100.0);
    }
    while (hue >= ALWAN_LITERAL(100.0)) {
        hue -= ALWAN_LITERAL(100.0);
    }

    /* For achromatic colors (chroma ~0), use neutral axis */
    if (chroma < ALWAN_LITERAL(0.01)) {
        /* Find neutral entries (chroma = 0) and interpolate by value */
        size_t idx_low = 0;
        size_t idx_high = 0;

        for (size_t i = 0; i < g_munsell_renotation_count; i++) {
            if (MUNSELL_CHROMA(i) < ALWAN_LITERAL(0.01)) {
                if (MUNSELL_VALUE(i) <= value) {
                    idx_low = i;
                }
                if (MUNSELL_VALUE(i) >= value && idx_high == 0) {
                    idx_high = i;
                }
            }
        }

        /* Linear interpolation by value */
        alwan_f64 t = ALWAN_LITERAL(0.0);
        if (MUNSELL_VALUE(idx_high) > MUNSELL_VALUE(idx_low)) {
            t = (value - MUNSELL_VALUE(idx_low)) / (MUNSELL_VALUE(idx_high) - MUNSELL_VALUE(idx_low));
        }

        alwan_f64 x_interp = MUNSELL_X(idx_low) + t * (MUNSELL_X(idx_high) - MUNSELL_X(idx_low));
        alwan_f64 y_interp = MUNSELL_Y(idx_low) + t * (MUNSELL_Y(idx_high) - MUNSELL_Y(idx_low));
        alwan_f64 Y_interp = MUNSELL_YLUM(idx_low) + t * (MUNSELL_YLUM(idx_high) - MUNSELL_YLUM(idx_low));

        /* Convert xyY to XYZ */
        if (y_interp <= ALWAN_LITERAL(0.0)) {
            return ALWAN_E_INVALID;
        }

        xyz->x = x_interp * Y_interp / y_interp;
        xyz->y = Y_interp;
        xyz->z = (ALWAN_LITERAL(1.0) - x_interp - y_interp) * Y_interp / y_interp;
    } else {
        /* Chromatic colors: find nearest entries and interpolate.
         * With full dataset (~4000 entries), find bracketing entries
         * in hue, value, and chroma for trilinear interpolation.
         * TODO: proper trilinear interpolation once full gendata CSV is run */
        size_t best = 0;
        alwan_f64 best_dist = ALWAN_LITERAL(1e10);
        for (size_t i = 0; i < g_munsell_renotation_count; i++) {
            alwan_f64 dh = MUNSELL_HUE(i) - hue;
            alwan_f64 dv = MUNSELL_VALUE(i) - value;
            alwan_f64 dc = MUNSELL_CHROMA(i) - chroma;
            alwan_f64 dist = dh * dh + dv * dv * ALWAN_LITERAL(100.0) + dc * dc;
            if (dist < best_dist) {
                best_dist = dist;
                best = i;
            }
        }
        alwan_f64 x_near = MUNSELL_X(best);
        alwan_f64 y_near = MUNSELL_Y(best);
        alwan_f64 Y_near = MUNSELL_YLUM(best);

        if (y_near <= ALWAN_LITERAL(0.0)) {
            return ALWAN_E_INVALID;
        }

        xyz->x = x_near * Y_near / y_near;
        xyz->y = Y_near;
        xyz->z = (ALWAN_LITERAL(1.0) - x_near - y_near) * Y_near / y_near;
    }

    /* Adapt from Illuminant C to requested illuminant */
    if (illuminant != ALWAN_ILLUMINANT_C) {
        /* Get white points for both illuminants */
        alwan_xyz_f64 white_c, white_dst;
        int status = alwan_illuminant_white_point_f64(&white_c, ALWAN_ILLUMINANT_C,
                                                    ALWAN_OBSERVER_CIE_1931_2DEG);
        if (status != ALWAN_OK) {
            return status;
        }

        status = alwan_illuminant_white_point_f64(&white_dst, illuminant,
                                               ALWAN_OBSERVER_CIE_1931_2DEG);
        if (status != ALWAN_OK) {
            return status;
        }

        /* Compute CAT matrix */
        alwan_mat3x3_f64 cat_matrix;
        status = alwan_cat_matrix_f64(&cat_matrix, &white_c, &white_dst, ALWAN_CAT_BRADFORD);
        if (status != ALWAN_OK) {
            return status;
        }

        /* Apply adaptation */
        alwan_xyz_f64 xyz_adapted;
        alwan_vec3_f64 vec_in, vec_out;
        ALWAN_MEMCPY(&vec_in, xyz, sizeof(alwan_vec3_f64));
        alwan_mat3_mulv_f64(&vec_out, &cat_matrix, &vec_in);
        ALWAN_MEMCPY(&xyz_adapted, &vec_out, sizeof(alwan_vec3_f64));
        *xyz = xyz_adapted;
    }

    return ALWAN_OK;
}

/* Convert XYZ tristimulus values to Munsell HVC notation
 * Uses iterative search in the Munsell renotation data */
int alwan_xyz_to_munsell_f64(alwan_f64 *hue, alwan_f64 *value, alwan_f64 *chroma,
                         alwan_xyz_f64 const *xyz, alwan_illuminant illuminant) {
    if (!xyz || !hue || !value || !chroma) {
        return ALWAN_E_INVALID;
    }

    /* Adapt to Illuminant C (Munsell renotation data is under Illuminant C) */
    alwan_xyz_f64 xyz_c;
    if (illuminant != ALWAN_ILLUMINANT_C) {
        /* Get white points for both illuminants */
        alwan_xyz_f64 white_src, white_c;
        int status = alwan_illuminant_white_point_f64(&white_src, illuminant,
                                                    ALWAN_OBSERVER_CIE_1931_2DEG);
        if (status != ALWAN_OK) {
            return status;
        }

        status = alwan_illuminant_white_point_f64(&white_c, ALWAN_ILLUMINANT_C,
                                               ALWAN_OBSERVER_CIE_1931_2DEG);
        if (status != ALWAN_OK) {
            return status;
        }

        /* Compute CAT matrix */
        alwan_mat3x3_f64 cat_matrix;
        status = alwan_cat_matrix_f64(&cat_matrix, &white_src, &white_c, ALWAN_CAT_BRADFORD);
        if (status != ALWAN_OK) {
            return status;
        }

        /* Apply adaptation */
        alwan_vec3_f64 vec_in, vec_out;
        ALWAN_MEMCPY(&vec_in, xyz, sizeof(alwan_vec3_f64));
        alwan_mat3_mulv_f64(&vec_out, &cat_matrix, &vec_in);
        ALWAN_MEMCPY(&xyz_c, &vec_out, sizeof(alwan_vec3_f64));
    } else {
        xyz_c = *xyz;
    }

    /* Convert XYZ to xyY */
    alwan_f64 sum = xyz_c.x + xyz_c.y + xyz_c.z;
    if (sum <= ALWAN_LITERAL(0.0)) {
        return ALWAN_E_INVALID;
    }

    alwan_f64 x = xyz_c.x / sum;
    alwan_f64 y = xyz_c.y / sum;
    alwan_f64 Y = xyz_c.y;

    /* Find nearest entry in Munsell renotation data using nearest-neighbor search
     * More sophisticated inverse interpolation could be added in future versions */

    alwan_f64 min_dist = ALWAN_LITERAL(1e10);
    size_t best_idx = 0;

    for (size_t i = 0; i < g_munsell_renotation_count; i++) {
        alwan_f64 dx = x - MUNSELL_X(i);
        alwan_f64 dy = y - MUNSELL_Y(i);
        alwan_f64 dY = Y - MUNSELL_YLUM(i);

        alwan_f64 dist = dx * dx + dy * dy + dY * dY * ALWAN_LITERAL(0.01);

        if (dist < min_dist) {
            min_dist = dist;
            best_idx = i;
        }
    }

    *hue = MUNSELL_HUE(best_idx);
    *value = MUNSELL_VALUE(best_idx);
    *chroma = MUNSELL_CHROMA(best_idx);

    return ALWAN_OK;
}

/* ----------------------------------------------------------------
 * Color Checker Data
 * ---------------------------------------------------------------- */

/* ColorChecker Classic 24-patch data (D50, xyY)
 * Generated from colour-science SDS_COLOURCHECKERS['ColorChecker N Ohta']
 * Format: 24 patches x 3 values (x, y, Y) = 72 values total */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_f64 const g_colorchecker_classic_d50_xyY[] = {
#include "../data/colorchecker/classic_d50_xyy.csv"
};
ALWAN_DIAG_POP

/* Get number of patches in a Color Checker target */
size_t alwan_color_checker_num_patches(alwan_colorchecker_type type) {
    switch (type) {
        case ALWAN_COLORCHECKER_CLASSIC:
            return 24;
        case ALWAN_COLORCHECKER_SG:
            return 140;
        case ALWAN_COLORCHECKER_DIGITAL_SG:
            return 140;
        case ALWAN_BABELCOLOR_AVERAGE:
            return 24;
        case ALWAN_BABELCOLOR_HCT:
            return 24;
        default:
            return 0;
    }
}

/* Get XYZ tristimulus values for a Color Checker patch */
int alwan_color_checker_data_f64(alwan_xyz_f64 *xyz, alwan_colorchecker_type type, alwan_illuminant illuminant,
                              size_t patch_index) {
    if (!xyz) {
        return ALWAN_E_INVALID;
    }

    /* Get number of patches for validation */
    size_t num_patches = alwan_color_checker_num_patches(type);
    if (num_patches == 0) {
        return ALWAN_E_INVALID;  /* Unknown type */
    }
    if (patch_index >= num_patches) {
        return ALWAN_E_RANGE;
    }

    /* Currently only ColorChecker Classic is implemented */
    if (type != ALWAN_COLORCHECKER_CLASSIC) {
        return ALWAN_E_INVALID;
    }

    /* Get xyY data under D50 (flat array: patch_index * 3 + offset) */
    size_t const base_idx = patch_index * 3;
    alwan_f64 x = g_colorchecker_classic_d50_xyY[base_idx + 0];
    alwan_f64 y = g_colorchecker_classic_d50_xyY[base_idx + 1];
    alwan_f64 Y = g_colorchecker_classic_d50_xyY[base_idx + 2];

    /* Convert xyY to XYZ */
    if (y <= ALWAN_LITERAL(0.0)) {
        return ALWAN_E_INVALID;
    }

    alwan_xyz_f64 xyz_d50;
    xyz_d50.x = x * Y / y;
    xyz_d50.y = Y;
    xyz_d50.z = (ALWAN_LITERAL(1.0) - x - y) * Y / y;

    /* Adapt from D50 to requested illuminant */
    if (illuminant != ALWAN_ILLUMINANT_D50) {
        /* Get white points for both illuminants */
        alwan_xyz_f64 white_d50, white_dst;
        int status = alwan_illuminant_white_point_f64(&white_d50, ALWAN_ILLUMINANT_D50,
                                                    ALWAN_OBSERVER_CIE_1931_2DEG);
        if (status != ALWAN_OK) {
            return status;
        }

        status = alwan_illuminant_white_point_f64(&white_dst, illuminant,
                                               ALWAN_OBSERVER_CIE_1931_2DEG);
        if (status != ALWAN_OK) {
            return status;
        }

        /* Compute CAT matrix */
        alwan_mat3x3_f64 cat_matrix;
        status = alwan_cat_matrix_f64(&cat_matrix, &white_d50, &white_dst, ALWAN_CAT_BRADFORD);
        if (status != ALWAN_OK) {
            return status;
        }

        /* Apply adaptation */
        alwan_vec3_f64 vec_in, vec_out;
        ALWAN_MEMCPY(&vec_in, &xyz_d50, sizeof(alwan_vec3_f64));
        alwan_mat3_mulv_f64(&vec_out, &cat_matrix, &vec_in);
        ALWAN_MEMCPY(xyz, &vec_out, sizeof(alwan_vec3_f64));
    } else {
        *xyz = xyz_d50;
    }

    return ALWAN_OK;
}

int alwan_color_checker_data_f32(alwan_xyz_f32 *xyz, alwan_colorchecker_type type, alwan_illuminant illuminant,
                              size_t patch_index) {
    if (!xyz) return ALWAN_E_INVALID;
    alwan_xyz_f64 f64_out;
    int rc = alwan_color_checker_data_f64(&f64_out, type, illuminant, patch_index);
    if (rc != ALWAN_OK) return rc;
    xyz->x = (alwan_f32)f64_out.x;
    xyz->y = (alwan_f32)f64_out.y;
    xyz->z = (alwan_f32)f64_out.z;
    return ALWAN_OK;
}

int alwan_munsell_to_xyz_f32(alwan_xyz_f32 *xyz, alwan_f32 hue, alwan_f32 value, alwan_f32 chroma,
                         alwan_illuminant illuminant) {
    if (!xyz) return ALWAN_E_INVALID;
    alwan_xyz_f64 f64_out;
    int rc = alwan_munsell_to_xyz_f64(&f64_out, (alwan_f64)hue, (alwan_f64)value, (alwan_f64)chroma, illuminant);
    if (rc != ALWAN_OK) return rc;
    xyz->x = (alwan_f32)f64_out.x;
    xyz->y = (alwan_f32)f64_out.y;
    xyz->z = (alwan_f32)f64_out.z;
    return ALWAN_OK;
}

int alwan_xyz_to_munsell_f32(alwan_f32 *hue, alwan_f32 *value, alwan_f32 *chroma,
                         alwan_xyz_f32 const *xyz, alwan_illuminant illuminant) {
    if (!xyz || !hue || !value || !chroma) return ALWAN_E_INVALID;
    alwan_xyz_f64 xyz64 = { (alwan_f64)xyz->x, (alwan_f64)xyz->y, (alwan_f64)xyz->z };
    alwan_f64 hue64, value64, chroma64;
    int rc = alwan_xyz_to_munsell_f64(&hue64, &value64, &chroma64, &xyz64, illuminant);
    if (rc != ALWAN_OK) return rc;
    *hue = (alwan_f32)hue64;
    *value = (alwan_f32)value64;
    *chroma = (alwan_f32)chroma64;
    return ALWAN_OK;
}

int alwan_ncs_to_xyz_f32(alwan_xyz_f32 *xyz, char const *ncs_notation) {
    if (!xyz || !ncs_notation) return ALWAN_E_INVALID;
    alwan_xyz_f64 f64_out;
    int rc = alwan_ncs_to_xyz_f64(&f64_out, ncs_notation);
    if (rc != ALWAN_OK) return rc;
    xyz->x = (alwan_f32)f64_out.x;
    xyz->y = (alwan_f32)f64_out.y;
    xyz->z = (alwan_f32)f64_out.z;
    return ALWAN_OK;
}

int alwan_xyz_to_ncs_f32(char *ncs_notation, size_t notation_size, alwan_xyz_f32 const *xyz) {
    if (!xyz) return ALWAN_E_INVALID;
    alwan_xyz_f64 xyz64 = { (alwan_f64)xyz->x, (alwan_f64)xyz->y, (alwan_f64)xyz->z };
    return alwan_xyz_to_ncs_f64(ncs_notation, notation_size, &xyz64);
}

/* ----------------------------------------------------------------
 * NCS (Natural Color System) Data
 * ---------------------------------------------------------------- */

/* NCS color notation structure */
typedef struct {
    alwan_f64 blackness;     /* s: 0.0-99.0 */
    alwan_f64 chromaticness; /* c: 0.0-99.0 */
    alwan_f64 hue_pos;       /* hue position in NCS circle [0, 100) */
    int is_neutral;          /* non-zero for achromatic (chromaticness == 0 or "N") */
} ncs_notation_parsed;

/* Parse NCS notation string (e.g., "S 1050-Y90R")
 * Format: [S|W ]NNCC-HHX[X]  or  [S|W ]NNCC-N
 *   NN = blackness (00-99)
 *   CC = chromaticness (00-99)
 *   HH = hue percentage within hue pair (00-99)
 *   X[X] = one or two adjacent elementary hues from {Y, R, B, G} in circle order
 *           Y(0)->R(25)->B(50)->G(75)->Y, so valid pairs: YR RB BG GY
 * "S 1050-Y90R": s=10, c=50, hue=Y+90%x(R-Y)=22.5 on the NCS circle */
static int parse_ncs_notation(char const *notation, ncs_notation_parsed *parsed) {
    if (!notation || !parsed) return ALWAN_E_INVALID;

    const char *p = notation;

    /* Skip optional "S " or "W " prefix */
    if ((*p == 'S' || *p == 'W') && p[1] == ' ') p += 2;

    /* Blackness NN (2 digits) */
    if (p[0] < '0' || p[0] > '9' || p[1] < '0' || p[1] > '9') return ALWAN_E_INVALID;
    int blackness = (p[0] - '0') * 10 + (p[1] - '0');
    p += 2;

    /* Chromaticness CC (2 digits) */
    if (p[0] < '0' || p[0] > '9' || p[1] < '0' || p[1] > '9') return ALWAN_E_INVALID;
    int chromaticness = (p[0] - '0') * 10 + (p[1] - '0');
    p += 2;

    if (*p != '-') return ALWAN_E_INVALID;
    p++;

    /* Achromatic: notation ends with "N" */
    if (*p == 'N' && (p[1] == '\0')) {
        parsed->blackness     = (alwan_f64)blackness;
        parsed->chromaticness = ALWAN_LITERAL(0.0);
        parsed->hue_pos       = ALWAN_LITERAL(0.0);
        parsed->is_neutral    = 1;
        return ALWAN_OK;
    }

    /* Hue percentage HH (2 digits) */
    if (p[0] < '0' || p[0] > '9' || p[1] < '0' || p[1] > '9') return ALWAN_E_INVALID;
    int hue_pct = (p[0] - '0') * 10 + (p[1] - '0');
    p += 2;

    /* Elementary hue letters and their NCS circle positions */
    static const char   ELEM_CH[4]  = {'Y', 'R', 'B', 'G'};
    static const alwan_f64 ELEM_POS[4] = {0.0, 25.0, 50.0, 75.0};

    /* First letter */
    int idx1 = -1;
    for (int i = 0; i < 4; i++) { if (*p == ELEM_CH[i]) { idx1 = i; break; } }
    if (idx1 < 0) return ALWAN_E_INVALID;
    p++;

    /* Optional second letter -- must be the next elementary in circle order */
    if (*p != '\0') {
        int idx2 = -1;
        for (int i = 0; i < 4; i++) { if (*p == ELEM_CH[i]) { idx2 = i; break; } }
        if (idx2 < 0 || idx2 != (idx1 + 1) % 4) return ALWAN_E_INVALID;
        p++;
        /* GY pair: G(75) -> Y(100), wrapping */
        alwan_f64 pos2 = (idx2 == 0) ? 100.0 : ELEM_POS[idx2];
        alwan_f64 pos = ELEM_POS[idx1] + ((alwan_f64)hue_pct / 100.0) * (pos2 - ELEM_POS[idx1]);
        if (pos >= 100.0) pos -= 100.0;
        parsed->hue_pos = pos;
    } else {
        parsed->hue_pos = ELEM_POS[idx1];
    }

    if (*p != '\0') return ALWAN_E_INVALID; /* trailing garbage */

    parsed->blackness     = (alwan_f64)blackness;
    parsed->chromaticness = (alwan_f64)chromaticness;
    parsed->is_neutral    = (chromaticness == 0);
    return ALWAN_OK;
}

/* Approximate CIE 1931 xy chromaticities for the four NCS elementary hues
 * under D65 illuminant, at maximum chromaticness.
 * Source: Hard & Sivik (1981) Color Res. Appl. 6(3), 129-138, and
 *         Sallstrom (1973) unpublished data cited therein.
 * Order: Y(0), R(25), B(50), G(75) -- matching ELEM_POS above. */
static const alwan_f64 NCS_ELEM_x[4] = {0.418, 0.621, 0.162, 0.199};
static const alwan_f64 NCS_ELEM_y[4] = {0.503, 0.335, 0.083, 0.454};

/* D65 chromaticity */
static const alwan_f64 NCS_WP_x = 0.3127;
static const alwan_f64 NCS_WP_y = 0.3290;

/* Convert NCS notation to approximate XYZ tristimulus values.
 * Uses an approximation based on published elementary hue chromaticities
 * (Hard & Sivik 1981) with linear interpolation along the NCS hue circle
 * and chromaticness-weighted mixing towards the D65 white point.
 * Luminance derived from blackness via Y ~ (1 - s/100)^2.
 * This approximation is suitable for colour-approximate use; it does not
 * reproduce the proprietary NCS colour atlas. */
int alwan_ncs_to_xyz_f64(alwan_xyz_f64 *xyz, char const *ncs_notation) {
    if (!xyz || !ncs_notation) return ALWAN_E_INVALID;

    ncs_notation_parsed parsed;
    int status = parse_ncs_notation(ncs_notation, &parsed);
    if (status != ALWAN_OK) return status;

    alwan_f64 s = parsed.blackness     / 100.0;
    alwan_f64 c = parsed.chromaticness / 100.0;

    /* NCS constraint: s + c <= 1; normalise if violated */
    if (s + c > ALWAN_LITERAL(1.0)) {
        alwan_f64 total = s + c;
        s /= total;
        c /= total;
    }

    /* Approximate CIE Y from NCS blackness: Y ~ (1 - s)^2 x 100 */
    alwan_f64 Y = (ALWAN_LITERAL(1.0) - s) * (ALWAN_LITERAL(1.0) - s) * 100.0;

    alwan_f64 cx, cy;
    if (parsed.is_neutral) {
        cx = NCS_WP_x;
        cy = NCS_WP_y;
    } else {
        /* Interpolate xy between adjacent elementary hues */
        static const alwan_f64 ELEM_POS[4] = {0.0, 25.0, 50.0, 75.0};
        alwan_f64 pos = parsed.hue_pos;
        int seg      = (int)(pos / 25.0) % 4;
        int seg_next = (seg + 1) % 4;
        alwan_f64 seg_end = (seg == 3) ? 100.0 : ELEM_POS[seg_next];
        alwan_f64 t = (pos - ELEM_POS[seg]) / (seg_end - ELEM_POS[seg]);
        alwan_f64 hue_x = NCS_ELEM_x[seg] + t * (NCS_ELEM_x[seg_next] - NCS_ELEM_x[seg]);
        alwan_f64 hue_y = NCS_ELEM_y[seg] + t * (NCS_ELEM_y[seg_next] - NCS_ELEM_y[seg]);

        /* Mix white point with full-chroma hue according to chromaticness */
        cx = NCS_WP_x + c * (hue_x - NCS_WP_x);
        cy = NCS_WP_y + c * (hue_y - NCS_WP_y);
    }

    /* xyY -> XYZ */
    if (cy < ALWAN_LITERAL(1e-12)) {
        xyz->x = xyz->y = xyz->z = ALWAN_LITERAL(0.0);
    } else {
        xyz->y = Y;
        xyz->x = Y * cx / cy;
        xyz->z = Y * (ALWAN_LITERAL(1.0) - cx - cy) / cy;
    }

    return ALWAN_OK;
}

/* Convert XYZ tristimulus values to NCS notation.
 * An accurate inverse requires the full NCS colour atlas (proprietary data).
 * Not implemented. */
int alwan_xyz_to_ncs_f64(char *ncs_notation, size_t notation_size, alwan_xyz_f64 const *xyz) {
    if (!ncs_notation || notation_size < 16 || !xyz) return ALWAN_E_INVALID;
    return ALWAN_E_INVALID;
}

/* ----------------------------------------------------------------
 * Additional RGB Space Definitions
 * ---------------------------------------------------------------- */

/* Primaries + white point data from CSV (generated by gendata/rgb_spaces_lookup.py)
 * 22 spaces x 8 values (rx, ry, gx, gy, bx, by, wx, wy) */
#define RGB_LOOKUP_STRIDE 8
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_f64 const g_rgb_lookup_data[] = {
#include "../data/rgb_spaces_lookup.csv"
};
ALWAN_DIAG_POP

/* RGB space metadata entry (name + transfer functions) */
typedef struct {
    char const *name;
    alwan_transfer_function oetf;
    alwan_transfer_function eotf;
} rgb_space_meta;

/* RGB space metadata -- order matches g_rgb_lookup_data rows */
static rgb_space_meta const g_rgb_spaces_meta[] = {
    {"sRGB",            ALWAN_TF_SRGB,    ALWAN_TF_SRGB},
    {"Adobe RGB",       ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"ProPhoto RGB",    ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"DCI-P3",          ALWAN_TF_GAMMA26,  ALWAN_TF_GAMMA26},
    {"Display P3",      ALWAN_TF_SRGB,    ALWAN_TF_SRGB},
    {"Rec. 2020",       ALWAN_TF_BT2020,  ALWAN_TF_BT2020},
    {"ACES AP0",        ALWAN_TF_LINEAR,  ALWAN_TF_LINEAR},
    {"ACES AP1",        ALWAN_TF_LINEAR,  ALWAN_TF_LINEAR},
    {"ACEScg",          ALWAN_TF_LINEAR,  ALWAN_TF_LINEAR},
    {"Apple RGB",       ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"Best RGB",        ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"Beta RGB",        ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"Bruce RGB",       ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"CIE RGB",         ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"ColorMatch RGB",  ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"Don RGB 4",       ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"ECI RGB v2",      ALWAN_TF_LINEAR,  ALWAN_TF_LINEAR},
    {"Ekta Space PS5",  ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"NTSC RGB",        ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"PAL/SECAM RGB",   ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"SMPTE-C RGB",     ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
    {"Wide Gamut RGB",  ALWAN_TF_GAMMA22,  ALWAN_TF_GAMMA22},
};

static size_t const g_rgb_spaces_count =
    sizeof(g_rgb_spaces_meta) / sizeof(g_rgb_spaces_meta[0]);

/* Map enum value to g_rgb_spaces array index. Returns -1 if not found. */
static int get_rgb_space_index(alwan_rgb_space space) {
    switch (space) {
        case ALWAN_RGB_SPACE_SRGB:            return 0;  /* sRGB */
        case ALWAN_RGB_SPACE_ADOBE_RGB_1998:  return 1;  /* Adobe RGB */
        case ALWAN_RGB_SPACE_PROPHOTO_RGB:    return 2;  /* ProPhoto RGB */
        case ALWAN_RGB_SPACE_DCI_P3:          return 3;  /* DCI-P3 */
        case ALWAN_RGB_SPACE_DISPLAY_P3:      return 4;  /* Display P3 */
        case ALWAN_RGB_SPACE_BT2020:          return 5;  /* Rec. 2020 */
        case ALWAN_RGB_SPACE_ACES2065_1:      return 6;  /* ACES AP0 */
        case ALWAN_RGB_SPACE_ACESCG:          return 8;  /* ACEScg (same as ACES AP1) */
        case ALWAN_RGB_SPACE_APPLE_RGB:       return 9;  /* Apple RGB */
        case ALWAN_RGB_SPACE_BEST_RGB:        return 10; /* Best RGB */
        case ALWAN_RGB_SPACE_BETA_RGB:        return 11; /* Beta RGB */
        case ALWAN_RGB_SPACE_CIE_RGB:         return 13; /* CIE RGB */
        case ALWAN_RGB_SPACE_COLORMATCH_RGB:  return 14; /* ColorMatch RGB */
        case ALWAN_RGB_SPACE_DON_RGB_4:       return 15; /* Don RGB 4 */
        case ALWAN_RGB_SPACE_ECI_RGB_V2:      return 16; /* ECI RGB v2 */
        case ALWAN_RGB_SPACE_EKTA_SPACE_PS5: return 17; /* Ekta Space PS5 */
        case ALWAN_RGB_SPACE_NTSC_1953:       return 18; /* NTSC RGB */
        case ALWAN_RGB_SPACE_PAL_SECAM:       return 19; /* PAL/SECAM RGB */
        case ALWAN_RGB_SPACE_SMPTE_C:         return 20; /* SMPTE-C RGB */
        case ALWAN_RGB_SPACE_ADOBE_WIDE_GAMUT_RGB: return 21; /* Wide Gamut RGB */
        default: return -1;
    }
}

/* Get RGB space primaries and white point by name */
int alwan_rgb_space_by_enum_f64(alwan_f64 primaries[6], alwan_vec2_f64 *white_point, alwan_rgb_space space) {
    if (!primaries || !white_point) {
        return ALWAN_E_INVALID;
    }

    /* Map enum to array index */
    int index = get_rgb_space_index(space);
    if (index < 0 || (size_t)index >= g_rgb_spaces_count) {
        return ALWAN_E_INVALID;
    }

    /* Lookup primaries + white from CSV data */
    alwan_f64 const *row = &g_rgb_lookup_data[index * RGB_LOOKUP_STRIDE];

    /* Copy primaries (first 6 values: rx, ry, gx, gy, bx, by) */
    for (int j = 0; j < 6; j++) {
        primaries[j] = row[j];
    }

    /* Copy white point (values 6 and 7: wx, wy) */
    white_point->v[0] = row[6];
    white_point->v[1] = row[7];

    return ALWAN_OK;
}

/* Get RGB space transfer functions */
int alwan_rgb_space_get_tfs_f64(alwan_transfer_function *oetf, alwan_transfer_function *eotf, alwan_rgb_space space) {
    if (!oetf || !eotf) {
        return ALWAN_E_INVALID;
    }

    /* Map enum to array index */
    int index = get_rgb_space_index(space);
    if (index < 0 || (size_t)index >= g_rgb_spaces_count) {
        return ALWAN_E_INVALID;
    }

    /* Lookup transfer functions from metadata */
    rgb_space_meta const *meta = &g_rgb_spaces_meta[index];

    /* Copy transfer functions */
    *oetf = meta->oetf;
    *eotf = meta->eotf;

    return ALWAN_OK;
}

int alwan_rgb_space_by_enum_f32(alwan_f32 primaries[6], alwan_vec2_f32 *white_point, alwan_rgb_space space) {
    if (!primaries || !white_point) return ALWAN_E_INVALID;
    alwan_f64 pri64[6];
    alwan_vec2_f64 wp64;
    int rc = alwan_rgb_space_by_enum_f64(pri64, &wp64, space);
    if (rc != ALWAN_OK) return rc;
    for (int j = 0; j < 6; j++) primaries[j] = (alwan_f32)pri64[j];
    white_point->v[0] = (alwan_f32)wp64.v[0];
    white_point->v[1] = (alwan_f32)wp64.v[1];
    return ALWAN_OK;
}

int alwan_rgb_space_get_tfs_f32(alwan_transfer_function *oetf, alwan_transfer_function *eotf, alwan_rgb_space space) {
    /* Transfer functions are enum values -- precision-independent. */
    return alwan_rgb_space_get_tfs_f64(oetf, eotf, space);
}
