/* AgX Default Contrast LUT
 * Source: sobotka/AgX (https://github.com/sobotka/AgX)
 * File:   LUTs/AgX_Default_Contrast.spi1d
 * Entries: 4096, domain [0.0, 1.0]
 *
 * Tone curve sigmoid: normalized log2 [0,1] -> display [0,1].
 * Generated by alwan_dev/gendata/data/agx_contrast_lut.py
 */
#define AGX_LUT_SIZE 4096
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_f64 const agx_default_contrast_lut[AGX_LUT_SIZE] = {
#include "agx_default_contrast_lut.csv"
};
ALWAN_DIAG_POP
