/* Blender AgX (EaryChow) picture-formation 3D LUT.
 * Source: extern/agx/blender/luts/AgX_Base_sRGB.cube (57^3, tetrahedral).
 * Generated by alwan_dev/gendata/data/agx_blender.py.
 *
 * Layout: r-fastest, index = ((b*SIZE + g)*SIZE + r)*3 + ch, matching
 * alwan_lut3d_sample_v. Values are power-2.4 encoded display output.
 *
 * Native dual precision (f32 + f64) like every other CSV-imported table; the
 * f32 and f64 blender views each sample their own precision copy.
 */
#define AGX_BLENDER_LUT_SIZE 57
#if ALWAN_WITH_F32
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_f32 const agx_blender_lut3d_f32[AGX_BLENDER_LUT_SIZE * AGX_BLENDER_LUT_SIZE * AGX_BLENDER_LUT_SIZE * 3] = {
#include "agx_blender_lut3d.csv"
};
ALWAN_DIAG_POP
#endif
#if ALWAN_WITH_F64
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_f64 const agx_blender_lut3d_f64[AGX_BLENDER_LUT_SIZE * AGX_BLENDER_LUT_SIZE * AGX_BLENDER_LUT_SIZE * 3] = {
#include "agx_blender_lut3d.csv"
};
ALWAN_DIAG_POP
#endif
