/* SB2383 AgX contrast LUT
 * Source: sobotka/SB2383-Configuration-Generation (vendored under
 *         alwan_dev/extern/agx/sb2383)
 * Entries: 4096 (AGX_LUT_SIZE), domain [0.0, 1.0]
 *
 * Tone curve: Jed Smith tunable sigmoid (calculate_sigmoid), normalized
 * log2 [0,1] -> display [0,1]. SB2383 uses its own log2 range [-10, +6.5]
 * (see AGX_SB2383_LOG2_MIN/MAX in alwan_view.c), distinct from the original
 * AgX. Generated by alwan_dev/gendata/data/agx_sb2383.py.
 *
 * AGX_LUT_SIZE is defined by agx_default_contrast_lut.h, which must be
 * included before this header.
 */
#if ALWAN_WITH_F32
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_f32 const agx_sb2383_contrast_lut_f32[AGX_LUT_SIZE] = {
#include "agx_sb2383_contrast_lut.csv"
};
ALWAN_DIAG_POP
#endif
#if ALWAN_WITH_F64
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_f64 const agx_sb2383_contrast_lut_f64[AGX_LUT_SIZE] = {
#include "agx_sb2383_contrast_lut.csv"
};
ALWAN_DIAG_POP
#endif
