/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Soufiane KHIAT
 * SPDX-License-Identifier: MIT
 *
 * The refractiveindex.info database tables (Polyanskiy; CC0 1.0 Universal Public Domain
 * Dedication; https://refractiveindex.info). Generated by
 * alwan_dev/gendata/data/refractive_index.py from the dated release ZIP pinned in
 * gendata/datasets.py; layout in alwan_data_refractive.h. About 35 MB of CSV source: build
 * with ALWAN_WITH_REFRACTIVE_DATA=0 to leave it out.
 *
 * The tabulated wavelengths and values are spelled as the database spells them and read
 * as float32; the formula coefficients are read as double.
 */

#include "alwan_data_refractive.h"

#if ALWAN_WITH_REFRACTIVE_DATA

ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV

alwan_f32 const alwan__rx_lambda[] = {
#include "refractive/refractive_lambda.csv"
};

alwan_f32 const alwan__rx_values[] = {
#include "refractive/refractive_values.csv"
};

double const alwan__rx_coeffs[] = {
#include "refractive/refractive_coeffs.csv"
};

ALWAN_DIAG_POP

alwan__rx_series const alwan__rx_series_table[] = {
#include "refractive/refractive_series.inc"
};

alwan__rx_page const alwan__rx_pages[] = {
#include "refractive/refractive_pages.inc"
};

size_t const alwan__rx_page_count = sizeof(alwan__rx_pages) / sizeof(alwan__rx_pages[0]);

#endif /* ALWAN_WITH_REFRACTIVE_DATA */
