/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Soufiane KHIAT
 * SPDX-License-Identifier: MIT
 *
 * The physical sky models' tables (layout in alwan_data_sky.h), generated by
 * alwan_dev/gendata/data/sky_models.py:
 *   hosek_wilkie_*.csv  Hosek-Wilkie sky model 1.4a, ArHosekSkyModelData_Spectral.h,
 *                       BSD-3-Clause, Copyright (c) 2012 - 2013, Lukas Hosek and Alexander
 *                       Wilkie (licenses/hosek-wilkie-BSD-3-Clause.txt). Each literal as written there.
 *   preetham_table2.csv Preetham, Shirley and Smits 1999, Table 2.
 *   astm_g173.csv       ASTM G173-03 reference solar spectra (NREL, SMARTS 2.9.2).
 *   bruneton_ozone.csv  Bruneton's demo ozone cross sections, BSD-3-Clause, Copyright (c)
 *                       2017 Eric Bruneton (licenses/bruneton-BSD-3-Clause.txt).
 */

#include "alwan_data_sky.h"

ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV

double const alwan__sky_hw_config[ALWAN__SKY_HW_BANDS * ALWAN__SKY_HW_CONFIG] = {
#include "sky/hosek_wilkie_config.csv"
};

double const alwan__sky_hw_radiance[ALWAN__SKY_HW_BANDS * ALWAN__SKY_HW_RADIANCE] = {
#include "sky/hosek_wilkie_radiance.csv"
};

double const alwan__sky_hw_solar[ALWAN__SKY_HW_BANDS * ALWAN__SKY_HW_SOLAR] = {
#include "sky/hosek_wilkie_solar.csv"
};

double const alwan__sky_hw_limb[ALWAN__SKY_HW_BANDS * ALWAN__SKY_HW_LIMB] = {
#include "sky/hosek_wilkie_limb.csv"
};

double const alwan__sky_preetham[ALWAN__SKY_PREETHAM_ROWS * ALWAN__SKY_PREETHAM_COLS] = {
#include "sky/preetham_table2.csv"
};

double const alwan__sky_g173[ALWAN__SKY_G173_ROWS * ALWAN__SKY_G173_COLS] = {
#include "sky/astm_g173.csv"
};

double const alwan__sky_ozone[ALWAN__SKY_OZONE] = {
#include "sky/bruneton_ozone.csv"
};

ALWAN_DIAG_POP
