/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Soufiane KHIAT
 * SPDX-License-Identifier: MIT
 *
 * The physical sky models' data, generated by alwan_dev/gendata/data/sky_models.py into
 * data/sky/ (SOURCE.txt there names each source). Internal: the public surface is
 * alwan_sky_* and alwan_spd_astm_g173_* in alwan.h. Every table is read by index from
 * whole-number arithmetic or by a search on its wavelengths, never through a
 * float-to-index cast of a coordinate, so none is in the float-coordinate table registry.
 */

#ifndef ALWAN_DATA_SKY_H
#define ALWAN_DATA_SKY_H

#include "../alwan.h"

/* Hosek-Wilkie 1.4a spectral data (BSD-3-Clause, Copyright (c) 2012 - 2013 Lukas Hosek and
 * Alexander Wilkie), eleven bands from 320 nm every 40 nm, band-major:
 *   config    1080 a band: albedo (2) x turbidity (10) x elevation control point (6) x 9
 *   radiance   120 a band: albedo (2) x turbidity (10) x control point (6)
 *   solar     1800 a band: turbidity (10) x piece (45) x order (4)
 *   limb         6 a band: the limb darkening polynomial */
enum {
    ALWAN__SKY_HW_BANDS = 11,
    ALWAN__SKY_HW_CONFIG = 1080,
    ALWAN__SKY_HW_RADIANCE = 120,
    ALWAN__SKY_HW_SOLAR = 1800,
    ALWAN__SKY_HW_LIMB = 6,
    ALWAN__SKY_PREETHAM_ROWS = 41,   /* 380-780 nm every 10 nm */
    ALWAN__SKY_PREETHAM_COLS = 9,    /* lambda, K, S0, S1, S2, sun, k_o, k_wa, k_g; -1 = none */
    ALWAN__SKY_G173_ROWS = 2002,     /* 280-4000 nm, non-uniform */
    ALWAN__SKY_G173_COLS = 4,        /* lambda, extraterrestrial, global tilt, direct */
    ALWAN__SKY_OZONE = 48            /* 360-830 nm every 10 nm, m^2 */
};

extern double const alwan__sky_hw_config[ALWAN__SKY_HW_BANDS * ALWAN__SKY_HW_CONFIG];
extern double const alwan__sky_hw_radiance[ALWAN__SKY_HW_BANDS * ALWAN__SKY_HW_RADIANCE];
extern double const alwan__sky_hw_solar[ALWAN__SKY_HW_BANDS * ALWAN__SKY_HW_SOLAR];
extern double const alwan__sky_hw_limb[ALWAN__SKY_HW_BANDS * ALWAN__SKY_HW_LIMB];
extern double const alwan__sky_preetham[ALWAN__SKY_PREETHAM_ROWS * ALWAN__SKY_PREETHAM_COLS];
extern double const alwan__sky_g173[ALWAN__SKY_G173_ROWS * ALWAN__SKY_G173_COLS];
extern double const alwan__sky_ozone[ALWAN__SKY_OZONE];

#endif /* ALWAN_DATA_SKY_H */
