/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Soufiane KHIAT
 * SPDX-License-Identifier: MIT
 *
 * The refractiveindex.info database (Polyanskiy, CC0 1.0) as alwan's tables, generated by
 * alwan_dev/gendata/data/refractive_index.py into data/refractive/. Internal: the public
 * surface is alwan_refractive_index_* in alwan.h. Present only when
 * ALWAN_WITH_REFRACTIVE_DATA is 1 (the default).
 *
 * A page (one measurement or fit of one material) has an n series and a k series, either
 * of which may be absent (-1). A series is tabulated (formula 0: count wavelengths at
 * alwan__rx_lambda[lambda_offset], values at alwan__rx_values[value_offset]) or one of the
 * database's nine dispersion formulas for n (coefficients at alwan__rx_coeffs). Wavelengths
 * are in micrometres, as the database writes them; tabulated wavelengths ascend strictly.
 * Tables are read by a binary search on the wavelength, never through a float-to-index
 * cast, so they are not part of the float-coordinate table registry.
 */

#ifndef ALWAN_DATA_REFRACTIVE_H
#define ALWAN_DATA_REFRACTIVE_H

#include "../alwan.h"

#if ALWAN_WITH_REFRACTIVE_DATA

typedef struct {
    int quantity;        /* 0 n, 1 k */
    int formula;         /* 0 tabulated, 1..9 the database's dispersion formulas */
    int lambda_offset;
    int value_offset;
    int count;
    int coeff_offset;
    int coeff_count;
    double lo_um, hi_um; /* the series' wavelength range */
} alwan__rx_series;

typedef struct {
    char const *id;        /* "shelf/book/page" */
    char const *shelf, *book, *page;
    char const *material;  /* the book's display name */
    char const *name;      /* the page's display name */
    char const *reference; /* plain text */
    int n_series, k_series;
} alwan__rx_page;

extern alwan_f32 const alwan__rx_lambda[];
extern alwan_f32 const alwan__rx_values[];
extern double const alwan__rx_coeffs[];
extern alwan__rx_series const alwan__rx_series_table[];
extern alwan__rx_page const alwan__rx_pages[];
extern size_t const alwan__rx_page_count;

#endif /* ALWAN_WITH_REFRACTIVE_DATA */

#endif /* ALWAN_DATA_REFRACTIVE_H */
