/*
 * Alwan - Pure C colour science library
 * Copyright (c) 2025 Alwan Contributors
 * SPDX-License-Identifier: MIT
 *
 * M10: Light Quality & CCT
 * CCT estimation (McCamy, Robertson) and CRI
 */

#include "alwan.h"
#include "alwan_internal.h"
#include <math.h>

/* ----------------------------------------------------------------
 * CCT: Correlated Color Temperature
 * ---------------------------------------------------------------- */

/* McCamy's approximation for CCT from CIE 1931 xy coordinates
 * Fast approximation, ~2% accuracy above 2800K
 * Formula: CCT = 437n³ + 3601n² + 6861n + 5517
 * where n = (x - 0.3320) / (0.1858 - y)
 */
alwan_scalar alwan_cct_mccamy_xy(alwan_vec3 const *xy) {
    if (!xy) {
        return ALWAN_LITERAL(-1.0);
    }

    alwan_scalar x = xy->v[0];
    alwan_scalar y = xy->v[1];

    /* Epicenter of the Planckian locus in CIE xy */
    alwan_scalar const x_e = ALWAN_LITERAL(0.3320);
    alwan_scalar const y_e = ALWAN_LITERAL(0.1858);

    /* Avoid division by zero */
    alwan_scalar denom = y_e - y;
    if (ALWAN_FABS(denom) < ALWAN_EPSILON) {
        return ALWAN_LITERAL(-1.0);
    }

    alwan_scalar n = (x - x_e) / denom;
    alwan_scalar n2 = n * n;
    alwan_scalar n3 = n2 * n;

    /* McCamy's formula: CCT = 437n³ + 3601n² + 6861n + 5517 */
    alwan_scalar cct = ALWAN_LITERAL(437.0) * n3 +
                       ALWAN_LITERAL(3601.0) * n2 +
                       ALWAN_LITERAL(6861.0) * n +
                       ALWAN_LITERAL(5517.0);

    return cct;
}

/* Robertson's method for CCT from CIE 1960 UCS uv coordinates
 * Uses lookup table of Planckian locus points
 * More accurate than McCamy, especially at low CCT
 */

/* Robertson lookup table: Planckian locus in CIE 1960 UCS
 * Format: cct,u,v,du,dv per row (22 points from 1000K to 20000K)
 * Generated by generate_data.ps1 from colour-science library */
ALWAN_DIAG_PUSH
ALWAN_DIAG_DISABLE_FLOAT_CONV
static alwan_scalar const robertson_table_data[] = {
#include "data/fixtures/robertson_cct_locus.csv"
};
ALWAN_DIAG_POP

#define ROBERTSON_TABLE_SIZE 22
#define ROBERTSON_TABLE_STRIDE 5  /* cct, u, v, du, dv */

/* Helper to access Robertson table entries */
static inline void robertson_get_point(size_t idx,
                                        alwan_scalar *cct,
                                        alwan_scalar *u,
                                        alwan_scalar *v,
                                        alwan_scalar *du,
                                        alwan_scalar *dv) {
    size_t offset = idx * ROBERTSON_TABLE_STRIDE;
    *cct = robertson_table_data[offset + 0];
    *u   = robertson_table_data[offset + 1];
    *v   = robertson_table_data[offset + 2];
    *du  = robertson_table_data[offset + 3];
    *dv  = robertson_table_data[offset + 4];
}

alwan_scalar alwan_cct_robertson_xy(alwan_vec3 const *xy) {
    if (!xy) {
        return ALWAN_LITERAL(-1.0);
    }

    alwan_scalar x = xy->v[0];
    alwan_scalar y = xy->v[1];

    /* Convert CIE 1931 xy to CIE 1960 UCS uv */
    alwan_scalar denom = ALWAN_LITERAL(12.0) * y - ALWAN_LITERAL(2.0) * x + ALWAN_LITERAL(3.0);
    if (ALWAN_FABS(denom) < ALWAN_EPSILON) {
        return ALWAN_LITERAL(-1.0);
    }

    alwan_scalar u = (ALWAN_LITERAL(4.0) * x) / denom;
    alwan_scalar v = (ALWAN_LITERAL(6.0) * y) / denom;

    /* Find closest point on the Planckian locus by checking all segments */
    alwan_scalar min_dist = ALWAN_LITERAL(1e10);
    size_t best_idx = 0;
    alwan_scalar best_t = ALWAN_LITERAL(0.0);

    for (size_t i = 0; i < ROBERTSON_TABLE_SIZE - 1; i++) {
        alwan_scalar cct1, u1, v1, du1, dv1;
        alwan_scalar cct2, u2, v2, du2, dv2;
        robertson_get_point(i, &cct1, &u1, &v1, &du1, &dv1);
        robertson_get_point(i + 1, &cct2, &u2, &v2, &du2, &dv2);

        /* Vector from p1 to p2 */
        alwan_scalar du_seg = u2 - u1;
        alwan_scalar dv_seg = v2 - v1;

        /* Vector from p1 to test point */
        alwan_scalar du_test = u - u1;
        alwan_scalar dv_test = v - v1;

        alwan_scalar seg_len_sq = du_seg * du_seg + dv_seg * dv_seg;
        if (seg_len_sq < ALWAN_EPSILON) {
            continue;
        }

        /* Project test point onto line segment */
        alwan_scalar t = (du_test * du_seg + dv_test * dv_seg) / seg_len_sq;
        t = alwan_clamp(t, ALWAN_LITERAL(0.0), ALWAN_LITERAL(1.0));

        /* Find the closest point on the segment */
        alwan_scalar u_proj = u1 + t * du_seg;
        alwan_scalar v_proj = v1 + t * dv_seg;

        /* Calculate actual distance to this point */
        alwan_scalar du_diff = u - u_proj;
        alwan_scalar dv_diff = v - v_proj;
        alwan_scalar dist = ALWAN_SQRT(du_diff * du_diff + dv_diff * dv_diff);

        if (dist < min_dist) {
            min_dist = dist;
            best_idx = i;
            best_t = t;
        }
    }

    /* Interpolate CCT using the best segment and parameter */
    alwan_scalar cct1, u1, v1, du1, dv1;
    alwan_scalar cct2, u2, v2, du2, dv2;
    robertson_get_point(best_idx, &cct1, &u1, &v1, &du1, &dv1);
    robertson_get_point(best_idx + 1, &cct2, &u2, &v2, &du2, &dv2);

    /* Linear interpolation of CCT */
    alwan_scalar cct = cct1 + best_t * (cct2 - cct1);

    return cct;
}

/* ----------------------------------------------------------------
 * CRI: Color Rendering Index
 * ---------------------------------------------------------------- */

/* CRI Ra calculation requires:
 * 1. Test SPD
 * 2. Reference illuminant (blackbody or daylight at same CCT)
 * 3. 8 TCS (Test Color Samples) reflectances
 * 4. CIE 1931 2° observer
 *
 * This is a complex calculation that requires spectral integration.
 * For now, return a placeholder that indicates this feature is not yet implemented.
 */
// TODO
alwan_scalar alwan_cri_ra(alwan_spd const *test_spd) {
    if (!test_spd) {
        return ALWAN_LITERAL(-1.0);
    }

    /* CRI calculation requires:
     * - Reference illuminant generation at matching CCT
     * - TCS reflectance data
     * - Chromatic adaptation
     * - Special CRI color space (U*V*W*)
     * This is beyond the scope of initial M10 implementation.
     */
    return ALWAN_LITERAL(-2.0);  /* Not yet implemented */
}
