#!/usr/bin/env python3
"""Generate a Windows module-definition (.def) listing every defined, external
alwan* symbol, so the Sharpmake/MSVC *_Dll configurations export the full API.

This mirrors CMake's WINDOWS_EXPORT_ALL_SYMBOLS: it dumps the actual *compiled*
object symbols (via dumpbin) rather than parsing the header, so the export set
matches the build exactly -- no phantom symbols (declared-but-not-compiled
facades) and no missing ones. Run as a Sharpmake EventPreLink step with the
intermediate object directory.

Usage: python gen_exports_def.py <obj_dir> <out.def>

If <obj_dir> has no .obj files or dumpbin is unavailable (e.g. a bare checkout
outside a VC environment), the existing <out.def> is left untouched so the path
stays valid for project generation; the next real build refreshes it.
"""
import os
import re
import sys
import glob
import subprocess


def dump_symbols(objs):
    names = set()
    # Batch to stay under the command-line length limit (~32k chars).
    for i in range(0, len(objs), 40):
        batch = objs[i:i + 40]
        try:
            out = subprocess.run(['dumpbin', '/SYMBOLS', *batch],
                                  capture_output=True, text=True, check=True).stdout
        except (FileNotFoundError, subprocess.CalledProcessError):
            return None
        for line in out.splitlines():
            # e.g. "008 0 SECT3 notype () External | alwan_create"
            if 'External' not in line or 'UNDEF' in line:
                continue
            # Functions only. dumpbin spells a function "notype ()" and a data
            # object "notype" with no parens. The embedded tables in
            # src/alwan/data are external so the declaration header can enforce
            # their extents at compile time, but they are implementation, not
            # API: the readers are the API. Exporting them would also need the
            # DATA keyword to import correctly, and would pin a 60 MB byte
            # layout into the DLL's ABI for nothing.
            if 'notype ()' not in line:
                continue
            m = re.search(r'\|\s+(alwan\w+)\s*$', line)
            if m:
                names.add(m.group(1))
    return names


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_exports_def.py <obj_dir> <out.def>")
    obj_dir, out = sys.argv[1], sys.argv[2]
    objs = glob.glob(os.path.join(obj_dir, '*.obj'))
    if not objs:
        print(f"gen_exports_def: no .obj in {obj_dir}; leaving {out} as-is")
        return
    names = dump_symbols(objs)
    if not names:
        print(f"gen_exports_def: dumpbin unavailable/failed; leaving {out} as-is")
        return
    with open(out, 'w', encoding='utf-8', newline='\r\n') as f:
        f.write("; Auto-generated by tools/gen_exports_def.py from compiled objects.\n")
        f.write("; Public alwan exports for the *_Dll (shared) configurations.\n")
        f.write("EXPORTS\n")
        for n in sorted(names):
            f.write(f"    {n}\n")
    print(f"gen_exports_def: wrote {len(names)} exports -> {out}")


if __name__ == '__main__':
    main()
