name: Windows f32
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - run: cmake -B build -DALWAN_SCALAR_IS_FLOAT=ON -DALWAN_ENABLE_WARNINGS=ON -DALWAN_WARNINGS_AS_ERRORS=OFF -DALWAN_BUILD_BENCH=ON
      - run: cmake --build build --config Release
      - run: ./build/bench/Release/alwan_bench.exe
